var data = {lines:[
{"lineNum":"    1","line":"#!/usr/bin/env bats"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":""},
{"lineNum":"    4","line":"# Make executables ./tests/../ visible to PATH"},
{"lineNum":"    5","line":"PATH=\"/home/aveey/tom-project/shell-scripts/tests/batspp-only/../:$PATH\"","class":"lineCov","hits":"23","order":"333","possible_hits":"0",},
{"lineNum":"    6","line":""},
{"lineNum":"    7","line":"# Source files"},
{"lineNum":"    8","line":"shopt -s expand_aliases","class":"lineCov","hits":"23","order":"349","possible_hits":"0",},
{"lineNum":"    9","line":""},
{"lineNum":"   10","line":""},
{"lineNum":"   11","line":"test_test0() { bats_test_begin \"test0\";"},
{"lineNum":"   12","line":"\ttest_folder=$(echo /tmp/test0-$$)","class":"lineCov","hits":"4","order":"446","possible_hits":"0",},
{"lineNum":"   13","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"447","possible_hits":"0",},
{"lineNum":"   14","line":""},
{"lineNum":"   15","line":"\tbind \'set enable-bracketed-paste off\'","class":"lineCov","hits":"2","order":"448","possible_hits":"0",},
{"lineNum":"   16","line":"}"},
{"lineNum":"   17","line":""},
{"lineNum":"   18","line":""},
{"lineNum":"   19","line":"test_test1() { bats_test_begin \"test1\";"},
{"lineNum":"   20","line":"\ttest_folder=$(echo /tmp/test1-$$)","class":"lineCov","hits":"4","order":"487","possible_hits":"0",},
{"lineNum":"   21","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"488","possible_hits":"0",},
{"lineNum":"   22","line":""},
{"lineNum":"   23","line":"}"},
{"lineNum":"   24","line":""},
{"lineNum":"   25","line":""},
{"lineNum":"   26","line":"test_test2() { bats_test_begin \"test2\";"},
{"lineNum":"   27","line":"\ttest_folder=$(echo /tmp/test2-$$)","class":"lineCov","hits":"4","order":"489","possible_hits":"0",},
{"lineNum":"   28","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"490","possible_hits":"0",},
{"lineNum":"   29","line":""},
{"lineNum":"   30","line":"\tunalias -a","class":"lineCov","hits":"2","order":"491","possible_hits":"0",},
{"lineNum":"   31","line":"\talias | wc -l","class":"lineCov","hits":"4","order":"492","possible_hits":"0",},
{"lineNum":"   32","line":"\tfor f in $(typeset -f | egrep \'^\\w+\'); do unset -f $f; done","class":"lineCov","hits":"66","order":"493","possible_hits":"0",},
{"lineNum":"   33","line":"\tactual=$(test2-assert4-actual)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   34","line":"\texpected=$(test2-assert4-expected)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   35","line":"\techo \"========== actual ==========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   36","line":"\techo \"$actual\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   37","line":"\techo \"========= expected =========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   38","line":"\techo \"$expected\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   39","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   40","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   41","line":""},
{"lineNum":"   42","line":"}"},
{"lineNum":"   43","line":""},
{"lineNum":"   44","line":"function test2-assert4-actual () {"},
{"lineNum":"   45","line":"\ttypeset -f | egrep \'^\\w+\' | wc -l","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   46","line":"}"},
{"lineNum":"   47","line":"function test2-assert4-expected () {"},
{"lineNum":"   48","line":"\techo -e \'00\'","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   49","line":"}"},
{"lineNum":"   50","line":""},
{"lineNum":"   51","line":"test_test3() { bats_test_begin \"test3\";"},
{"lineNum":"   52","line":"\ttest_folder=$(echo /tmp/test3-$$)","class":"lineCov","hits":"4","order":"585","possible_hits":"0",},
{"lineNum":"   53","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"586","possible_hits":"0",},
{"lineNum":"   54","line":""},
{"lineNum":"   55","line":"\ttemp_dir=$TMP/test-3214","class":"lineCov","hits":"2","order":"587","possible_hits":"0",},
{"lineNum":"   56","line":"\tcd \"$temp_dir\"","class":"lineCov","hits":"4","order":"588","possible_hits":"0",},
{"lineNum":"   57","line":"}"},
{"lineNum":"   58","line":""},
{"lineNum":"   59","line":""},
{"lineNum":"   60","line":"test_test4() { bats_test_begin \"test4\";"},
{"lineNum":"   61","line":"\ttest_folder=$(echo /tmp/test4-$$)","class":"lineCov","hits":"4","order":"590","possible_hits":"0",},
{"lineNum":"   62","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"591","possible_hits":"0",},
{"lineNum":"   63","line":""},
{"lineNum":"   64","line":"\tactual=$(test4-assert1-actual)","class":"lineCov","hits":"4","order":"592","possible_hits":"0",},
{"lineNum":"   65","line":"\texpected=$(test4-assert1-expected)","class":"lineCov","hits":"4","order":"594","possible_hits":"0",},
{"lineNum":"   66","line":"\techo \"========== actual ==========\"","class":"lineCov","hits":"2","order":"596","possible_hits":"0",},
{"lineNum":"   67","line":"\techo \"$actual\" | hexview.perl","class":"lineCov","hits":"4","order":"597","possible_hits":"0",},
{"lineNum":"   68","line":"\techo \"========= expected =========\"","class":"lineCov","hits":"2","order":"598","possible_hits":"0",},
{"lineNum":"   69","line":"\techo \"$expected\" | hexview.perl","class":"lineCov","hits":"4","order":"599","possible_hits":"0",},
{"lineNum":"   70","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"600","possible_hits":"0",},
{"lineNum":"   71","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineCov","hits":"4","order":"601","possible_hits":"0",},
{"lineNum":"   72","line":""},
{"lineNum":"   73","line":"}"},
{"lineNum":"   74","line":""},
{"lineNum":"   75","line":"function test4-assert1-actual () {"},
{"lineNum":"   76","line":"\ttypeset -f | egrep \'^\\w+\' | wc -l","class":"lineCov","hits":"6","order":"593","possible_hits":"0",},
{"lineNum":"   77","line":"}"},
{"lineNum":"   78","line":"function test4-assert1-expected () {"},
{"lineNum":"   79","line":"\techo -e \'10\'","class":"lineCov","hits":"2","order":"595","possible_hits":"0",},
{"lineNum":"   80","line":"}"},
{"lineNum":"   81","line":""},
{"lineNum":"   82","line":"test_test5() { bats_test_begin \"test5\";"},
{"lineNum":"   83","line":"\ttest_folder=$(echo /tmp/test5-$$)","class":"lineCov","hits":"4","order":"602","possible_hits":"0",},
{"lineNum":"   84","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"603","possible_hits":"0",},
{"lineNum":"   85","line":""},
{"lineNum":"   86","line":"\tsource $BIN_DIR/tomohara-aliases.bash","class":"lineCov","hits":"2","order":"604","possible_hits":"0",},
{"lineNum":"   87","line":"}"},
{"lineNum":"   88","line":""},
{"lineNum":"   89","line":""},
{"lineNum":"   90","line":"test_test6() { bats_test_begin \"test6\";"},
{"lineNum":"   91","line":"\ttest_folder=$(echo /tmp/test6-$$)","class":"lineCov","hits":"4","order":"606","possible_hits":"0",},
{"lineNum":"   92","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"607","possible_hits":"0",},
{"lineNum":"   93","line":""},
{"lineNum":"   94","line":"}"},
{"lineNum":"   95","line":""},
{"lineNum":"   96","line":""},
{"lineNum":"   97","line":"test_test7() { bats_test_begin \"test7\";"},
{"lineNum":"   98","line":"\ttest_folder=$(echo /tmp/test7-$$)","class":"lineCov","hits":"4","order":"608","possible_hits":"0",},
{"lineNum":"   99","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"609","possible_hits":"0",},
{"lineNum":"  100","line":""},
{"lineNum":"  101","line":"}"},
{"lineNum":"  102","line":""},
{"lineNum":"  103","line":""},
{"lineNum":"  104","line":"test_test8() { bats_test_begin \"test8\";"},
{"lineNum":"  105","line":"\ttest_folder=$(echo /tmp/test8-$$)","class":"lineCov","hits":"4","order":"610","possible_hits":"0",},
{"lineNum":"  106","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"611","possible_hits":"0",},
{"lineNum":"  107","line":""},
{"lineNum":"  108","line":"}"},
{"lineNum":"  109","line":""},
{"lineNum":"  110","line":""},
{"lineNum":"  111","line":"test_test9() { bats_test_begin \"test9\";"},
{"lineNum":"  112","line":"\ttest_folder=$(echo /tmp/test9-$$)","class":"lineCov","hits":"4","order":"612","possible_hits":"0",},
{"lineNum":"  113","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"613","possible_hits":"0",},
{"lineNum":"  114","line":""},
{"lineNum":"  115","line":"}"},
{"lineNum":"  116","line":""},
{"lineNum":"  117","line":""},
{"lineNum":"  118","line":"test_test10() { bats_test_begin \"test10\";"},
{"lineNum":"  119","line":"\ttest_folder=$(echo /tmp/test10-$$)","class":"lineCov","hits":"4","order":"614","possible_hits":"0",},
{"lineNum":"  120","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"615","possible_hits":"0",},
{"lineNum":"  121","line":""},
{"lineNum":"  122","line":"\trm -rf ./* > /dev/null","class":"lineCov","hits":"2","order":"616","possible_hits":"0",},
{"lineNum":"  123","line":"\tprintf \"This is Line A.\\n1 2 3 4 5\" > file_a.txt","class":"lineCov","hits":"2","order":"617","possible_hits":"0",},
{"lineNum":"  124","line":"\tprintf \"This is Line B.\\n1 3 5 7 9\" > file_b.txt","class":"lineCov","hits":"2","order":"618","possible_hits":"0",},
{"lineNum":"  125","line":"}"},
{"lineNum":"  126","line":""},
{"lineNum":"  127","line":""},
{"lineNum":"  128","line":"test_test11() { bats_test_begin \"test11\";"},
{"lineNum":"  129","line":"\ttest_folder=$(echo /tmp/test11-$$)","class":"lineCov","hits":"4","order":"619","possible_hits":"0",},
{"lineNum":"  130","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"620","possible_hits":"0",},
{"lineNum":"  131","line":""},
{"lineNum":"  132","line":"\tactual=$(test11-assert1-actual)","class":"lineCov","hits":"7","order":"621","possible_hits":"0",},
{"lineNum":"  133","line":"\texpected=$(test11-assert1-expected)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  134","line":"\techo \"========== actual ==========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  135","line":"\techo \"$actual\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  136","line":"\techo \"========= expected =========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  137","line":"\techo \"$expected\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  138","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  139","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  140","line":""},
{"lineNum":"  141","line":"}"},
{"lineNum":"  142","line":""},
{"lineNum":"  143","line":"function test11-assert1-actual () {"},
{"lineNum":"  144","line":"\tintersection ./file_a.txt ./file_b.txt","class":"lineCov","hits":"4","order":"622","possible_hits":"0",},
{"lineNum":"  145","line":"}"},
{"lineNum":"  146","line":"function test11-assert1-expected () {"},
{"lineNum":"  147","line":"\techo -e \'ThisisLine135\'","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  148","line":"}"},
{"lineNum":"  149","line":""},
{"lineNum":"  150","line":"test_test12() { bats_test_begin \"test12\";"},
{"lineNum":"  151","line":"\ttest_folder=$(echo /tmp/test12-$$)","class":"lineCov","hits":"4","order":"623","possible_hits":"0",},
{"lineNum":"  152","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"624","possible_hits":"0",},
{"lineNum":"  153","line":""},
{"lineNum":"  154","line":"\tline-intersection ./file_b.txt ./file_a.txt","class":"lineCov","hits":"4","order":"625","possible_hits":"0",},
{"lineNum":"  155","line":"}"},
{"lineNum":"  156","line":""},
{"lineNum":"  157","line":""},
{"lineNum":"  158","line":"test_test13() { bats_test_begin \"test13\";"},
{"lineNum":"  159","line":"\ttest_folder=$(echo /tmp/test13-$$)","class":"lineCov","hits":"4","order":"626","possible_hits":"0",},
{"lineNum":"  160","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"627","possible_hits":"0",},
{"lineNum":"  161","line":""},
{"lineNum":"  162","line":"\tactual=$(test13-assert1-actual)","class":"lineCov","hits":"7","order":"628","possible_hits":"0",},
{"lineNum":"  163","line":"\texpected=$(test13-assert1-expected)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  164","line":"\techo \"========== actual ==========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  165","line":"\techo \"$actual\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  166","line":"\techo \"========= expected =========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  167","line":"\techo \"$expected\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  168","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  169","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  170","line":""},
{"lineNum":"  171","line":"}"},
{"lineNum":"  172","line":""},
{"lineNum":"  173","line":"function test13-assert1-actual () {"},
{"lineNum":"  174","line":"\tdifference ./file_a.txt ./file_b.txt","class":"lineCov","hits":"4","order":"629","possible_hits":"0",},
{"lineNum":"  175","line":"}"},
{"lineNum":"  176","line":"function test13-assert1-expected () {"},
{"lineNum":"  177","line":"\techo -e \'24A.\'","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  178","line":"}"},
{"lineNum":"  179","line":""},
{"lineNum":"  180","line":"test_test14() { bats_test_begin \"test14\";"},
{"lineNum":"  181","line":"\ttest_folder=$(echo /tmp/test14-$$)","class":"lineCov","hits":"4","order":"630","possible_hits":"0",},
{"lineNum":"  182","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"631","possible_hits":"0",},
{"lineNum":"  183","line":""},
{"lineNum":"  184","line":"\tactual=$(test14-assert1-actual)","class":"lineCov","hits":"7","order":"632","possible_hits":"0",},
{"lineNum":"  185","line":"\texpected=$(test14-assert1-expected)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  186","line":"\techo \"========== actual ==========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  187","line":"\techo \"$actual\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  188","line":"\techo \"========= expected =========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  189","line":"\techo \"$expected\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  190","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  191","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  192","line":""},
{"lineNum":"  193","line":"}"},
{"lineNum":"  194","line":""},
{"lineNum":"  195","line":"function test14-assert1-actual () {"},
{"lineNum":"  196","line":"\tline-difference ./file_b.txt ./file_a.txt","class":"lineCov","hits":"4","order":"633","possible_hits":"0",},
{"lineNum":"  197","line":"}"},
{"lineNum":"  198","line":"function test14-assert1-expected () {"},
{"lineNum":"  199","line":"\techo -e \'1 3 5 7 9This is Line B.\'","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  200","line":"}"},
{"lineNum":"  201","line":""},
{"lineNum":"  202","line":"test_test15() { bats_test_begin \"test15\";"},
{"lineNum":"  203","line":"\ttest_folder=$(echo /tmp/test15-$$)","class":"lineCov","hits":"4","order":"634","possible_hits":"0",},
{"lineNum":"  204","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"635","possible_hits":"0",},
{"lineNum":"  205","line":""},
{"lineNum":"  206","line":"\tactual=$(test15-assert1-actual)","class":"lineCov","hits":"4","order":"636","possible_hits":"0",},
{"lineNum":"  207","line":"\texpected=$(test15-assert1-expected)","class":"lineCov","hits":"4","order":"638","possible_hits":"0",},
{"lineNum":"  208","line":"\techo \"========== actual ==========\"","class":"lineCov","hits":"2","order":"640","possible_hits":"0",},
{"lineNum":"  209","line":"\techo \"$actual\" | hexview.perl","class":"lineCov","hits":"4","order":"641","possible_hits":"0",},
{"lineNum":"  210","line":"\techo \"========= expected =========\"","class":"lineCov","hits":"2","order":"642","possible_hits":"0",},
{"lineNum":"  211","line":"\techo \"$expected\" | hexview.perl","class":"lineCov","hits":"4","order":"643","possible_hits":"0",},
{"lineNum":"  212","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"644","possible_hits":"0",},
{"lineNum":"  213","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineCov","hits":"4","order":"645","possible_hits":"0",},
{"lineNum":"  214","line":""},
{"lineNum":"  215","line":"}"},
{"lineNum":"  216","line":""},
{"lineNum":"  217","line":"function test15-assert1-actual () {"},
{"lineNum":"  218","line":"\tprintf \"Hi Mom, \\rI am using Ubuntu\\n\"","class":"lineCov","hits":"2","order":"637","possible_hits":"0",},
{"lineNum":"  219","line":"}"},
{"lineNum":"  220","line":"function test15-assert1-expected () {"},
{"lineNum":"  221","line":"\techo -e \'I am using Ubuntu\'","class":"lineCov","hits":"2","order":"639","possible_hits":"0",},
{"lineNum":"  222","line":"}"},
{"lineNum":"  223","line":""},
{"lineNum":"  224","line":"test_test16() { bats_test_begin \"test16\";"},
{"lineNum":"  225","line":"\ttest_folder=$(echo /tmp/test16-$$)","class":"lineCov","hits":"4","order":"646","possible_hits":"0",},
{"lineNum":"  226","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"647","possible_hits":"0",},
{"lineNum":"  227","line":""},
{"lineNum":"  228","line":"\tactual=$(test16-assert1-actual)","class":"lineCov","hits":"7","order":"648","possible_hits":"0",},
{"lineNum":"  229","line":"\texpected=$(test16-assert1-expected)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  230","line":"\techo \"========== actual ==========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  231","line":"\techo \"$actual\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  232","line":"\techo \"========= expected =========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  233","line":"\techo \"$expected\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  234","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  235","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  236","line":""},
{"lineNum":"  237","line":"}"},
{"lineNum":"  238","line":""},
{"lineNum":"  239","line":"function test16-assert1-actual () {"},
{"lineNum":"  240","line":"\tprintf \"Hi Mom,\\r I am using Ubuntu\\n\" | remove-cr","class":"lineCov","hits":"6","order":"649","possible_hits":"0",},
{"lineNum":"  241","line":"}"},
{"lineNum":"  242","line":"function test16-assert1-expected () {"},
{"lineNum":"  243","line":"\techo -e \'Hi Mom, I am using Ubuntu\'","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  244","line":"}"},
{"lineNum":"  245","line":""},
{"lineNum":"  246","line":"test_test17() { bats_test_begin \"test17\";"},
{"lineNum":"  247","line":"\ttest_folder=$(echo /tmp/test17-$$)","class":"lineCov","hits":"4","order":"650","possible_hits":"0",},
{"lineNum":"  248","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"651","possible_hits":"0",},
{"lineNum":"  249","line":""},
{"lineNum":"  250","line":"\tactual=$(test17-assert1-actual)","class":"lineCov","hits":"7","order":"652","possible_hits":"0",},
{"lineNum":"  251","line":"\texpected=$(test17-assert1-expected)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  252","line":"\techo \"========== actual ==========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  253","line":"\techo \"$actual\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  254","line":"\techo \"========= expected =========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  255","line":"\techo \"$expected\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  256","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  257","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  258","line":""},
{"lineNum":"  259","line":"}"},
{"lineNum":"  260","line":""},
{"lineNum":"  261","line":"function test17-assert1-actual () {"},
{"lineNum":"  262","line":"\tprintf \"Hi Mom,\\r I am using Ubuntu\\n\" | alt-remove-cr","class":"lineCov","hits":"6","order":"653","possible_hits":"0",},
{"lineNum":"  263","line":"}"},
{"lineNum":"  264","line":"function test17-assert1-expected () {"},
{"lineNum":"  265","line":"\techo -e \'Hi Mom, I am using Ubuntu\'","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  266","line":"}"},
{"lineNum":"  267","line":""},
{"lineNum":"  268","line":"test_test18() { bats_test_begin \"test18\";"},
{"lineNum":"  269","line":"\ttest_folder=$(echo /tmp/test18-$$)","class":"lineCov","hits":"4","order":"654","possible_hits":"0",},
{"lineNum":"  270","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"655","possible_hits":"0",},
{"lineNum":"  271","line":""},
{"lineNum":"  272","line":"}"},
{"lineNum":"  273","line":""},
{"lineNum":"  274","line":""},
{"lineNum":"  275","line":"test_test19() { bats_test_begin \"test19\";"},
{"lineNum":"  276","line":"\ttest_folder=$(echo /tmp/test19-$$)","class":"lineCov","hits":"4","order":"656","possible_hits":"0",},
{"lineNum":"  277","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"657","possible_hits":"0",},
{"lineNum":"  278","line":""},
{"lineNum":"  279","line":"\tpwd","class":"lineCov","hits":"2","order":"658","possible_hits":"0",},
{"lineNum":"  280","line":"\trm -rf ./* > /dev/null","class":"lineCov","hits":"2","order":"659","possible_hits":"0",},
{"lineNum":"  281","line":"\tprintf \"Hi Mom,\\nThs is the use of printf\\nI can use a backslash n to start a new line.\\n1\\n2\\n3\"> abc-test.txt","class":"lineCov","hits":"2","order":"660","possible_hits":"0",},
{"lineNum":"  282","line":"}"},
{"lineNum":"  283","line":""},
{"lineNum":"  284","line":""},
{"lineNum":"  285","line":"test_test20() { bats_test_begin \"test20\";"},
{"lineNum":"  286","line":"\ttest_folder=$(echo /tmp/test20-$$)","class":"lineCov","hits":"4","order":"661","possible_hits":"0",},
{"lineNum":"  287","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"662","possible_hits":"0",},
{"lineNum":"  288","line":""},
{"lineNum":"  289","line":"\tactual=$(test20-assert1-actual)","class":"lineCov","hits":"7","order":"663","possible_hits":"0",},
{"lineNum":"  290","line":"\texpected=$(test20-assert1-expected)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  291","line":"\techo \"========== actual ==========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  292","line":"\techo \"$actual\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  293","line":"\techo \"========= expected =========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  294","line":"\techo \"$expected\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  295","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  296","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  297","line":""},
{"lineNum":"  298","line":"}"},
{"lineNum":"  299","line":""},
{"lineNum":"  300","line":"function test20-assert1-actual () {"},
{"lineNum":"  301","line":"\tshow-line 3 abc-test.txt","class":"lineCov","hits":"4","order":"664","possible_hits":"0",},
{"lineNum":"  302","line":"}"},
{"lineNum":"  303","line":"function test20-assert1-expected () {"},
{"lineNum":"  304","line":"\techo -e \'I can use a backslash n to start a new line.\'","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  305","line":"}"},
{"lineNum":"  306","line":""},
{"lineNum":"  307","line":"bats_test_function --tags \'\' test_test0","class":"lineCov","hits":"23","order":"350","possible_hits":"0",},
{"lineNum":"  308","line":"bats_test_function --tags \'\' test_test1","class":"lineCov","hits":"23","order":"351","possible_hits":"0",},
{"lineNum":"  309","line":"bats_test_function --tags \'\' test_test2","class":"lineCov","hits":"23","order":"352","possible_hits":"0",},
{"lineNum":"  310","line":"bats_test_function --tags \'\' test_test3","class":"lineCov","hits":"23","order":"353","possible_hits":"0",},
{"lineNum":"  311","line":"bats_test_function --tags \'\' test_test4","class":"lineCov","hits":"23","order":"354","possible_hits":"0",},
{"lineNum":"  312","line":"bats_test_function --tags \'\' test_test5","class":"lineCov","hits":"23","order":"355","possible_hits":"0",},
{"lineNum":"  313","line":"bats_test_function --tags \'\' test_test6","class":"lineCov","hits":"23","order":"356","possible_hits":"0",},
{"lineNum":"  314","line":"bats_test_function --tags \'\' test_test7","class":"lineCov","hits":"23","order":"357","possible_hits":"0",},
{"lineNum":"  315","line":"bats_test_function --tags \'\' test_test8","class":"lineCov","hits":"23","order":"358","possible_hits":"0",},
{"lineNum":"  316","line":"bats_test_function --tags \'\' test_test9","class":"lineCov","hits":"23","order":"359","possible_hits":"0",},
{"lineNum":"  317","line":"bats_test_function --tags \'\' test_test10","class":"lineCov","hits":"23","order":"360","possible_hits":"0",},
{"lineNum":"  318","line":"bats_test_function --tags \'\' test_test11","class":"lineCov","hits":"23","order":"361","possible_hits":"0",},
{"lineNum":"  319","line":"bats_test_function --tags \'\' test_test12","class":"lineCov","hits":"23","order":"362","possible_hits":"0",},
{"lineNum":"  320","line":"bats_test_function --tags \'\' test_test13","class":"lineCov","hits":"23","order":"363","possible_hits":"0",},
{"lineNum":"  321","line":"bats_test_function --tags \'\' test_test14","class":"lineCov","hits":"23","order":"364","possible_hits":"0",},
{"lineNum":"  322","line":"bats_test_function --tags \'\' test_test15","class":"lineCov","hits":"23","order":"365","possible_hits":"0",},
{"lineNum":"  323","line":"bats_test_function --tags \'\' test_test16","class":"lineCov","hits":"23","order":"366","possible_hits":"0",},
{"lineNum":"  324","line":"bats_test_function --tags \'\' test_test17","class":"lineCov","hits":"23","order":"367","possible_hits":"0",},
{"lineNum":"  325","line":"bats_test_function --tags \'\' test_test18","class":"lineCov","hits":"23","order":"368","possible_hits":"0",},
{"lineNum":"  326","line":"bats_test_function --tags \'\' test_test19","class":"lineCov","hits":"23","order":"369","possible_hits":"0",},
{"lineNum":"  327","line":"bats_test_function --tags \'\' test_test20","class":"lineCov","hits":"23","order":"370","possible_hits":"0",},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "bats", "date" : "2023-05-04 19:40:27", "instrumented" : 169, "covered" : 111,};
var merged_data = [];
