var data = {lines:[
{"lineNum":"    1","line":"#!/usr/bin/env bats"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":""},
{"lineNum":"    4","line":"# Make executables ./tests/../ visible to PATH"},
{"lineNum":"    5","line":"PATH=\"/home/aveey/tom-project/shell-scripts/tests/batspp-only/../:$PATH\"","class":"lineCov","hits":"9","order":"333","possible_hits":"0",},
{"lineNum":"    6","line":""},
{"lineNum":"    7","line":"# Source files"},
{"lineNum":"    8","line":"shopt -s expand_aliases","class":"lineCov","hits":"9","order":"349","possible_hits":"0",},
{"lineNum":"    9","line":""},
{"lineNum":"   10","line":""},
{"lineNum":"   11","line":"test_test0() { bats_test_begin \"test0\";"},
{"lineNum":"   12","line":"\ttest_folder=$(echo /tmp/test0-$$)","class":"lineCov","hits":"4","order":"432","possible_hits":"0",},
{"lineNum":"   13","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"433","possible_hits":"0",},
{"lineNum":"   14","line":""},
{"lineNum":"   15","line":"\talias testnum=\"sed -r \"s/[0-9]/X/g\"\"","class":"lineCov","hits":"2","order":"434","possible_hits":"0",},
{"lineNum":"   16","line":"\talias testuser=\"sed -r \"s/\"$USER\"+/user/g\"\"","class":"lineCov","hits":"2","order":"435","possible_hits":"0",},
{"lineNum":"   17","line":"}"},
{"lineNum":"   18","line":""},
{"lineNum":"   19","line":""},
{"lineNum":"   20","line":"test_test1() { bats_test_begin \"test1\";"},
{"lineNum":"   21","line":"\ttest_folder=$(echo /tmp/test1-$$)","class":"lineCov","hits":"4","order":"474","possible_hits":"0",},
{"lineNum":"   22","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"475","possible_hits":"0",},
{"lineNum":"   23","line":""},
{"lineNum":"   24","line":"\tactual=$(test1-assert1-actual)","class":"lineCov","hits":"4","order":"476","possible_hits":"0",},
{"lineNum":"   25","line":"\texpected=$(test1-assert1-expected)","class":"lineCov","hits":"4","order":"478","possible_hits":"0",},
{"lineNum":"   26","line":"\techo \"========== actual ==========\"","class":"lineCov","hits":"2","order":"480","possible_hits":"0",},
{"lineNum":"   27","line":"\techo \"$actual\" | hexview.perl","class":"lineCov","hits":"4","order":"481","possible_hits":"0",},
{"lineNum":"   28","line":"\techo \"========= expected =========\"","class":"lineCov","hits":"2","order":"482","possible_hits":"0",},
{"lineNum":"   29","line":"\techo \"$expected\" | hexview.perl","class":"lineCov","hits":"4","order":"483","possible_hits":"0",},
{"lineNum":"   30","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"484","possible_hits":"0",},
{"lineNum":"   31","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineCov","hits":"2","order":"485","possible_hits":"0",},
{"lineNum":"   32","line":""},
{"lineNum":"   33","line":"}"},
{"lineNum":"   34","line":""},
{"lineNum":"   35","line":"function test1-assert1-actual () {"},
{"lineNum":"   36","line":"\techo \"Hello\"","class":"lineCov","hits":"2","order":"477","possible_hits":"0",},
{"lineNum":"   37","line":"}"},
{"lineNum":"   38","line":"function test1-assert1-expected () {"},
{"lineNum":"   39","line":"\techo -e \'Hello\'","class":"lineCov","hits":"2","order":"479","possible_hits":"0",},
{"lineNum":"   40","line":"}"},
{"lineNum":"   41","line":""},
{"lineNum":"   42","line":"test_test2() { bats_test_begin \"test2\";"},
{"lineNum":"   43","line":"\ttest_folder=$(echo /tmp/test2-$$)","class":"lineCov","hits":"4","order":"486","possible_hits":"0",},
{"lineNum":"   44","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"487","possible_hits":"0",},
{"lineNum":"   45","line":""},
{"lineNum":"   46","line":"\tactual=$(test2-assert1-actual)","class":"lineCov","hits":"4","order":"488","possible_hits":"0",},
{"lineNum":"   47","line":"\texpected=$(test2-assert1-expected)","class":"lineCov","hits":"4","order":"490","possible_hits":"0",},
{"lineNum":"   48","line":"\techo \"========== actual ==========\"","class":"lineCov","hits":"2","order":"492","possible_hits":"0",},
{"lineNum":"   49","line":"\techo \"$actual\" | hexview.perl","class":"lineCov","hits":"4","order":"493","possible_hits":"0",},
{"lineNum":"   50","line":"\techo \"========= expected =========\"","class":"lineCov","hits":"2","order":"494","possible_hits":"0",},
{"lineNum":"   51","line":"\techo \"$expected\" | hexview.perl","class":"lineCov","hits":"4","order":"495","possible_hits":"0",},
{"lineNum":"   52","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"496","possible_hits":"0",},
{"lineNum":"   53","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineCov","hits":"2","order":"497","possible_hits":"0",},
{"lineNum":"   54","line":""},
{"lineNum":"   55","line":"}"},
{"lineNum":"   56","line":""},
{"lineNum":"   57","line":"function test2-assert1-actual () {"},
{"lineNum":"   58","line":"\techo \"This is a test\" | wc -c","class":"lineCov","hits":"4","order":"489","possible_hits":"0",},
{"lineNum":"   59","line":"}"},
{"lineNum":"   60","line":"function test2-assert1-expected () {"},
{"lineNum":"   61","line":"\techo -e \'15\'","class":"lineCov","hits":"2","order":"491","possible_hits":"0",},
{"lineNum":"   62","line":"}"},
{"lineNum":"   63","line":""},
{"lineNum":"   64","line":"test_test3() { bats_test_begin \"test3\";"},
{"lineNum":"   65","line":"\ttest_folder=$(echo /tmp/test3-$$)","class":"lineCov","hits":"4","order":"498","possible_hits":"0",},
{"lineNum":"   66","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"499","possible_hits":"0",},
{"lineNum":"   67","line":""},
{"lineNum":"   68","line":"\tactual=$(test3-assert1-actual)","class":"lineCov","hits":"4","order":"500","possible_hits":"0",},
{"lineNum":"   69","line":"\texpected=$(test3-assert1-expected)","class":"lineCov","hits":"4","order":"502","possible_hits":"0",},
{"lineNum":"   70","line":"\techo \"========== actual ==========\"","class":"lineCov","hits":"2","order":"504","possible_hits":"0",},
{"lineNum":"   71","line":"\techo \"$actual\" | hexview.perl","class":"lineCov","hits":"4","order":"505","possible_hits":"0",},
{"lineNum":"   72","line":"\techo \"========= expected =========\"","class":"lineCov","hits":"2","order":"506","possible_hits":"0",},
{"lineNum":"   73","line":"\techo \"$expected\" | hexview.perl","class":"lineCov","hits":"4","order":"507","possible_hits":"0",},
{"lineNum":"   74","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"508","possible_hits":"0",},
{"lineNum":"   75","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineCov","hits":"4","order":"509","possible_hits":"0",},
{"lineNum":"   76","line":""},
{"lineNum":"   77","line":"}"},
{"lineNum":"   78","line":""},
{"lineNum":"   79","line":"function test3-assert1-actual () {"},
{"lineNum":"   80","line":"\tiwconfig | tee wireless_info.txt","class":"lineCov","hits":"4","order":"501","possible_hits":"0",},
{"lineNum":"   81","line":"}"},
{"lineNum":"   82","line":"function test3-assert1-expected () {"},
{"lineNum":"   83","line":"\techo -e \'lo        no wireless extensions.\'","class":"lineCov","hits":"2","order":"503","possible_hits":"0",},
{"lineNum":"   84","line":"}"},
{"lineNum":"   85","line":""},
{"lineNum":"   86","line":"test_test4() { bats_test_begin \"test4\";"},
{"lineNum":"   87","line":"\ttest_folder=$(echo /tmp/test4-$$)","class":"lineCov","hits":"4","order":"601","possible_hits":"0",},
{"lineNum":"   88","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"602","possible_hits":"0",},
{"lineNum":"   89","line":""},
{"lineNum":"   90","line":"\tactual=$(test4-assert1-actual)","class":"lineCov","hits":"7","order":"603","possible_hits":"0",},
{"lineNum":"   91","line":"\texpected=$(test4-assert1-expected)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   92","line":"\techo \"========== actual ==========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   93","line":"\techo \"$actual\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   94","line":"\techo \"========= expected =========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   95","line":"\techo \"$expected\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   96","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   97","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   98","line":""},
{"lineNum":"   99","line":"}"},
{"lineNum":"  100","line":""},
{"lineNum":"  101","line":"function test4-assert1-actual () {"},
{"lineNum":"  102","line":"\tcat wireless_info.txt","class":"lineCov","hits":"4","order":"604","possible_hits":"0",},
{"lineNum":"  103","line":"}"},
{"lineNum":"  104","line":"function test4-assert1-expected () {"},
{"lineNum":"  105","line":"\techo -e \'wlp4s0    IEEE 802.11  ESSID:\"Sudhir_DHFibernet\"  Mode:Managed  Frequency:2.447 GHz  Access Point: 6C:14:6E:5A:B7:58   Bit Rate=78 Mb/s   Tx-Power=3 dBm   Retry short limit:7   RTS thr:off   Fragment thr:offPower Management:onLink Quality=42/70  Signal level=-68 dBm  Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0Tx excessive retries:0  Invalid misc:3   Missed beacon:0\'","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  106","line":"}"},
{"lineNum":"  107","line":""},
{"lineNum":"  108","line":"test_test5() { bats_test_begin \"test5\";"},
{"lineNum":"  109","line":"\ttest_folder=$(echo /tmp/test5-$$)","class":"lineCov","hits":"4","order":"605","possible_hits":"0",},
{"lineNum":"  110","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"606","possible_hits":"0",},
{"lineNum":"  111","line":""},
{"lineNum":"  112","line":"\tactual=$(test5-assert1-actual)","class":"lineCov","hits":"4","order":"607","possible_hits":"0",},
{"lineNum":"  113","line":"\texpected=$(test5-assert1-expected)","class":"lineCov","hits":"4","order":"609","possible_hits":"0",},
{"lineNum":"  114","line":"\techo \"========== actual ==========\"","class":"lineCov","hits":"2","order":"611","possible_hits":"0",},
{"lineNum":"  115","line":"\techo \"$actual\" | hexview.perl","class":"lineCov","hits":"4","order":"612","possible_hits":"0",},
{"lineNum":"  116","line":"\techo \"========= expected =========\"","class":"lineCov","hits":"2","order":"613","possible_hits":"0",},
{"lineNum":"  117","line":"\techo \"$expected\" | hexview.perl","class":"lineCov","hits":"4","order":"614","possible_hits":"0",},
{"lineNum":"  118","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"615","possible_hits":"0",},
{"lineNum":"  119","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineCov","hits":"2","order":"616","possible_hits":"0",},
{"lineNum":"  120","line":""},
{"lineNum":"  121","line":"}"},
{"lineNum":"  122","line":""},
{"lineNum":"  123","line":"function test5-assert1-actual () {"},
{"lineNum":"  124","line":"\techo \"Done\"","class":"lineCov","hits":"2","order":"608","possible_hits":"0",},
{"lineNum":"  125","line":"}"},
{"lineNum":"  126","line":"function test5-assert1-expected () {"},
{"lineNum":"  127","line":"\techo -e \'Done\'","class":"lineCov","hits":"2","order":"610","possible_hits":"0",},
{"lineNum":"  128","line":"}"},
{"lineNum":"  129","line":""},
{"lineNum":"  130","line":"test_test6() { bats_test_begin \"test6\";"},
{"lineNum":"  131","line":"\ttest_folder=$(echo /tmp/test6-$$)","class":"lineCov","hits":"4","order":"617","possible_hits":"0",},
{"lineNum":"  132","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"618","possible_hits":"0",},
{"lineNum":"  133","line":""},
{"lineNum":"  134","line":"\tsudo apt search libnoise","class":"lineCov","hits":"2","order":"619","possible_hits":"0",},
{"lineNum":"  135","line":"}"},
{"lineNum":"  136","line":""},
{"lineNum":"  137","line":"bats_test_function --tags \'\' test_test0","class":"lineCov","hits":"9","order":"350","possible_hits":"0",},
{"lineNum":"  138","line":"bats_test_function --tags \'\' test_test1","class":"lineCov","hits":"9","order":"351","possible_hits":"0",},
{"lineNum":"  139","line":"bats_test_function --tags \'\' test_test2","class":"lineCov","hits":"9","order":"352","possible_hits":"0",},
{"lineNum":"  140","line":"bats_test_function --tags \'\' test_test3","class":"lineCov","hits":"9","order":"353","possible_hits":"0",},
{"lineNum":"  141","line":"bats_test_function --tags \'\' test_test4","class":"lineCov","hits":"9","order":"354","possible_hits":"0",},
{"lineNum":"  142","line":"bats_test_function --tags \'\' test_test5","class":"lineCov","hits":"9","order":"355","possible_hits":"0",},
{"lineNum":"  143","line":"bats_test_function --tags \'\' test_test6","class":"lineCov","hits":"9","order":"356","possible_hits":"0",},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "bats", "date" : "2023-04-12 19:00:35", "instrumented" : 76, "covered" : 68,};
var merged_data = [];
