var data = {lines:[
{"lineNum":"    1","line":"#!/usr/bin/env bats"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":""},
{"lineNum":"    4","line":"# Make executables ./tests/../ visible to PATH"},
{"lineNum":"    5","line":"PATH=\"/home/aveey/tom-project/shell-scripts/tests/batspp-only/../:$PATH\"","class":"lineCov","hits":"28","order":"333","possible_hits":"0",},
{"lineNum":"    6","line":""},
{"lineNum":"    7","line":"# Enable aliases"},
{"lineNum":"    8","line":"shopt -s expand_aliases","class":"lineCov","hits":"28","order":"349","possible_hits":"0",},
{"lineNum":"    9","line":""},
{"lineNum":"   10","line":""},
{"lineNum":"   11","line":""},
{"lineNum":"   12","line":"test_test-2d1() { bats_test_begin \"test-1\";"},
{"lineNum":"   13","line":"\ttestfolder=\"/tmp/batspp-131274/test-1\"","class":"lineCov","hits":"2","order":"451","possible_hits":"0",},
{"lineNum":"   14","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"452","possible_hits":"0",},
{"lineNum":"   15","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"453","possible_hits":"0",},
{"lineNum":"   16","line":""},
{"lineNum":"   17","line":"\techo \"==========\" $\'echo $PS1\\n\' \"==========\"","class":"lineCov","hits":"2","order":"454","possible_hits":"0",},
{"lineNum":"   18","line":"\ttest-1-actual","class":"lineCov","hits":"2","order":"455","possible_hits":"0",},
{"lineNum":"   19","line":"\techo \"=========\" $\'[PEXP\\\\[\\\\]ECT_PROMPT>\' \"=========\"","class":"lineCov","hits":"2","order":"458","possible_hits":"0",},
{"lineNum":"   20","line":"\ttest-1-expected","class":"lineCov","hits":"2","order":"459","possible_hits":"0",},
{"lineNum":"   21","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"462","possible_hits":"0",},
{"lineNum":"   22","line":"\t# ???: \'echo $PS1\\n\'=$(test-1-actual)"},
{"lineNum":"   23","line":"\t# ???: \'[PEXP\\\\[\\\\]ECT_PROMPT>\'=$(test-1-expected)"},
{"lineNum":"   24","line":"\t[ \"$(test-1-actual)\" == \"$(test-1-expected)\" ]","class":"lineCov","hits":"8","order":"463","possible_hits":"0",},
{"lineNum":"   25","line":"}"},
{"lineNum":"   26","line":""},
{"lineNum":"   27","line":"function test-1-actual () {"},
{"lineNum":"   28","line":"\t# no-op in case content just a comment"},
{"lineNum":"   29","line":"\ttrue","class":"lineCov","hits":"4","order":"456","possible_hits":"0",},
{"lineNum":"   30","line":""},
{"lineNum":"   31","line":"\techo $PS1","class":"lineCov","hits":"4","order":"457","possible_hits":"0",},
{"lineNum":"   32","line":""},
{"lineNum":"   33","line":"}"},
{"lineNum":"   34","line":""},
{"lineNum":"   35","line":"function test-1-expected () {"},
{"lineNum":"   36","line":"\t# no-op in case content just a comment"},
{"lineNum":"   37","line":"\ttrue","class":"lineCov","hits":"4","order":"460","possible_hits":"0",},
{"lineNum":"   38","line":""},
{"lineNum":"   39","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"4","order":"461","possible_hits":"0",},
{"lineNum":"   40","line":"[PEXP\\[\\]ECT_PROMPT>"},
{"lineNum":"   41","line":"END_EXPECTED"},
{"lineNum":"   42","line":"}"},
{"lineNum":"   43","line":""},
{"lineNum":"   44","line":""},
{"lineNum":"   45","line":"test_test-2d3() { bats_test_begin \"test-3\";"},
{"lineNum":"   46","line":"\ttestfolder=\"/tmp/batspp-131274/test-3\"","class":"lineCov","hits":"2","order":"586","possible_hits":"0",},
{"lineNum":"   47","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"587","possible_hits":"0",},
{"lineNum":"   48","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"588","possible_hits":"0",},
{"lineNum":"   49","line":""},
{"lineNum":"   50","line":"\techo \"==========\" $\'unalias -a\\n\' \"==========\"","class":"lineCov","hits":"2","order":"589","possible_hits":"0",},
{"lineNum":"   51","line":"\ttest-3-actual","class":"lineCov","hits":"2","order":"590","possible_hits":"0",},
{"lineNum":"   52","line":"\techo \"=========\" $\"$ alias | wc -l\\n$ for f in $(typeset -f | egrep \'^\\\\w+\'); do unset -f $f; done\\n$ typeset -f | egrep \'^\\\\w+\' | wc -l\\n0\\n0\" \"=========\"","class":"lineCov","hits":"8","order":"593","possible_hits":"0",},
{"lineNum":"   53","line":"\ttest-3-expected","class":"lineCov","hits":"2","order":"594","possible_hits":"0",},
{"lineNum":"   54","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"597","possible_hits":"0",},
{"lineNum":"   55","line":"\t# ???: \'unalias -a\\n\'=$(test-3-actual)"},
{"lineNum":"   56","line":"\t# ???: \"$ alias | wc -l\\n$ for f in $(typeset -f | egrep \'^\\\\w+\'); do unset -f $f; done\\n$ typeset -f | egrep \'^\\\\w+\' | wc -l\\n0\\n0\"=$(test-3-expected)"},
{"lineNum":"   57","line":"\t[ \"$(test-3-actual)\" == \"$(test-3-expected)\" ]","class":"lineCov","hits":"8","order":"598","possible_hits":"0",},
{"lineNum":"   58","line":"}"},
{"lineNum":"   59","line":""},
{"lineNum":"   60","line":"function test-3-actual () {"},
{"lineNum":"   61","line":"\t# no-op in case content just a comment"},
{"lineNum":"   62","line":"\ttrue","class":"lineCov","hits":"4","order":"591","possible_hits":"0",},
{"lineNum":"   63","line":""},
{"lineNum":"   64","line":"\tunalias -a","class":"lineCov","hits":"4","order":"592","possible_hits":"0",},
{"lineNum":"   65","line":""},
{"lineNum":"   66","line":"}"},
{"lineNum":"   67","line":""},
{"lineNum":"   68","line":"function test-3-expected () {"},
{"lineNum":"   69","line":"\t# no-op in case content just a comment"},
{"lineNum":"   70","line":"\ttrue","class":"lineCov","hits":"4","order":"595","possible_hits":"0",},
{"lineNum":"   71","line":""},
{"lineNum":"   72","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"12","order":"596","possible_hits":"0",},
{"lineNum":"   73","line":"$ alias | wc -l"},
{"lineNum":"   74","line":"$ for f in $(typeset -f | egrep \'^\\w+\'); do unset -f $f; done"},
{"lineNum":"   75","line":"$ typeset -f | egrep \'^\\w+\' | wc -l"},
{"lineNum":"   76","line":"0"},
{"lineNum":"   77","line":"0"},
{"lineNum":"   78","line":"END_EXPECTED"},
{"lineNum":"   79","line":"}"},
{"lineNum":"   80","line":""},
{"lineNum":"   81","line":""},
{"lineNum":"   82","line":"test_test-2d4() { bats_test_begin \"test-4\";"},
{"lineNum":"   83","line":"\ttestfolder=\"/tmp/batspp-131274/test-4\"","class":"lineCov","hits":"2","order":"599","possible_hits":"0",},
{"lineNum":"   84","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"600","possible_hits":"0",},
{"lineNum":"   85","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"601","possible_hits":"0",},
{"lineNum":"   86","line":""},
{"lineNum":"   87","line":"\techo \"==========\" $\'TMP=/tmp/test-unix-alias\\n\' \"==========\"","class":"lineCov","hits":"2","order":"602","possible_hits":"0",},
{"lineNum":"   88","line":"\ttest-4-actual","class":"lineCov","hits":"2","order":"603","possible_hits":"0",},
{"lineNum":"   89","line":"\techo \"=========\" $\'$ BIN_DIR=$PWD/..\\n$ alias | wc -l\\n$ temp_dir=$TMP/test-2899\\n$ mkdir -p \"$temp_dir\"\\n$ cd \"$temp_dir\"\\n$ pwd\\n#ALIAS FOR PRINTING SEPERATION LINES (FOR JUPYTER)\\n$ alias linebr=\"printf \\\'%*s\\\\n\\\' \"${COLUMNS:-$(tput cols)}\" \\\'\\\' | tr \\\' \\\' -\"\\n0\\n/tmp/test-unix-alias/test-2899\' \"=========\"","class":"lineCov","hits":"2","order":"606","possible_hits":"0",},
{"lineNum":"   90","line":"\ttest-4-expected","class":"lineCov","hits":"2","order":"607","possible_hits":"0",},
{"lineNum":"   91","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"610","possible_hits":"0",},
{"lineNum":"   92","line":"\t# ???: \'TMP=/tmp/test-unix-alias\\n\'=$(test-4-actual)"},
{"lineNum":"   93","line":"\t# ???: \'$ BIN_DIR=$PWD/..\\n$ alias | wc -l\\n$ temp_dir=$TMP/test-2899\\n$ mkdir -p \"$temp_dir\"\\n$ cd \"$temp_dir\"\\n$ pwd\\n#ALIAS FOR PRINTING SEPERATION LINES (FOR JUPYTER)\\n$ alias linebr=\"printf \\\'%*s\\\\n\\\' \"${COLUMNS:-$(tput cols)}\" \\\'\\\' | tr \\\' \\\' -\"\\n0\\n/tmp/test-unix-alias/test-2899\'=$(test-4-expected)"},
{"lineNum":"   94","line":"\t[ \"$(test-4-actual)\" == \"$(test-4-expected)\" ]","class":"lineCov","hits":"8","order":"611","possible_hits":"0",},
{"lineNum":"   95","line":"}"},
{"lineNum":"   96","line":""},
{"lineNum":"   97","line":"function test-4-actual () {"},
{"lineNum":"   98","line":"\t# no-op in case content just a comment"},
{"lineNum":"   99","line":"\ttrue","class":"lineCov","hits":"4","order":"604","possible_hits":"0",},
{"lineNum":"  100","line":""},
{"lineNum":"  101","line":"\tTMP=/tmp/test-unix-alias","class":"lineCov","hits":"4","order":"605","possible_hits":"0",},
{"lineNum":"  102","line":""},
{"lineNum":"  103","line":"}"},
{"lineNum":"  104","line":""},
{"lineNum":"  105","line":"function test-4-expected () {"},
{"lineNum":"  106","line":"\t# no-op in case content just a comment"},
{"lineNum":"  107","line":"\ttrue","class":"lineCov","hits":"4","order":"608","possible_hits":"0",},
{"lineNum":"  108","line":""},
{"lineNum":"  109","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"8","order":"609","possible_hits":"0",},
{"lineNum":"  110","line":"$ BIN_DIR=$PWD/.."},
{"lineNum":"  111","line":"$ alias | wc -l"},
{"lineNum":"  112","line":"$ temp_dir=$TMP/test-2899"},
{"lineNum":"  113","line":"$ mkdir -p \"$temp_dir\""},
{"lineNum":"  114","line":"$ cd \"$temp_dir\""},
{"lineNum":"  115","line":"$ pwd"},
{"lineNum":"  116","line":"#ALIAS FOR PRINTING SEPERATION LINES (FOR JUPYTER)"},
{"lineNum":"  117","line":"$ alias linebr=\"printf \'%*s\\n\' \"${COLUMNS:-$(tput cols)}\" \'\' | tr \' \' -\""},
{"lineNum":"  118","line":"0"},
{"lineNum":"  119","line":"/tmp/test-unix-alias/test-2899"},
{"lineNum":"  120","line":"END_EXPECTED"},
{"lineNum":"  121","line":"}"},
{"lineNum":"  122","line":""},
{"lineNum":"  123","line":""},
{"lineNum":"  124","line":"test_test-2d5() { bats_test_begin \"test-5\";"},
{"lineNum":"  125","line":"\ttestfolder=\"/tmp/batspp-131274/test-5\"","class":"lineCov","hits":"2","order":"612","possible_hits":"0",},
{"lineNum":"  126","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"613","possible_hits":"0",},
{"lineNum":"  127","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"614","possible_hits":"0",},
{"lineNum":"  128","line":""},
{"lineNum":"  129","line":"\techo \"==========\" $\'alias | wc -l\\n\' \"==========\"","class":"lineCov","hits":"2","order":"615","possible_hits":"0",},
{"lineNum":"  130","line":"\ttest-5-actual","class":"lineCov","hits":"2","order":"616","possible_hits":"0",},
{"lineNum":"  131","line":"\techo \"=========\" $\"# Count functions\\n$ typeset -f | egrep \'^\\\\w+\' | wc -l\\n1\\n0\" \"=========\"","class":"lineCov","hits":"2","order":"619","possible_hits":"0",},
{"lineNum":"  132","line":"\ttest-5-expected","class":"lineCov","hits":"2","order":"620","possible_hits":"0",},
{"lineNum":"  133","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"623","possible_hits":"0",},
{"lineNum":"  134","line":"\t# ???: \'alias | wc -l\\n\'=$(test-5-actual)"},
{"lineNum":"  135","line":"\t# ???: \"# Count functions\\n$ typeset -f | egrep \'^\\\\w+\' | wc -l\\n1\\n0\"=$(test-5-expected)"},
{"lineNum":"  136","line":"\t[ \"$(test-5-actual)\" == \"$(test-5-expected)\" ]","class":"lineCov","hits":"8","order":"624","possible_hits":"0",},
{"lineNum":"  137","line":"}"},
{"lineNum":"  138","line":""},
{"lineNum":"  139","line":"function test-5-actual () {"},
{"lineNum":"  140","line":"\t# no-op in case content just a comment"},
{"lineNum":"  141","line":"\ttrue","class":"lineCov","hits":"4","order":"617","possible_hits":"0",},
{"lineNum":"  142","line":""},
{"lineNum":"  143","line":"\talias | wc -l","class":"lineCov","hits":"8","order":"618","possible_hits":"0",},
{"lineNum":"  144","line":""},
{"lineNum":"  145","line":"}"},
{"lineNum":"  146","line":""},
{"lineNum":"  147","line":"function test-5-expected () {"},
{"lineNum":"  148","line":"\t# no-op in case content just a comment"},
{"lineNum":"  149","line":"\ttrue","class":"lineCov","hits":"4","order":"621","possible_hits":"0",},
{"lineNum":"  150","line":""},
{"lineNum":"  151","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"4","order":"622","possible_hits":"0",},
{"lineNum":"  152","line":"# Count functions"},
{"lineNum":"  153","line":"$ typeset -f | egrep \'^\\w+\' | wc -l"},
{"lineNum":"  154","line":"1"},
{"lineNum":"  155","line":"0"},
{"lineNum":"  156","line":"END_EXPECTED"},
{"lineNum":"  157","line":"}"},
{"lineNum":"  158","line":""},
{"lineNum":"  159","line":""},
{"lineNum":"  160","line":"test_test-2d6() { bats_test_begin \"test-6\";"},
{"lineNum":"  161","line":"\ttestfolder=\"/tmp/batspp-131274/test-6\"","class":"lineCov","hits":"2","order":"625","possible_hits":"0",},
{"lineNum":"  162","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"626","possible_hits":"0",},
{"lineNum":"  163","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"627","possible_hits":"0",},
{"lineNum":"  164","line":""},
{"lineNum":"  165","line":"\techo \"==========\" $\'alias testnum=\"sed -r \"s/[0-9]/N/g\"\" \\n\' \"==========\"","class":"lineCov","hits":"2","order":"628","possible_hits":"0",},
{"lineNum":"  166","line":"\ttest-6-actual","class":"lineCov","hits":"2","order":"629","possible_hits":"0",},
{"lineNum":"  167","line":"\techo \"=========\" $\'$ alias testuser=\"sed -r \"s/\"$USER\"+/userxf333/g\"\"\' \"=========\"","class":"lineCov","hits":"2","order":"632","possible_hits":"0",},
{"lineNum":"  168","line":"\ttest-6-expected","class":"lineCov","hits":"2","order":"633","possible_hits":"0",},
{"lineNum":"  169","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"636","possible_hits":"0",},
{"lineNum":"  170","line":"\t# ???: \'alias testnum=\"sed -r \"s/[0-9]/N/g\"\" \\n\'=$(test-6-actual)"},
{"lineNum":"  171","line":"\t# ???: \'$ alias testuser=\"sed -r \"s/\"$USER\"+/userxf333/g\"\"\'=$(test-6-expected)"},
{"lineNum":"  172","line":"\t[ \"$(test-6-actual)\" == \"$(test-6-expected)\" ]","class":"lineCov","hits":"8","order":"637","possible_hits":"0",},
{"lineNum":"  173","line":"}"},
{"lineNum":"  174","line":""},
{"lineNum":"  175","line":"function test-6-actual () {"},
{"lineNum":"  176","line":"\t# no-op in case content just a comment"},
{"lineNum":"  177","line":"\ttrue","class":"lineCov","hits":"4","order":"630","possible_hits":"0",},
{"lineNum":"  178","line":""},
{"lineNum":"  179","line":"\talias testnum=\"sed -r \"s/[0-9]/N/g\"\"","class":"lineCov","hits":"4","order":"631","possible_hits":"0",},
{"lineNum":"  180","line":""},
{"lineNum":"  181","line":"}"},
{"lineNum":"  182","line":""},
{"lineNum":"  183","line":"function test-6-expected () {"},
{"lineNum":"  184","line":"\t# no-op in case content just a comment"},
{"lineNum":"  185","line":"\ttrue","class":"lineCov","hits":"4","order":"634","possible_hits":"0",},
{"lineNum":"  186","line":""},
{"lineNum":"  187","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"4","order":"635","possible_hits":"0",},
{"lineNum":"  188","line":"$ alias testuser=\"sed -r \"s/\"$USER\"+/userxf333/g\"\""},
{"lineNum":"  189","line":"END_EXPECTED"},
{"lineNum":"  190","line":"}"},
{"lineNum":"  191","line":""},
{"lineNum":"  192","line":""},
{"lineNum":"  193","line":"test_test-2d7() { bats_test_begin \"test-7\";"},
{"lineNum":"  194","line":"\ttestfolder=\"/tmp/batspp-131274/test-7\"","class":"lineCov","hits":"2","order":"638","possible_hits":"0",},
{"lineNum":"  195","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"639","possible_hits":"0",},
{"lineNum":"  196","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"640","possible_hits":"0",},
{"lineNum":"  197","line":""},
{"lineNum":"  198","line":"\techo \"==========\" $\'source $BIN_DIR/tomohara-aliases.bash\\n\' \"==========\"","class":"lineCov","hits":"2","order":"641","possible_hits":"0",},
{"lineNum":"  199","line":"\ttest-7-actual","class":"lineCov","hits":"2","order":"642","possible_hits":"0",},
{"lineNum":"  200","line":"\techo \"=========\" $\'\' \"=========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  201","line":"\ttest-7-expected","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  202","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  203","line":"\t# ???: \'source $BIN_DIR/tomohara-aliases.bash\\n\'=$(test-7-actual)"},
{"lineNum":"  204","line":"\t# ???: \'\'=$(test-7-expected)"},
{"lineNum":"  205","line":"\t[ \"$(test-7-actual)\" == \"$(test-7-expected)\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  206","line":"}"},
{"lineNum":"  207","line":""},
{"lineNum":"  208","line":"function test-7-actual () {"},
{"lineNum":"  209","line":"\t# no-op in case content just a comment"},
{"lineNum":"  210","line":"\ttrue","class":"lineCov","hits":"2","order":"643","possible_hits":"0",},
{"lineNum":"  211","line":""},
{"lineNum":"  212","line":"\tsource $BIN_DIR/tomohara-aliases.bash","class":"lineCov","hits":"2","order":"644","possible_hits":"0",},
{"lineNum":"  213","line":""},
{"lineNum":"  214","line":"}"},
{"lineNum":"  215","line":""},
{"lineNum":"  216","line":"function test-7-expected () {"},
{"lineNum":"  217","line":"\t# no-op in case content just a comment"},
{"lineNum":"  218","line":"\ttrue","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  219","line":""},
{"lineNum":"  220","line":"\tcat <<END_EXPECTED","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  221","line":""},
{"lineNum":"  222","line":"END_EXPECTED"},
{"lineNum":"  223","line":"}"},
{"lineNum":"  224","line":""},
{"lineNum":"  225","line":""},
{"lineNum":"  226","line":"test_test-2d8() { bats_test_begin \"test-8\";"},
{"lineNum":"  227","line":"\ttestfolder=\"/tmp/batspp-131274/test-8\"","class":"lineCov","hits":"2","order":"652","possible_hits":"0",},
{"lineNum":"  228","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"653","possible_hits":"0",},
{"lineNum":"  229","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"654","possible_hits":"0",},
{"lineNum":"  230","line":""},
{"lineNum":"  231","line":"\techo \"==========\" $\'# $ group-members\\n\' \"==========\"","class":"lineCov","hits":"2","order":"655","possible_hits":"0",},
{"lineNum":"  232","line":"\ttest-8-actual","class":"lineCov","hits":"2","order":"656","possible_hits":"0",},
{"lineNum":"  233","line":"\techo \"=========\" $\"# | ypcat: can\'t get local yp domain: Local domain name not set\" \"=========\"","class":"lineCov","hits":"2","order":"658","possible_hits":"0",},
{"lineNum":"  234","line":"\ttest-8-expected","class":"lineCov","hits":"2","order":"659","possible_hits":"0",},
{"lineNum":"  235","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"662","possible_hits":"0",},
{"lineNum":"  236","line":"\t# ???: \'# $ group-members\\n\'=$(test-8-actual)"},
{"lineNum":"  237","line":"\t# ???: \"# | ypcat: can\'t get local yp domain: Local domain name not set\"=$(test-8-expected)"},
{"lineNum":"  238","line":"\t[ \"$(test-8-actual)\" == \"$(test-8-expected)\" ]","class":"lineCov","hits":"8","order":"663","possible_hits":"0",},
{"lineNum":"  239","line":"}"},
{"lineNum":"  240","line":""},
{"lineNum":"  241","line":"function test-8-actual () {"},
{"lineNum":"  242","line":"\t# no-op in case content just a comment"},
{"lineNum":"  243","line":"\ttrue","class":"lineCov","hits":"4","order":"657","possible_hits":"0",},
{"lineNum":"  244","line":""},
{"lineNum":"  245","line":""},
{"lineNum":"  246","line":"}"},
{"lineNum":"  247","line":""},
{"lineNum":"  248","line":"function test-8-expected () {"},
{"lineNum":"  249","line":"\t# no-op in case content just a comment"},
{"lineNum":"  250","line":"\ttrue","class":"lineCov","hits":"4","order":"660","possible_hits":"0",},
{"lineNum":"  251","line":""},
{"lineNum":"  252","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"4","order":"661","possible_hits":"0",},
{"lineNum":"  253","line":"# | ypcat: can\'t get local yp domain: Local domain name not set"},
{"lineNum":"  254","line":"END_EXPECTED"},
{"lineNum":"  255","line":"}"},
{"lineNum":"  256","line":""},
{"lineNum":"  257","line":""},
{"lineNum":"  258","line":"test_test-2d9() { bats_test_begin \"test-9\";"},
{"lineNum":"  259","line":"\ttestfolder=\"/tmp/batspp-131274/test-9\"","class":"lineCov","hits":"2","order":"664","possible_hits":"0",},
{"lineNum":"  260","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"665","possible_hits":"0",},
{"lineNum":"  261","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"666","possible_hits":"0",},
{"lineNum":"  262","line":""},
{"lineNum":"  263","line":"\techo \"==========\" $\'rm -rf ./* > /dev/null\\n\' \"==========\"","class":"lineCov","hits":"2","order":"667","possible_hits":"0",},
{"lineNum":"  264","line":"\ttest-9-actual","class":"lineCov","hits":"2","order":"668","possible_hits":"0",},
{"lineNum":"  265","line":"\techo \"=========\" $\'$ mkdir testfolder\\n$ echo \"Hi Mom!\" > himom.txt\\n$ echo \"Hi Dad!\" > hidad.txt\\n$ do-make \"himom.txt\"\\n$ cat _make.log\\n$ do-make \"hidad.txt\"\\n$ cat _make.log\\n$ ls -l | awk \\\'!($6=\"\")\\\' | testuser | testnum\\n/bin/mv: cannot stat \\\'_make.log\\\': No such file or directory\\n\\x1b[?1h\\x1b=\' \"=========\"","class":"lineCov","hits":"2","order":"671","possible_hits":"0",},
{"lineNum":"  266","line":"\ttest-9-expected","class":"lineCov","hits":"2","order":"672","possible_hits":"0",},
{"lineNum":"  267","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"675","possible_hits":"0",},
{"lineNum":"  268","line":"\t# ???: \'rm -rf ./* > /dev/null\\n\'=$(test-9-actual)"},
{"lineNum":"  269","line":"\t# ???: \'$ mkdir testfolder\\n$ echo \"Hi Mom!\" > himom.txt\\n$ echo \"Hi Dad!\" > hidad.txt\\n$ do-make \"himom.txt\"\\n$ cat _make.log\\n$ do-make \"hidad.txt\"\\n$ cat _make.log\\n$ ls -l | awk \\\'!($6=\"\")\\\' | testuser | testnum\\n/bin/mv: cannot stat \\\'_make.log\\\': No such file or directory\\n\\x1b[?1h\\x1b=\'=$(test-9-expected)"},
{"lineNum":"  270","line":"\t[ \"$(test-9-actual)\" == \"$(test-9-expected)\" ]","class":"lineCov","hits":"8","order":"676","possible_hits":"0",},
{"lineNum":"  271","line":"}"},
{"lineNum":"  272","line":""},
{"lineNum":"  273","line":"function test-9-actual () {"},
{"lineNum":"  274","line":"\t# no-op in case content just a comment"},
{"lineNum":"  275","line":"\ttrue","class":"lineCov","hits":"4","order":"669","possible_hits":"0",},
{"lineNum":"  276","line":""},
{"lineNum":"  277","line":"\trm -rf ./* > /dev/null","class":"lineCov","hits":"4","order":"670","possible_hits":"0",},
{"lineNum":"  278","line":""},
{"lineNum":"  279","line":"}"},
{"lineNum":"  280","line":""},
{"lineNum":"  281","line":"function test-9-expected () {"},
{"lineNum":"  282","line":"\t# no-op in case content just a comment"},
{"lineNum":"  283","line":"\ttrue","class":"lineCov","hits":"4","order":"673","possible_hits":"0",},
{"lineNum":"  284","line":""},
{"lineNum":"  285","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"4","order":"674","possible_hits":"0",},
{"lineNum":"  286","line":"$ mkdir testfolder"},
{"lineNum":"  287","line":"$ echo \"Hi Mom!\" > himom.txt"},
{"lineNum":"  288","line":"$ echo \"Hi Dad!\" > hidad.txt"},
{"lineNum":"  289","line":"$ do-make \"himom.txt\""},
{"lineNum":"  290","line":"$ cat _make.log"},
{"lineNum":"  291","line":"$ do-make \"hidad.txt\""},
{"lineNum":"  292","line":"$ cat _make.log"},
{"lineNum":"  293","line":"$ ls -l | awk \'!($6=\"\")\' | testuser | testnum"},
{"lineNum":"  294","line":"/bin/mv: cannot stat \'_make.log\': No such file or directory"},
{"lineNum":"  295","line":"[?1h="},
{"lineNum":"  296","line":"END_EXPECTED"},
{"lineNum":"  297","line":"}"},
{"lineNum":"  298","line":""},
{"lineNum":"  299","line":""},
{"lineNum":"  300","line":"test_test-2d10() { bats_test_begin \"test-10\";"},
{"lineNum":"  301","line":"\ttestfolder=\"/tmp/batspp-131274/test-10\"","class":"lineCov","hits":"2","order":"677","possible_hits":"0",},
{"lineNum":"  302","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"678","possible_hits":"0",},
{"lineNum":"  303","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"679","possible_hits":"0",},
{"lineNum":"  304","line":""},
{"lineNum":"  305","line":"\techo \"==========\" $\'printf \"THIS IS THE 1ST FILE.\" > tf1.txt\\n\' \"==========\"","class":"lineCov","hits":"2","order":"680","possible_hits":"0",},
{"lineNum":"  306","line":"\ttest-10-actual","class":"lineCov","hits":"2","order":"681","possible_hits":"0",},
{"lineNum":"  307","line":"\techo \"=========\" $\'$ printf \"THIS IS THE 2ND FILE.\" > tf2.txt\\n$ printf \"THIS IS THE 3RD FILE.\" > tf3.txt\\n# MESSAGE SHOWN IF MERGE IS USED\\n$ merge tf1.txt tf2.txt\\ndo-merge MODFILE1 OLDFILE MODFILE2 > NEWFILE tf1.txt tf2.txt\' \"=========\"","class":"lineCov","hits":"2","order":"684","possible_hits":"0",},
{"lineNum":"  308","line":"\ttest-10-expected","class":"lineCov","hits":"2","order":"685","possible_hits":"0",},
{"lineNum":"  309","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"688","possible_hits":"0",},
{"lineNum":"  310","line":"\t# ???: \'printf \"THIS IS THE 1ST FILE.\" > tf1.txt\\n\'=$(test-10-actual)"},
{"lineNum":"  311","line":"\t# ???: \'$ printf \"THIS IS THE 2ND FILE.\" > tf2.txt\\n$ printf \"THIS IS THE 3RD FILE.\" > tf3.txt\\n# MESSAGE SHOWN IF MERGE IS USED\\n$ merge tf1.txt tf2.txt\\ndo-merge MODFILE1 OLDFILE MODFILE2 > NEWFILE tf1.txt tf2.txt\'=$(test-10-expected)"},
{"lineNum":"  312","line":"\t[ \"$(test-10-actual)\" == \"$(test-10-expected)\" ]","class":"lineCov","hits":"8","order":"689","possible_hits":"0",},
{"lineNum":"  313","line":"}"},
{"lineNum":"  314","line":""},
{"lineNum":"  315","line":"function test-10-actual () {"},
{"lineNum":"  316","line":"\t# no-op in case content just a comment"},
{"lineNum":"  317","line":"\ttrue","class":"lineCov","hits":"4","order":"682","possible_hits":"0",},
{"lineNum":"  318","line":""},
{"lineNum":"  319","line":"\tprintf \"THIS IS THE 1ST FILE.\" > tf1.txt","class":"lineCov","hits":"4","order":"683","possible_hits":"0",},
{"lineNum":"  320","line":""},
{"lineNum":"  321","line":"}"},
{"lineNum":"  322","line":""},
{"lineNum":"  323","line":"function test-10-expected () {"},
{"lineNum":"  324","line":"\t# no-op in case content just a comment"},
{"lineNum":"  325","line":"\ttrue","class":"lineCov","hits":"4","order":"686","possible_hits":"0",},
{"lineNum":"  326","line":""},
{"lineNum":"  327","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"4","order":"687","possible_hits":"0",},
{"lineNum":"  328","line":"$ printf \"THIS IS THE 2ND FILE.\" > tf2.txt"},
{"lineNum":"  329","line":"$ printf \"THIS IS THE 3RD FILE.\" > tf3.txt"},
{"lineNum":"  330","line":"# MESSAGE SHOWN IF MERGE IS USED"},
{"lineNum":"  331","line":"$ merge tf1.txt tf2.txt"},
{"lineNum":"  332","line":"do-merge MODFILE1 OLDFILE MODFILE2 > NEWFILE tf1.txt tf2.txt"},
{"lineNum":"  333","line":"END_EXPECTED"},
{"lineNum":"  334","line":"}"},
{"lineNum":"  335","line":""},
{"lineNum":"  336","line":""},
{"lineNum":"  337","line":"test_test-2d11() { bats_test_begin \"test-11\";"},
{"lineNum":"  338","line":"\ttestfolder=\"/tmp/batspp-131274/test-11\"","class":"lineCov","hits":"2","order":"690","possible_hits":"0",},
{"lineNum":"  339","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"691","possible_hits":"0",},
{"lineNum":"  340","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"692","possible_hits":"0",},
{"lineNum":"  341","line":""},
{"lineNum":"  342","line":"\techo \"==========\" $\'# $ do-merge tf1.txt tf2.txt tf3.txt\\n\' \"==========\"","class":"lineCov","hits":"2","order":"693","possible_hits":"0",},
{"lineNum":"  343","line":"\ttest-11-actual","class":"lineCov","hits":"2","order":"694","possible_hits":"0",},
{"lineNum":"  344","line":"\techo \"=========\" $\'# | <<<<<<< tf1.txt\\n# | THIS IS THE 1ST FILE.=======\\n# | THIS IS THE 3RD FILE.>>>>>>> tf3.txt\\n# | merge: warning: conflicts during merge\' \"=========\"","class":"lineCov","hits":"2","order":"696","possible_hits":"0",},
{"lineNum":"  345","line":"\ttest-11-expected","class":"lineCov","hits":"2","order":"697","possible_hits":"0",},
{"lineNum":"  346","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"700","possible_hits":"0",},
{"lineNum":"  347","line":"\t# ???: \'# $ do-merge tf1.txt tf2.txt tf3.txt\\n\'=$(test-11-actual)"},
{"lineNum":"  348","line":"\t# ???: \'# | <<<<<<< tf1.txt\\n# | THIS IS THE 1ST FILE.=======\\n# | THIS IS THE 3RD FILE.>>>>>>> tf3.txt\\n# | merge: warning: conflicts during merge\'=$(test-11-expected)"},
{"lineNum":"  349","line":"\t[ \"$(test-11-actual)\" == \"$(test-11-expected)\" ]","class":"lineCov","hits":"8","order":"701","possible_hits":"0",},
{"lineNum":"  350","line":"}"},
{"lineNum":"  351","line":""},
{"lineNum":"  352","line":"function test-11-actual () {"},
{"lineNum":"  353","line":"\t# no-op in case content just a comment"},
{"lineNum":"  354","line":"\ttrue","class":"lineCov","hits":"4","order":"695","possible_hits":"0",},
{"lineNum":"  355","line":""},
{"lineNum":"  356","line":""},
{"lineNum":"  357","line":"}"},
{"lineNum":"  358","line":""},
{"lineNum":"  359","line":"function test-11-expected () {"},
{"lineNum":"  360","line":"\t# no-op in case content just a comment"},
{"lineNum":"  361","line":"\ttrue","class":"lineCov","hits":"4","order":"698","possible_hits":"0",},
{"lineNum":"  362","line":""},
{"lineNum":"  363","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"4","order":"699","possible_hits":"0",},
{"lineNum":"  364","line":"# | <<<<<<< tf1.txt"},
{"lineNum":"  365","line":"# | THIS IS THE 1ST FILE.======="},
{"lineNum":"  366","line":"# | THIS IS THE 3RD FILE.>>>>>>> tf3.txt"},
{"lineNum":"  367","line":"# | merge: warning: conflicts during merge"},
{"lineNum":"  368","line":"END_EXPECTED"},
{"lineNum":"  369","line":"}"},
{"lineNum":"  370","line":""},
{"lineNum":"  371","line":""},
{"lineNum":"  372","line":"test_test-2d12() { bats_test_begin \"test-12\";"},
{"lineNum":"  373","line":"\ttestfolder=\"/tmp/batspp-131274/test-12\"","class":"lineCov","hits":"2","order":"702","possible_hits":"0",},
{"lineNum":"  374","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"703","possible_hits":"0",},
{"lineNum":"  375","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"704","possible_hits":"0",},
{"lineNum":"  376","line":""},
{"lineNum":"  377","line":"\techo \"==========\" $\'# $ diff3-merge tf1.txt tf2.txt tf3.txt -A\\n\' \"==========\"","class":"lineCov","hits":"2","order":"705","possible_hits":"0",},
{"lineNum":"  378","line":"\ttest-12-actual","class":"lineCov","hits":"2","order":"706","possible_hits":"0",},
{"lineNum":"  379","line":"\techo \"=========\" $\'# | <<<<<<< tf1.txt\\n# | THIS IS THE 1ST FILE.||||||| tf2.txt\\n# | THIS IS THE 2ND FILE.=======\\n# | THIS IS THE 3RD FILE.>>>>>>> tf3.txt\' \"=========\"","class":"lineCov","hits":"2","order":"708","possible_hits":"0",},
{"lineNum":"  380","line":"\ttest-12-expected","class":"lineCov","hits":"2","order":"709","possible_hits":"0",},
{"lineNum":"  381","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"712","possible_hits":"0",},
{"lineNum":"  382","line":"\t# ???: \'# $ diff3-merge tf1.txt tf2.txt tf3.txt -A\\n\'=$(test-12-actual)"},
{"lineNum":"  383","line":"\t# ???: \'# | <<<<<<< tf1.txt\\n# | THIS IS THE 1ST FILE.||||||| tf2.txt\\n# | THIS IS THE 2ND FILE.=======\\n# | THIS IS THE 3RD FILE.>>>>>>> tf3.txt\'=$(test-12-expected)"},
{"lineNum":"  384","line":"\t[ \"$(test-12-actual)\" == \"$(test-12-expected)\" ]","class":"lineCov","hits":"8","order":"713","possible_hits":"0",},
{"lineNum":"  385","line":"}"},
{"lineNum":"  386","line":""},
{"lineNum":"  387","line":"function test-12-actual () {"},
{"lineNum":"  388","line":"\t# no-op in case content just a comment"},
{"lineNum":"  389","line":"\ttrue","class":"lineCov","hits":"4","order":"707","possible_hits":"0",},
{"lineNum":"  390","line":""},
{"lineNum":"  391","line":""},
{"lineNum":"  392","line":"}"},
{"lineNum":"  393","line":""},
{"lineNum":"  394","line":"function test-12-expected () {"},
{"lineNum":"  395","line":"\t# no-op in case content just a comment"},
{"lineNum":"  396","line":"\ttrue","class":"lineCov","hits":"4","order":"710","possible_hits":"0",},
{"lineNum":"  397","line":""},
{"lineNum":"  398","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"4","order":"711","possible_hits":"0",},
{"lineNum":"  399","line":"# | <<<<<<< tf1.txt"},
{"lineNum":"  400","line":"# | THIS IS THE 1ST FILE.||||||| tf2.txt"},
{"lineNum":"  401","line":"# | THIS IS THE 2ND FILE.======="},
{"lineNum":"  402","line":"# | THIS IS THE 3RD FILE.>>>>>>> tf3.txt"},
{"lineNum":"  403","line":"END_EXPECTED"},
{"lineNum":"  404","line":"}"},
{"lineNum":"  405","line":""},
{"lineNum":"  406","line":""},
{"lineNum":"  407","line":"test_test-2d13() { bats_test_begin \"test-13\";"},
{"lineNum":"  408","line":"\ttestfolder=\"/tmp/batspp-131274/test-13\"","class":"lineCov","hits":"2","order":"714","possible_hits":"0",},
{"lineNum":"  409","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"715","possible_hits":"0",},
{"lineNum":"  410","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"716","possible_hits":"0",},
{"lineNum":"  411","line":""},
{"lineNum":"  412","line":"\techo \"==========\" $\'which python\\n\' \"==========\"","class":"lineCov","hits":"2","order":"717","possible_hits":"0",},
{"lineNum":"  413","line":"\ttest-13-actual","class":"lineCov","hits":"2","order":"718","possible_hits":"0",},
{"lineNum":"  414","line":"\techo \"=========\" $\'# 3A) full-dirname RETURNS THE FULL PATH OF THE FILE\\n$ full-dirname himom.txt | testuser\\n# 3B) base-name-with-dir RETURNS THE BASENAME INCLUDING dir\\n$ basename-with-dir himom.txt\\n/usr/bin/python\\n/tmp/test-unix-alias/test-2899/himom.txt\\n./himom.txt\' \"=========\"","class":"lineCov","hits":"2","order":"721","possible_hits":"0",},
{"lineNum":"  415","line":"\ttest-13-expected","class":"lineCov","hits":"2","order":"722","possible_hits":"0",},
{"lineNum":"  416","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"725","possible_hits":"0",},
{"lineNum":"  417","line":"\t# ???: \'which python\\n\'=$(test-13-actual)"},
{"lineNum":"  418","line":"\t# ???: \'# 3A) full-dirname RETURNS THE FULL PATH OF THE FILE\\n$ full-dirname himom.txt | testuser\\n# 3B) base-name-with-dir RETURNS THE BASENAME INCLUDING dir\\n$ basename-with-dir himom.txt\\n/usr/bin/python\\n/tmp/test-unix-alias/test-2899/himom.txt\\n./himom.txt\'=$(test-13-expected)"},
{"lineNum":"  419","line":"\t[ \"$(test-13-actual)\" == \"$(test-13-expected)\" ]","class":"lineCov","hits":"8","order":"726","possible_hits":"0",},
{"lineNum":"  420","line":"}"},
{"lineNum":"  421","line":""},
{"lineNum":"  422","line":"function test-13-actual () {"},
{"lineNum":"  423","line":"\t# no-op in case content just a comment"},
{"lineNum":"  424","line":"\ttrue","class":"lineCov","hits":"4","order":"719","possible_hits":"0",},
{"lineNum":"  425","line":""},
{"lineNum":"  426","line":"\twhich python","class":"lineCov","hits":"4","order":"720","possible_hits":"0",},
{"lineNum":"  427","line":""},
{"lineNum":"  428","line":"}"},
{"lineNum":"  429","line":""},
{"lineNum":"  430","line":"function test-13-expected () {"},
{"lineNum":"  431","line":"\t# no-op in case content just a comment"},
{"lineNum":"  432","line":"\ttrue","class":"lineCov","hits":"4","order":"723","possible_hits":"0",},
{"lineNum":"  433","line":""},
{"lineNum":"  434","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"4","order":"724","possible_hits":"0",},
{"lineNum":"  435","line":"# 3A) full-dirname RETURNS THE FULL PATH OF THE FILE"},
{"lineNum":"  436","line":"$ full-dirname himom.txt | testuser"},
{"lineNum":"  437","line":"# 3B) base-name-with-dir RETURNS THE BASENAME INCLUDING dir"},
{"lineNum":"  438","line":"$ basename-with-dir himom.txt"},
{"lineNum":"  439","line":"/usr/bin/python"},
{"lineNum":"  440","line":"/tmp/test-unix-alias/test-2899/himom.txt"},
{"lineNum":"  441","line":"./himom.txt"},
{"lineNum":"  442","line":"END_EXPECTED"},
{"lineNum":"  443","line":"}"},
{"lineNum":"  444","line":""},
{"lineNum":"  445","line":""},
{"lineNum":"  446","line":"test_test-2d14() { bats_test_begin \"test-14\";"},
{"lineNum":"  447","line":"\ttestfolder=\"/tmp/batspp-131274/test-14\"","class":"lineCov","hits":"2","order":"727","possible_hits":"0",},
{"lineNum":"  448","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"728","possible_hits":"0",},
{"lineNum":"  449","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"729","possible_hits":"0",},
{"lineNum":"  450","line":""},
{"lineNum":"  451","line":"\techo \"==========\" $\'# $ gtime\\n\' \"==========\"","class":"lineCov","hits":"2","order":"730","possible_hits":"0",},
{"lineNum":"  452","line":"\ttest-14-actual","class":"lineCov","hits":"2","order":"731","possible_hits":"0",},
{"lineNum":"  453","line":"\techo \"=========\" $\"# | /usr/bin/time: missing program to run\\n# | Try \'/usr/bin/time --help\' for more information\\n$ gtime -V | testnum\\ntime (GNU Time) UNKNOWN\\nCopyright (C) NNNN Free Software Foundation, Inc.\\nLicense GPLvN+: GNU GPL version N or later <https://gnu.org/licenses/gpl.html>.\\nThis is free software: you are free to change and redistribute it.\\nThere is NO WARRANTY, to the extent permitted by law.\" \"=========\"","class":"lineCov","hits":"2","order":"733","possible_hits":"0",},
{"lineNum":"  454","line":"\ttest-14-expected","class":"lineCov","hits":"2","order":"734","possible_hits":"0",},
{"lineNum":"  455","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"737","possible_hits":"0",},
{"lineNum":"  456","line":"\t# ???: \'# $ gtime\\n\'=$(test-14-actual)"},
{"lineNum":"  457","line":"\t# ???: \"# | /usr/bin/time: missing program to run\\n# | Try \'/usr/bin/time --help\' for more information\\n$ gtime -V | testnum\\ntime (GNU Time) UNKNOWN\\nCopyright (C) NNNN Free Software Foundation, Inc.\\nLicense GPLvN+: GNU GPL version N or later <https://gnu.org/licenses/gpl.html>.\\nThis is free software: you are free to change and redistribute it.\\nThere is NO WARRANTY, to the extent permitted by law.\"=$(test-14-expected)"},
{"lineNum":"  458","line":"\t[ \"$(test-14-actual)\" == \"$(test-14-expected)\" ]","class":"lineCov","hits":"8","order":"738","possible_hits":"0",},
{"lineNum":"  459","line":"}"},
{"lineNum":"  460","line":""},
{"lineNum":"  461","line":"function test-14-actual () {"},
{"lineNum":"  462","line":"\t# no-op in case content just a comment"},
{"lineNum":"  463","line":"\ttrue","class":"lineCov","hits":"4","order":"732","possible_hits":"0",},
{"lineNum":"  464","line":""},
{"lineNum":"  465","line":""},
{"lineNum":"  466","line":"}"},
{"lineNum":"  467","line":""},
{"lineNum":"  468","line":"function test-14-expected () {"},
{"lineNum":"  469","line":"\t# no-op in case content just a comment"},
{"lineNum":"  470","line":"\ttrue","class":"lineCov","hits":"4","order":"735","possible_hits":"0",},
{"lineNum":"  471","line":""},
{"lineNum":"  472","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"4","order":"736","possible_hits":"0",},
{"lineNum":"  473","line":"# | /usr/bin/time: missing program to run"},
{"lineNum":"  474","line":"# | Try \'/usr/bin/time --help\' for more information"},
{"lineNum":"  475","line":"$ gtime -V | testnum"},
{"lineNum":"  476","line":"time (GNU Time) UNKNOWN"},
{"lineNum":"  477","line":"Copyright (C) NNNN Free Software Foundation, Inc."},
{"lineNum":"  478","line":"License GPLvN+: GNU GPL version N or later <https://gnu.org/licenses/gpl.html>."},
{"lineNum":"  479","line":"This is free software: you are free to change and redistribute it."},
{"lineNum":"  480","line":"There is NO WARRANTY, to the extent permitted by law."},
{"lineNum":"  481","line":"END_EXPECTED"},
{"lineNum":"  482","line":"}"},
{"lineNum":"  483","line":""},
{"lineNum":"  484","line":""},
{"lineNum":"  485","line":"test_test-2d15() { bats_test_begin \"test-15\";"},
{"lineNum":"  486","line":"\ttestfolder=\"/tmp/batspp-131274/test-15\"","class":"lineCov","hits":"2","order":"739","possible_hits":"0",},
{"lineNum":"  487","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"740","possible_hits":"0",},
{"lineNum":"  488","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"741","possible_hits":"0",},
{"lineNum":"  489","line":""},
{"lineNum":"  490","line":"\techo \"==========\" $\'linux-version | grep VERSION_ID | testnum\\n\' \"==========\"","class":"lineCov","hits":"2","order":"742","possible_hits":"0",},
{"lineNum":"  491","line":"\ttest-15-actual","class":"lineCov","hits":"2","order":"743","possible_hits":"0",},
{"lineNum":"  492","line":"\techo \"=========\" $\'# os-release ALSO WORKS SAME AS linux-version\\nVERSION_ID=\"NN.NN\"\' \"=========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  493","line":"\ttest-15-expected","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  494","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  495","line":"\t# ???: \'linux-version | grep VERSION_ID | testnum\\n\'=$(test-15-actual)"},
{"lineNum":"  496","line":"\t# ???: \'# os-release ALSO WORKS SAME AS linux-version\\nVERSION_ID=\"NN.NN\"\'=$(test-15-expected)"},
{"lineNum":"  497","line":"\t[ \"$(test-15-actual)\" == \"$(test-15-expected)\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  498","line":"}"},
{"lineNum":"  499","line":""},
{"lineNum":"  500","line":"function test-15-actual () {"},
{"lineNum":"  501","line":"\t# no-op in case content just a comment"},
{"lineNum":"  502","line":"\ttrue","class":"lineCov","hits":"2","order":"744","possible_hits":"0",},
{"lineNum":"  503","line":""},
{"lineNum":"  504","line":"\tlinux-version | grep VERSION_ID | testnum","class":"lineCov","hits":"8","order":"745","possible_hits":"0",},
{"lineNum":"  505","line":""},
{"lineNum":"  506","line":"}"},
{"lineNum":"  507","line":""},
{"lineNum":"  508","line":"function test-15-expected () {"},
{"lineNum":"  509","line":"\t# no-op in case content just a comment"},
{"lineNum":"  510","line":"\ttrue","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  511","line":""},
{"lineNum":"  512","line":"\tcat <<END_EXPECTED","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  513","line":"# os-release ALSO WORKS SAME AS linux-version"},
{"lineNum":"  514","line":"VERSION_ID=\"NN.NN\""},
{"lineNum":"  515","line":"END_EXPECTED"},
{"lineNum":"  516","line":"}"},
{"lineNum":"  517","line":""},
{"lineNum":"  518","line":""},
{"lineNum":"  519","line":"test_test-2d16() { bats_test_begin \"test-16\";"},
{"lineNum":"  520","line":"\ttestfolder=\"/tmp/batspp-131274/test-16\"","class":"lineCov","hits":"2","order":"747","possible_hits":"0",},
{"lineNum":"  521","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"748","possible_hits":"0",},
{"lineNum":"  522","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"749","possible_hits":"0",},
{"lineNum":"  523","line":""},
{"lineNum":"  524","line":"\techo \"==========\" $\'system-status | testnum | testuser | tail -n +2 | awk \\\'!($8=\"\")\\\'\\n\' \"==========\"","class":"lineCov","hits":"2","order":"750","possible_hits":"0",},
{"lineNum":"  525","line":"\ttest-16-actual","class":"lineCov","hits":"2","order":"751","possible_hits":"0",},
{"lineNum":"  526","line":"\techo \"=========\" $\'total used free shared buff/cache available  \\nMem: NNNNNNN NNNNNNN NNNNNN NNNNNN NNNNNN NNNNNN \\nSwap: NNNNNNN NNNNNNN NNNNNNN    \\nNN:NN:NN up N:NN, N user, load average:  N.NN, N.NN\\nUSER TTY FROM LOGIN@ IDLE JCPU PCPU \\nuserxf333 ttyN :N NN:NN N:NNm NN:NN N.NNs\' \"=========\"","class":"lineCov","hits":"2","order":"754","possible_hits":"0",},
{"lineNum":"  527","line":"\ttest-16-expected","class":"lineCov","hits":"2","order":"755","possible_hits":"0",},
{"lineNum":"  528","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"758","possible_hits":"0",},
{"lineNum":"  529","line":"\t# ???: \'system-status | testnum | testuser | tail -n +2 | awk \\\'!($8=\"\")\\\'\\n\'=$(test-16-actual)"},
{"lineNum":"  530","line":"\t# ???: \'total used free shared buff/cache available  \\nMem: NNNNNNN NNNNNNN NNNNNN NNNNNN NNNNNN NNNNNN \\nSwap: NNNNNNN NNNNNNN NNNNNNN    \\nNN:NN:NN up N:NN, N user, load average:  N.NN, N.NN\\nUSER TTY FROM LOGIN@ IDLE JCPU PCPU \\nuserxf333 ttyN :N NN:NN N:NNm NN:NN N.NNs\'=$(test-16-expected)"},
{"lineNum":"  531","line":"\t[ \"$(test-16-actual)\" == \"$(test-16-expected)\" ]","class":"lineCov","hits":"8","order":"759","possible_hits":"0",},
{"lineNum":"  532","line":"}"},
{"lineNum":"  533","line":""},
{"lineNum":"  534","line":"function test-16-actual () {"},
{"lineNum":"  535","line":"\t# no-op in case content just a comment"},
{"lineNum":"  536","line":"\ttrue","class":"lineCov","hits":"4","order":"752","possible_hits":"0",},
{"lineNum":"  537","line":""},
{"lineNum":"  538","line":"\tsystem-status | testnum | testuser | tail -n +2 | awk \'!($8=\"\")\'","class":"lineCov","hits":"20","order":"753","possible_hits":"0",},
{"lineNum":"  539","line":""},
{"lineNum":"  540","line":"}"},
{"lineNum":"  541","line":""},
{"lineNum":"  542","line":"function test-16-expected () {"},
{"lineNum":"  543","line":"\t# no-op in case content just a comment"},
{"lineNum":"  544","line":"\ttrue","class":"lineCov","hits":"4","order":"756","possible_hits":"0",},
{"lineNum":"  545","line":""},
{"lineNum":"  546","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"4","order":"757","possible_hits":"0",},
{"lineNum":"  547","line":"total used free shared buff/cache available"},
{"lineNum":"  548","line":"Mem: NNNNNNN NNNNNNN NNNNNN NNNNNN NNNNNN NNNNNN"},
{"lineNum":"  549","line":"Swap: NNNNNNN NNNNNNN NNNNNNN"},
{"lineNum":"  550","line":"NN:NN:NN up N:NN, N user, load average:  N.NN, N.NN"},
{"lineNum":"  551","line":"USER TTY FROM LOGIN@ IDLE JCPU PCPU"},
{"lineNum":"  552","line":"userxf333 ttyN :N NN:NN N:NNm NN:NN N.NNs"},
{"lineNum":"  553","line":"END_EXPECTED"},
{"lineNum":"  554","line":"}"},
{"lineNum":"  555","line":""},
{"lineNum":"  556","line":""},
{"lineNum":"  557","line":"test_test-2d17() { bats_test_begin \"test-17\";"},
{"lineNum":"  558","line":"\ttestfolder=\"/tmp/batspp-131274/test-17\"","class":"lineCov","hits":"2","order":"760","possible_hits":"0",},
{"lineNum":"  559","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"761","possible_hits":"0",},
{"lineNum":"  560","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"762","possible_hits":"0",},
{"lineNum":"  561","line":""},
{"lineNum":"  562","line":"\techo \"==========\" $\'apropos-command time | grep asctime | wc -l | testnum\\n\' \"==========\"","class":"lineCov","hits":"2","order":"763","possible_hits":"0",},
{"lineNum":"  563","line":"\ttest-17-actual","class":"lineCov","hits":"2","order":"764","possible_hits":"0",},
{"lineNum":"  564","line":"\techo \"=========\" $\'N\' \"=========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  565","line":"\ttest-17-expected","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  566","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  567","line":"\t# ???: \'apropos-command time | grep asctime | wc -l | testnum\\n\'=$(test-17-actual)"},
{"lineNum":"  568","line":"\t# ???: \'N\'=$(test-17-expected)"},
{"lineNum":"  569","line":"\t[ \"$(test-17-actual)\" == \"$(test-17-expected)\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  570","line":"}"},
{"lineNum":"  571","line":""},
{"lineNum":"  572","line":"function test-17-actual () {"},
{"lineNum":"  573","line":"\t# no-op in case content just a comment"},
{"lineNum":"  574","line":"\ttrue","class":"lineCov","hits":"2","order":"765","possible_hits":"0",},
{"lineNum":"  575","line":""},
{"lineNum":"  576","line":"\tapropos-command time | grep asctime | wc -l | testnum","class":"lineCov","hits":"10","order":"766","possible_hits":"0",},
{"lineNum":"  577","line":""},
{"lineNum":"  578","line":"}"},
{"lineNum":"  579","line":""},
{"lineNum":"  580","line":"function test-17-expected () {"},
{"lineNum":"  581","line":"\t# no-op in case content just a comment"},
{"lineNum":"  582","line":"\ttrue","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  583","line":""},
{"lineNum":"  584","line":"\tcat <<END_EXPECTED","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  585","line":"N"},
{"lineNum":"  586","line":"END_EXPECTED"},
{"lineNum":"  587","line":"}"},
{"lineNum":"  588","line":""},
{"lineNum":"  589","line":""},
{"lineNum":"  590","line":"test_test-2d18() { bats_test_begin \"test-18\";"},
{"lineNum":"  591","line":"\ttestfolder=\"/tmp/batspp-131274/test-18\"","class":"lineCov","hits":"2","order":"767","possible_hits":"0",},
{"lineNum":"  592","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"768","possible_hits":"0",},
{"lineNum":"  593","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"769","possible_hits":"0",},
{"lineNum":"  594","line":""},
{"lineNum":"  595","line":"\techo \"==========\" $\'cat hidad.txt\\n\' \"==========\"","class":"lineCov","hits":"2","order":"770","possible_hits":"0",},
{"lineNum":"  596","line":"\ttest-18-actual","class":"lineCov","hits":"2","order":"771","possible_hits":"0",},
{"lineNum":"  597","line":"\techo \"=========\" $\'$ linebr\\n$ split-tokens hidad.txt\\nHi Dad!\\n--------------------------------------------------------------------------------\\nHi\\nDad!\' \"=========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  598","line":"\ttest-18-expected","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  599","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  600","line":"\t# ???: \'cat hidad.txt\\n\'=$(test-18-actual)"},
{"lineNum":"  601","line":"\t# ???: \'$ linebr\\n$ split-tokens hidad.txt\\nHi Dad!\\n--------------------------------------------------------------------------------\\nHi\\nDad!\'=$(test-18-expected)"},
{"lineNum":"  602","line":"\t[ \"$(test-18-actual)\" == \"$(test-18-expected)\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  603","line":"}"},
{"lineNum":"  604","line":""},
{"lineNum":"  605","line":"function test-18-actual () {"},
{"lineNum":"  606","line":"\t# no-op in case content just a comment"},
{"lineNum":"  607","line":"\ttrue","class":"lineCov","hits":"2","order":"772","possible_hits":"0",},
{"lineNum":"  608","line":""},
{"lineNum":"  609","line":"\tcat hidad.txt","class":"lineCov","hits":"4","order":"773","possible_hits":"0",},
{"lineNum":"  610","line":""},
{"lineNum":"  611","line":"}"},
{"lineNum":"  612","line":""},
{"lineNum":"  613","line":"function test-18-expected () {"},
{"lineNum":"  614","line":"\t# no-op in case content just a comment"},
{"lineNum":"  615","line":"\ttrue","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  616","line":""},
{"lineNum":"  617","line":"\tcat <<END_EXPECTED","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  618","line":"$ linebr"},
{"lineNum":"  619","line":"$ split-tokens hidad.txt"},
{"lineNum":"  620","line":"Hi Dad!"},
{"lineNum":"  621","line":"--------------------------------------------------------------------------------"},
{"lineNum":"  622","line":"Hi"},
{"lineNum":"  623","line":"Dad!"},
{"lineNum":"  624","line":"END_EXPECTED"},
{"lineNum":"  625","line":"}"},
{"lineNum":"  626","line":""},
{"lineNum":"  627","line":""},
{"lineNum":"  628","line":"test_test-2d19() { bats_test_begin \"test-19\";"},
{"lineNum":"  629","line":"\ttestfolder=\"/tmp/batspp-131274/test-19\"","class":"lineCov","hits":"2","order":"774","possible_hits":"0",},
{"lineNum":"  630","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"775","possible_hits":"0",},
{"lineNum":"  631","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"776","possible_hits":"0",},
{"lineNum":"  632","line":""},
{"lineNum":"  633","line":"\techo \"==========\" $\'tokenize _old_make.log\\n\' \"==========\"","class":"lineCov","hits":"2","order":"777","possible_hits":"0",},
{"lineNum":"  634","line":"\ttest-19-actual","class":"lineCov","hits":"2","order":"778","possible_hits":"0",},
{"lineNum":"  635","line":"\techo \"=========\" $\"make:\\nNothing\\nto\\nbe\\ndone\\nfor\\n\'himom.txt\'.\" \"=========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  636","line":"\ttest-19-expected","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  637","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  638","line":"\t# ???: \'tokenize _old_make.log\\n\'=$(test-19-actual)"},
{"lineNum":"  639","line":"\t# ???: \"make:\\nNothing\\nto\\nbe\\ndone\\nfor\\n\'himom.txt\'.\"=$(test-19-expected)"},
{"lineNum":"  640","line":"\t[ \"$(test-19-actual)\" == \"$(test-19-expected)\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  641","line":"}"},
{"lineNum":"  642","line":""},
{"lineNum":"  643","line":"function test-19-actual () {"},
{"lineNum":"  644","line":"\t# no-op in case content just a comment"},
{"lineNum":"  645","line":"\ttrue","class":"lineCov","hits":"2","order":"779","possible_hits":"0",},
{"lineNum":"  646","line":""},
{"lineNum":"  647","line":"\ttokenize _old_make.log","class":"lineCov","hits":"4","order":"780","possible_hits":"0",},
{"lineNum":"  648","line":""},
{"lineNum":"  649","line":"}"},
{"lineNum":"  650","line":""},
{"lineNum":"  651","line":"function test-19-expected () {"},
{"lineNum":"  652","line":"\t# no-op in case content just a comment"},
{"lineNum":"  653","line":"\ttrue","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  654","line":""},
{"lineNum":"  655","line":"\tcat <<END_EXPECTED","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  656","line":"make:"},
{"lineNum":"  657","line":"Nothing"},
{"lineNum":"  658","line":"to"},
{"lineNum":"  659","line":"be"},
{"lineNum":"  660","line":"done"},
{"lineNum":"  661","line":"for"},
{"lineNum":"  662","line":"\'himom.txt\'."},
{"lineNum":"  663","line":"END_EXPECTED"},
{"lineNum":"  664","line":"}"},
{"lineNum":"  665","line":""},
{"lineNum":"  666","line":""},
{"lineNum":"  667","line":"test_test-2d20() { bats_test_begin \"test-20\";"},
{"lineNum":"  668","line":"\ttestfolder=\"/tmp/batspp-131274/test-20\"","class":"lineCov","hits":"2","order":"781","possible_hits":"0",},
{"lineNum":"  669","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"782","possible_hits":"0",},
{"lineNum":"  670","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"783","possible_hits":"0",},
{"lineNum":"  671","line":""},
{"lineNum":"  672","line":"\techo \"==========\" $\"PERL_PRINT=\'This is Ubuntu!\'\\n\" \"==========\"","class":"lineCov","hits":"2","order":"784","possible_hits":"0",},
{"lineNum":"  673","line":"\ttest-20-actual","class":"lineCov","hits":"2","order":"785","possible_hits":"0",},
{"lineNum":"  674","line":"\techo \"=========\" $\'$ perl-echo $PERL_PRINT\\n$ perl-echo-sans-newline $PERL_PRINT\\nThis\\nThis\' \"=========\"","class":"lineCov","hits":"2","order":"788","possible_hits":"0",},
{"lineNum":"  675","line":"\ttest-20-expected","class":"lineCov","hits":"2","order":"789","possible_hits":"0",},
{"lineNum":"  676","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"792","possible_hits":"0",},
{"lineNum":"  677","line":"\t# ???: \"PERL_PRINT=\'This is Ubuntu!\'\\n\"=$(test-20-actual)"},
{"lineNum":"  678","line":"\t# ???: \'$ perl-echo $PERL_PRINT\\n$ perl-echo-sans-newline $PERL_PRINT\\nThis\\nThis\'=$(test-20-expected)"},
{"lineNum":"  679","line":"\t[ \"$(test-20-actual)\" == \"$(test-20-expected)\" ]","class":"lineCov","hits":"8","order":"793","possible_hits":"0",},
{"lineNum":"  680","line":"}"},
{"lineNum":"  681","line":""},
{"lineNum":"  682","line":"function test-20-actual () {"},
{"lineNum":"  683","line":"\t# no-op in case content just a comment"},
{"lineNum":"  684","line":"\ttrue","class":"lineCov","hits":"4","order":"786","possible_hits":"0",},
{"lineNum":"  685","line":""},
{"lineNum":"  686","line":"\tPERL_PRINT=\'This is Ubuntu!\'","class":"lineCov","hits":"4","order":"787","possible_hits":"0",},
{"lineNum":"  687","line":""},
{"lineNum":"  688","line":"}"},
{"lineNum":"  689","line":""},
{"lineNum":"  690","line":"function test-20-expected () {"},
{"lineNum":"  691","line":"\t# no-op in case content just a comment"},
{"lineNum":"  692","line":"\ttrue","class":"lineCov","hits":"4","order":"790","possible_hits":"0",},
{"lineNum":"  693","line":""},
{"lineNum":"  694","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"4","order":"791","possible_hits":"0",},
{"lineNum":"  695","line":"$ perl-echo $PERL_PRINT"},
{"lineNum":"  696","line":"$ perl-echo-sans-newline $PERL_PRINT"},
{"lineNum":"  697","line":"This"},
{"lineNum":"  698","line":"This"},
{"lineNum":"  699","line":"END_EXPECTED"},
{"lineNum":"  700","line":"}"},
{"lineNum":"  701","line":""},
{"lineNum":"  702","line":""},
{"lineNum":"  703","line":"test_test-2d21() { bats_test_begin \"test-21\";"},
{"lineNum":"  704","line":"\ttestfolder=\"/tmp/batspp-131274/test-21\"","class":"lineCov","hits":"2","order":"794","possible_hits":"0",},
{"lineNum":"  705","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"795","possible_hits":"0",},
{"lineNum":"  706","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"796","possible_hits":"0",},
{"lineNum":"  707","line":""},
{"lineNum":"  708","line":"\techo \"==========\" $\"perl-printf \'ONE KISS IS ALL IT TAKES\\\\n\'\\n\" \"==========\"","class":"lineCov","hits":"2","order":"797","possible_hits":"0",},
{"lineNum":"  709","line":"\ttest-21-actual","class":"lineCov","hits":"2","order":"798","possible_hits":"0",},
{"lineNum":"  710","line":"\techo \"=========\" $\'$ perl-print \\\'2\\\\n3\\\\n5\\\\n7\\\\n11\\\'\\n$ perl-print-n \\\'A B C D E F G\\\\n\\\'\\n$ quote-tokens \\\'HELP ME!\\\'\\nONE KISS IS ALL IT TAKES\\n2\\n3\\n5\\n7\\n11\\nA B C D E F G\\n\"HELP\" \"ME!\"\' \"=========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  711","line":"\ttest-21-expected","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  712","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  713","line":"\t# ???: \"perl-printf \'ONE KISS IS ALL IT TAKES\\\\n\'\\n\"=$(test-21-actual)"},
{"lineNum":"  714","line":"\t# ???: \'$ perl-print \\\'2\\\\n3\\\\n5\\\\n7\\\\n11\\\'\\n$ perl-print-n \\\'A B C D E F G\\\\n\\\'\\n$ quote-tokens \\\'HELP ME!\\\'\\nONE KISS IS ALL IT TAKES\\n2\\n3\\n5\\n7\\n11\\nA B C D E F G\\n\"HELP\" \"ME!\"\'=$(test-21-expected)"},
{"lineNum":"  715","line":"\t[ \"$(test-21-actual)\" == \"$(test-21-expected)\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  716","line":"}"},
{"lineNum":"  717","line":""},
{"lineNum":"  718","line":"function test-21-actual () {"},
{"lineNum":"  719","line":"\t# no-op in case content just a comment"},
{"lineNum":"  720","line":"\ttrue","class":"lineCov","hits":"2","order":"799","possible_hits":"0",},
{"lineNum":"  721","line":""},
{"lineNum":"  722","line":"\tperl-printf \'ONE KISS IS ALL IT TAKES\\n\'","class":"lineCov","hits":"4","order":"800","possible_hits":"0",},
{"lineNum":"  723","line":""},
{"lineNum":"  724","line":"}"},
{"lineNum":"  725","line":""},
{"lineNum":"  726","line":"function test-21-expected () {"},
{"lineNum":"  727","line":"\t# no-op in case content just a comment"},
{"lineNum":"  728","line":"\ttrue","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  729","line":""},
{"lineNum":"  730","line":"\tcat <<END_EXPECTED","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  731","line":"$ perl-print \'2\\n3\\n5\\n7\\n11\'"},
{"lineNum":"  732","line":"$ perl-print-n \'A B C D E F G\\n\'"},
{"lineNum":"  733","line":"$ quote-tokens \'HELP ME!\'"},
{"lineNum":"  734","line":"ONE KISS IS ALL IT TAKES"},
{"lineNum":"  735","line":"2"},
{"lineNum":"  736","line":"3"},
{"lineNum":"  737","line":"5"},
{"lineNum":"  738","line":"7"},
{"lineNum":"  739","line":"11"},
{"lineNum":"  740","line":"A B C D E F G"},
{"lineNum":"  741","line":"\"HELP\" \"ME!\""},
{"lineNum":"  742","line":"END_EXPECTED"},
{"lineNum":"  743","line":"}"},
{"lineNum":"  744","line":""},
{"lineNum":"  745","line":""},
{"lineNum":"  746","line":"test_test-2d22() { bats_test_begin \"test-22\";"},
{"lineNum":"  747","line":"\ttestfolder=\"/tmp/batspp-131274/test-22\"","class":"lineCov","hits":"2","order":"801","possible_hits":"0",},
{"lineNum":"  748","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"802","possible_hits":"0",},
{"lineNum":"  749","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"803","possible_hits":"0",},
{"lineNum":"  750","line":""},
{"lineNum":"  751","line":"\techo \"==========\" $\'set-display-local\\n\' \"==========\"","class":"lineCov","hits":"2","order":"804","possible_hits":"0",},
{"lineNum":"  752","line":"\ttest-22-actual","class":"lineCov","hits":"2","order":"805","possible_hits":"0",},
{"lineNum":"  753","line":"\techo \"=========\" $\'$ echo $DISPLAY | testnum\\nlocalhost:N.N\' \"=========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  754","line":"\ttest-22-expected","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  755","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  756","line":"\t# ???: \'set-display-local\\n\'=$(test-22-actual)"},
{"lineNum":"  757","line":"\t# ???: \'$ echo $DISPLAY | testnum\\nlocalhost:N.N\'=$(test-22-expected)"},
{"lineNum":"  758","line":"\t[ \"$(test-22-actual)\" == \"$(test-22-expected)\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  759","line":"}"},
{"lineNum":"  760","line":""},
{"lineNum":"  761","line":"function test-22-actual () {"},
{"lineNum":"  762","line":"\t# no-op in case content just a comment"},
{"lineNum":"  763","line":"\ttrue","class":"lineCov","hits":"2","order":"806","possible_hits":"0",},
{"lineNum":"  764","line":""},
{"lineNum":"  765","line":"\tset-display-local","class":"lineCov","hits":"4","order":"807","possible_hits":"0",},
{"lineNum":"  766","line":""},
{"lineNum":"  767","line":"}"},
{"lineNum":"  768","line":""},
{"lineNum":"  769","line":"function test-22-expected () {"},
{"lineNum":"  770","line":"\t# no-op in case content just a comment"},
{"lineNum":"  771","line":"\ttrue","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  772","line":""},
{"lineNum":"  773","line":"\tcat <<END_EXPECTED","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  774","line":"$ echo $DISPLAY | testnum"},
{"lineNum":"  775","line":"localhost:N.N"},
{"lineNum":"  776","line":"END_EXPECTED"},
{"lineNum":"  777","line":"}"},
{"lineNum":"  778","line":""},
{"lineNum":"  779","line":""},
{"lineNum":"  780","line":"test_test-2d23() { bats_test_begin \"test-23\";"},
{"lineNum":"  781","line":"\ttestfolder=\"/tmp/batspp-131274/test-23\"","class":"lineCov","hits":"2","order":"808","possible_hits":"0",},
{"lineNum":"  782","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"809","possible_hits":"0",},
{"lineNum":"  783","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"810","possible_hits":"0",},
{"lineNum":"  784","line":""},
{"lineNum":"  785","line":"\techo \"==========\" $\'bash-trace-on | testuser | testnum\\n\' \"==========\"","class":"lineCov","hits":"2","order":"811","possible_hits":"0",},
{"lineNum":"  786","line":"\ttest-23-actual","class":"lineCov","hits":"2","order":"812","possible_hits":"0",},
{"lineNum":"  787","line":"\techo \"=========\" $\'$ linebr\\n## trace-cmd TRACES COMMANDS AND STATS (TIME) OF THE USER\\n$ trace-cmd | testuser | testnum\\n## bash-trace-on DISABLES bash tracing\\n$ bash-trace-off | testuser | testnum\\n$ linebr\\n$ trace-cmd | testuser | testnum\\n--------------------------------------------------------------------------------\\nstart: Thu Dec  N NN:NN:NN PM +NNNN NNNN\\n+ eval\\n+ set - -o xtrace\\nend: Thu Dec  N NN:NN:NN PM +NNNN NNNN\\n--------------------------------------------------------------------------------\\nstart: Thu Dec  N NN:NN:NN PM +NNNN NNNN\\n+ eval\\n+ set - -o xtrace\\nend: Thu Dec  N NN:NN:NN PM +NNNN NNNN\' \"=========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  788","line":"\ttest-23-expected","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  789","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  790","line":"\t# ???: \'bash-trace-on | testuser | testnum\\n\'=$(test-23-actual)"},
{"lineNum":"  791","line":"\t# ???: \'$ linebr\\n## trace-cmd TRACES COMMANDS AND STATS (TIME) OF THE USER\\n$ trace-cmd | testuser | testnum\\n## bash-trace-on DISABLES bash tracing\\n$ bash-trace-off | testuser | testnum\\n$ linebr\\n$ trace-cmd | testuser | testnum\\n--------------------------------------------------------------------------------\\nstart: Thu Dec  N NN:NN:NN PM +NNNN NNNN\\n+ eval\\n+ set - -o xtrace\\nend: Thu Dec  N NN:NN:NN PM +NNNN NNNN\\n--------------------------------------------------------------------------------\\nstart: Thu Dec  N NN:NN:NN PM +NNNN NNNN\\n+ eval\\n+ set - -o xtrace\\nend: Thu Dec  N NN:NN:NN PM +NNNN NNNN\'=$(test-23-expected)"},
{"lineNum":"  792","line":"\t[ \"$(test-23-actual)\" == \"$(test-23-expected)\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  793","line":"}"},
{"lineNum":"  794","line":""},
{"lineNum":"  795","line":"function test-23-actual () {"},
{"lineNum":"  796","line":"\t# no-op in case content just a comment"},
{"lineNum":"  797","line":"\ttrue","class":"lineCov","hits":"2","order":"813","possible_hits":"0",},
{"lineNum":"  798","line":""},
{"lineNum":"  799","line":"\tbash-trace-on | testuser | testnum","class":"lineCov","hits":"8","order":"814","possible_hits":"0",},
{"lineNum":"  800","line":""},
{"lineNum":"  801","line":"}"},
{"lineNum":"  802","line":""},
{"lineNum":"  803","line":"function test-23-expected () {"},
{"lineNum":"  804","line":"\t# no-op in case content just a comment"},
{"lineNum":"  805","line":"\ttrue","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  806","line":""},
{"lineNum":"  807","line":"\tcat <<END_EXPECTED","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  808","line":"$ linebr"},
{"lineNum":"  809","line":"## trace-cmd TRACES COMMANDS AND STATS (TIME) OF THE USER"},
{"lineNum":"  810","line":"$ trace-cmd | testuser | testnum"},
{"lineNum":"  811","line":"## bash-trace-on DISABLES bash tracing"},
{"lineNum":"  812","line":"$ bash-trace-off | testuser | testnum"},
{"lineNum":"  813","line":"$ linebr"},
{"lineNum":"  814","line":"$ trace-cmd | testuser | testnum"},
{"lineNum":"  815","line":"--------------------------------------------------------------------------------"},
{"lineNum":"  816","line":"start: Thu Dec  N NN:NN:NN PM +NNNN NNNN"},
{"lineNum":"  817","line":"+ eval"},
{"lineNum":"  818","line":"+ set - -o xtrace"},
{"lineNum":"  819","line":"end: Thu Dec  N NN:NN:NN PM +NNNN NNNN"},
{"lineNum":"  820","line":"--------------------------------------------------------------------------------"},
{"lineNum":"  821","line":"start: Thu Dec  N NN:NN:NN PM +NNNN NNNN"},
{"lineNum":"  822","line":"+ eval"},
{"lineNum":"  823","line":"+ set - -o xtrace"},
{"lineNum":"  824","line":"end: Thu Dec  N NN:NN:NN PM +NNNN NNNN"},
{"lineNum":"  825","line":"END_EXPECTED"},
{"lineNum":"  826","line":"}"},
{"lineNum":"  827","line":""},
{"lineNum":"  828","line":""},
{"lineNum":"  829","line":"test_test-2d24() { bats_test_begin \"test-24\";"},
{"lineNum":"  830","line":"\ttestfolder=\"/tmp/batspp-131274/test-24\"","class":"lineCov","hits":"2","order":"815","possible_hits":"0",},
{"lineNum":"  831","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"816","possible_hits":"0",},
{"lineNum":"  832","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"817","possible_hits":"0",},
{"lineNum":"  833","line":""},
{"lineNum":"  834","line":"\techo \"==========\" $\'ls\\n\' \"==========\"","class":"lineCov","hits":"2","order":"818","possible_hits":"0",},
{"lineNum":"  835","line":"\ttest-24-actual","class":"lineCov","hits":"2","order":"819","possible_hits":"0",},
{"lineNum":"  836","line":"\techo \"=========\" $\"$ cp tf2.txt testfolder/\\n$ linebr\\n$ compress-this-dir ./testfolder | testnum\\n$ linebr\\n$ ls\\n$ linebr\\n$ ununcompress-this-dir ./testfolder | testnum\\nhidad.txt  _make.log\\t  testfolder  tf2.txt\\nhimom.txt  _old_make.log  tf1.txt     tf3.txt\\n\'tf2.txt\' -> \'testfolder/tf2.txt\'\\n--------------------------------------------------------------------------------\\ngzip: /tmp/test-unix-alias/test-NNNN is a directory -- ignored\\n/tmp/test-unix-alias/test-NNNN/hidad.txt:\\t-NN.N% -- replaced with /tmp/test-unix-alias/test-NNNN/hidad.txt.gz\\n/tmp/test-unix-alias/test-NNNN/himom.txt:\\t-NN.N% -- replaced with /tmp/test-unix-alias/test-NNNN/himom.txt.gz\\n/tmp/test-unix-alias/test-NNNN/tfN.txt:\\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/tfN.txt.gz\\n/tmp/test-unix-alias/test-NNNN/tfN.txt:\\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/tfN.txt.gz\\ngzip: /tmp/test-unix-alias/test-NNNN/testfolder is a directory -- ignored\\n/tmp/test-unix-alias/test-NNNN/testfolder/tfN.txt:\\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/testfolder/tfN.txt.gz\\n/tmp/test-unix-alias/test-NNNN/_old_make.log:\\t -N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/_old_make.log.gz\\n/tmp/test-unix-alias/test-NNNN/tfN.txt:\\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/tfN.txt.gz\\n/tmp/test-unix-alias/test-NNNN/_make.log:\\t -N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/_make.log.gz\\n--------------------------------------------------------------------------------\\nhidad.txt.gz  _make.log.gz\\ttestfolder  tf2.txt.gz\\nhimom.txt.gz  _old_make.log.gz\\ttf1.txt.gz  tf3.txt.gz\\n--------------------------------------------------------------------------------\\ngzip: /tmp/test-unix-alias/test-NNNN is a directory -- ignored\\n/tmp/test-unix-alias/test-NNNN/_make.log.gz:\\t -N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/_make.log\\n/tmp/test-unix-alias/test-NNNN/tfN.txt.gz:\\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/tfN.txt\\n/tmp/test-unix-alias/test-NNNN/tfN.txt.gz:\\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/tfN.txt\\n/tmp/test-unix-alias/test-NNNN/_old_make.log.gz:\\t -N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/_old_make.log\\n/tmp/test-unix-alias/test-NNNN/himom.txt.gz:\\t-NN.N% -- replaced with /tmp/test-unix-alias/test-NNNN/himom.txt\\n/tmp/test-unix-alias/test-NNNN/hidad.txt.gz:\\t-NN.N% -- replaced with /tmp/test-unix-alias/test-NNNN/hidad.txt\\ngzip: /tmp/test-unix-alias/test-NNNN/testfolder is a directory -- ignored\\n/tmp/test-unix-alias/test-NNNN/testfolder/tfN.txt.gz:\\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/testfolder/tfN.txt\\n/tmp/test-unix-alias/test-NNNN/tfN.txt.gz:\\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/tfN.txt\" \"=========\"","class":"lineCov","hits":"2","order":"822","possible_hits":"0",},
{"lineNum":"  837","line":"\ttest-24-expected","class":"lineCov","hits":"2","order":"823","possible_hits":"0",},
{"lineNum":"  838","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"826","possible_hits":"0",},
{"lineNum":"  839","line":"\t# ???: \'ls\\n\'=$(test-24-actual)"},
{"lineNum":"  840","line":"\t# ???: \"$ cp tf2.txt testfolder/\\n$ linebr\\n$ compress-this-dir ./testfolder | testnum\\n$ linebr\\n$ ls\\n$ linebr\\n$ ununcompress-this-dir ./testfolder | testnum\\nhidad.txt  _make.log\\t  testfolder  tf2.txt\\nhimom.txt  _old_make.log  tf1.txt     tf3.txt\\n\'tf2.txt\' -> \'testfolder/tf2.txt\'\\n--------------------------------------------------------------------------------\\ngzip: /tmp/test-unix-alias/test-NNNN is a directory -- ignored\\n/tmp/test-unix-alias/test-NNNN/hidad.txt:\\t-NN.N% -- replaced with /tmp/test-unix-alias/test-NNNN/hidad.txt.gz\\n/tmp/test-unix-alias/test-NNNN/himom.txt:\\t-NN.N% -- replaced with /tmp/test-unix-alias/test-NNNN/himom.txt.gz\\n/tmp/test-unix-alias/test-NNNN/tfN.txt:\\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/tfN.txt.gz\\n/tmp/test-unix-alias/test-NNNN/tfN.txt:\\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/tfN.txt.gz\\ngzip: /tmp/test-unix-alias/test-NNNN/testfolder is a directory -- ignored\\n/tmp/test-unix-alias/test-NNNN/testfolder/tfN.txt:\\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/testfolder/tfN.txt.gz\\n/tmp/test-unix-alias/test-NNNN/_old_make.log:\\t -N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/_old_make.log.gz\\n/tmp/test-unix-alias/test-NNNN/tfN.txt:\\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/tfN.txt.gz\\n/tmp/test-unix-alias/test-NNNN/_make.log:\\t -N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/_make.log.gz\\n--------------------------------------------------------------------------------\\nhidad.txt.gz  _make.log.gz\\ttestfolder  tf2.txt.gz\\nhimom.txt.gz  _old_make.log.gz\\ttf1.txt.gz  tf3.txt.gz\\n--------------------------------------------------------------------------------\\ngzip: /tmp/test-unix-alias/test-NNNN is a directory -- ignored\\n/tmp/test-unix-alias/test-NNNN/_make.log.gz:\\t -N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/_make.log\\n/tmp/test-unix-alias/test-NNNN/tfN.txt.gz:\\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/tfN.txt\\n/tmp/test-unix-alias/test-NNNN/tfN.txt.gz:\\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/tfN.txt\\n/tmp/test-unix-alias/test-NNNN/_old_make.log.gz:\\t -N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/_old_make.log\\n/tmp/test-unix-alias/test-NNNN/himom.txt.gz:\\t-NN.N% -- replaced with /tmp/test-unix-alias/test-NNNN/himom.txt\\n/tmp/test-unix-alias/test-NNNN/hidad.txt.gz:\\t-NN.N% -- replaced with /tmp/test-unix-alias/test-NNNN/hidad.txt\\ngzip: /tmp/test-unix-alias/test-NNNN/testfolder is a directory -- ignored\\n/tmp/test-unix-alias/test-NNNN/testfolder/tfN.txt.gz:\\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/testfolder/tfN.txt\\n/tmp/test-unix-alias/test-NNNN/tfN.txt.gz:\\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/tfN.txt\"=$(test-24-expected)"},
{"lineNum":"  841","line":"\t[ \"$(test-24-actual)\" == \"$(test-24-expected)\" ]","class":"lineCov","hits":"8","order":"827","possible_hits":"0",},
{"lineNum":"  842","line":"}"},
{"lineNum":"  843","line":""},
{"lineNum":"  844","line":"function test-24-actual () {"},
{"lineNum":"  845","line":"\t# no-op in case content just a comment"},
{"lineNum":"  846","line":"\ttrue","class":"lineCov","hits":"4","order":"820","possible_hits":"0",},
{"lineNum":"  847","line":""},
{"lineNum":"  848","line":"\tls","class":"lineCov","hits":"4","order":"821","possible_hits":"0",},
{"lineNum":"  849","line":""},
{"lineNum":"  850","line":"}"},
{"lineNum":"  851","line":""},
{"lineNum":"  852","line":"function test-24-expected () {"},
{"lineNum":"  853","line":"\t# no-op in case content just a comment"},
{"lineNum":"  854","line":"\ttrue","class":"lineCov","hits":"4","order":"824","possible_hits":"0",},
{"lineNum":"  855","line":""},
{"lineNum":"  856","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"4","order":"825","possible_hits":"0",},
{"lineNum":"  857","line":"$ cp tf2.txt testfolder/"},
{"lineNum":"  858","line":"$ linebr"},
{"lineNum":"  859","line":"$ compress-this-dir ./testfolder | testnum"},
{"lineNum":"  860","line":"$ linebr"},
{"lineNum":"  861","line":"$ ls"},
{"lineNum":"  862","line":"$ linebr"},
{"lineNum":"  863","line":"$ ununcompress-this-dir ./testfolder | testnum"},
{"lineNum":"  864","line":"hidad.txt  _make.log\t  testfolder  tf2.txt"},
{"lineNum":"  865","line":"himom.txt  _old_make.log  tf1.txt     tf3.txt"},
{"lineNum":"  866","line":"\'tf2.txt\' -> \'testfolder/tf2.txt\'"},
{"lineNum":"  867","line":"--------------------------------------------------------------------------------"},
{"lineNum":"  868","line":"gzip: /tmp/test-unix-alias/test-NNNN is a directory -- ignored"},
{"lineNum":"  869","line":"/tmp/test-unix-alias/test-NNNN/hidad.txt:\t-NN.N% -- replaced with /tmp/test-unix-alias/test-NNNN/hidad.txt.gz"},
{"lineNum":"  870","line":"/tmp/test-unix-alias/test-NNNN/himom.txt:\t-NN.N% -- replaced with /tmp/test-unix-alias/test-NNNN/himom.txt.gz"},
{"lineNum":"  871","line":"/tmp/test-unix-alias/test-NNNN/tfN.txt:\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/tfN.txt.gz"},
{"lineNum":"  872","line":"/tmp/test-unix-alias/test-NNNN/tfN.txt:\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/tfN.txt.gz"},
{"lineNum":"  873","line":"gzip: /tmp/test-unix-alias/test-NNNN/testfolder is a directory -- ignored"},
{"lineNum":"  874","line":"/tmp/test-unix-alias/test-NNNN/testfolder/tfN.txt:\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/testfolder/tfN.txt.gz"},
{"lineNum":"  875","line":"/tmp/test-unix-alias/test-NNNN/_old_make.log:\t -N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/_old_make.log.gz"},
{"lineNum":"  876","line":"/tmp/test-unix-alias/test-NNNN/tfN.txt:\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/tfN.txt.gz"},
{"lineNum":"  877","line":"/tmp/test-unix-alias/test-NNNN/_make.log:\t -N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/_make.log.gz"},
{"lineNum":"  878","line":"--------------------------------------------------------------------------------"},
{"lineNum":"  879","line":"hidad.txt.gz  _make.log.gz\ttestfolder  tf2.txt.gz"},
{"lineNum":"  880","line":"himom.txt.gz  _old_make.log.gz\ttf1.txt.gz  tf3.txt.gz"},
{"lineNum":"  881","line":"--------------------------------------------------------------------------------"},
{"lineNum":"  882","line":"gzip: /tmp/test-unix-alias/test-NNNN is a directory -- ignored"},
{"lineNum":"  883","line":"/tmp/test-unix-alias/test-NNNN/_make.log.gz:\t -N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/_make.log"},
{"lineNum":"  884","line":"/tmp/test-unix-alias/test-NNNN/tfN.txt.gz:\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/tfN.txt"},
{"lineNum":"  885","line":"/tmp/test-unix-alias/test-NNNN/tfN.txt.gz:\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/tfN.txt"},
{"lineNum":"  886","line":"/tmp/test-unix-alias/test-NNNN/_old_make.log.gz:\t -N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/_old_make.log"},
{"lineNum":"  887","line":"/tmp/test-unix-alias/test-NNNN/himom.txt.gz:\t-NN.N% -- replaced with /tmp/test-unix-alias/test-NNNN/himom.txt"},
{"lineNum":"  888","line":"/tmp/test-unix-alias/test-NNNN/hidad.txt.gz:\t-NN.N% -- replaced with /tmp/test-unix-alias/test-NNNN/hidad.txt"},
{"lineNum":"  889","line":"gzip: /tmp/test-unix-alias/test-NNNN/testfolder is a directory -- ignored"},
{"lineNum":"  890","line":"/tmp/test-unix-alias/test-NNNN/testfolder/tfN.txt.gz:\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/testfolder/tfN.txt"},
{"lineNum":"  891","line":"/tmp/test-unix-alias/test-NNNN/tfN.txt.gz:\t  N.N% -- replaced with /tmp/test-unix-alias/test-NNNN/tfN.txt"},
{"lineNum":"  892","line":"END_EXPECTED"},
{"lineNum":"  893","line":"}"},
{"lineNum":"  894","line":""},
{"lineNum":"  895","line":""},
{"lineNum":"  896","line":"test_test-2d25() { bats_test_begin \"test-25\";"},
{"lineNum":"  897","line":"\ttestfolder=\"/tmp/batspp-131274/test-25\"","class":"lineCov","hits":"2","order":"828","possible_hits":"0",},
{"lineNum":"  898","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"829","possible_hits":"0",},
{"lineNum":"  899","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"830","possible_hits":"0",},
{"lineNum":"  900","line":""},
{"lineNum":"  901","line":"\techo \"==========\" $\'# $ kill-iceweasel\\n\' \"==========\"","class":"lineCov","hits":"2","order":"831","possible_hits":"0",},
{"lineNum":"  902","line":"\ttest-25-actual","class":"lineCov","hits":"2","order":"832","possible_hits":"0",},
{"lineNum":"  903","line":"\techo \"=========\" $\'# | pattern=/:[0-9][0-9] [^ ]*iceweasel/\\n# | filter=/($)(^)/\\n# | Warning: No processes matched the pattern\' \"=========\"","class":"lineCov","hits":"2","order":"834","possible_hits":"0",},
{"lineNum":"  904","line":"\ttest-25-expected","class":"lineCov","hits":"2","order":"835","possible_hits":"0",},
{"lineNum":"  905","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"838","possible_hits":"0",},
{"lineNum":"  906","line":"\t# ???: \'# $ kill-iceweasel\\n\'=$(test-25-actual)"},
{"lineNum":"  907","line":"\t# ???: \'# | pattern=/:[0-9][0-9] [^ ]*iceweasel/\\n# | filter=/($)(^)/\\n# | Warning: No processes matched the pattern\'=$(test-25-expected)"},
{"lineNum":"  908","line":"\t[ \"$(test-25-actual)\" == \"$(test-25-expected)\" ]","class":"lineCov","hits":"8","order":"839","possible_hits":"0",},
{"lineNum":"  909","line":"}"},
{"lineNum":"  910","line":""},
{"lineNum":"  911","line":"function test-25-actual () {"},
{"lineNum":"  912","line":"\t# no-op in case content just a comment"},
{"lineNum":"  913","line":"\ttrue","class":"lineCov","hits":"4","order":"833","possible_hits":"0",},
{"lineNum":"  914","line":""},
{"lineNum":"  915","line":""},
{"lineNum":"  916","line":"}"},
{"lineNum":"  917","line":""},
{"lineNum":"  918","line":"function test-25-expected () {"},
{"lineNum":"  919","line":"\t# no-op in case content just a comment"},
{"lineNum":"  920","line":"\ttrue","class":"lineCov","hits":"4","order":"836","possible_hits":"0",},
{"lineNum":"  921","line":""},
{"lineNum":"  922","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"4","order":"837","possible_hits":"0",},
{"lineNum":"  923","line":"# | pattern=/:[0-9][0-9] [^ ]*iceweasel/"},
{"lineNum":"  924","line":"# | filter=/($)(^)/"},
{"lineNum":"  925","line":"# | Warning: No processes matched the pattern"},
{"lineNum":"  926","line":"END_EXPECTED"},
{"lineNum":"  927","line":"}"},
{"lineNum":"  928","line":""},
{"lineNum":"  929","line":""},
{"lineNum":"  930","line":"test_test-2d26() { bats_test_begin \"test-26\";"},
{"lineNum":"  931","line":"\ttestfolder=\"/tmp/batspp-131274/test-26\"","class":"lineCov","hits":"2","order":"840","possible_hits":"0",},
{"lineNum":"  932","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"841","possible_hits":"0",},
{"lineNum":"  933","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"842","possible_hits":"0",},
{"lineNum":"  934","line":""},
{"lineNum":"  935","line":"\techo \"==========\" $\'old-count-exts | testnum\\n\' \"==========\"","class":"lineCov","hits":"2","order":"843","possible_hits":"0",},
{"lineNum":"  936","line":"\ttest-26-actual","class":"lineCov","hits":"2","order":"844","possible_hits":"0",},
{"lineNum":"  937","line":"\techo \"=========\" $\'$ linebr\\n$ count-exts | testnum\\n.txt\\tN\\n.log\\tN\\n--------------------------------------------------------------------------------\\n.txt\\tN\\n.log\\tN\' \"=========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  938","line":"\ttest-26-expected","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  939","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  940","line":"\t# ???: \'old-count-exts | testnum\\n\'=$(test-26-actual)"},
{"lineNum":"  941","line":"\t# ???: \'$ linebr\\n$ count-exts | testnum\\n.txt\\tN\\n.log\\tN\\n--------------------------------------------------------------------------------\\n.txt\\tN\\n.log\\tN\'=$(test-26-expected)"},
{"lineNum":"  942","line":"\t[ \"$(test-26-actual)\" == \"$(test-26-expected)\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  943","line":"}"},
{"lineNum":"  944","line":""},
{"lineNum":"  945","line":"function test-26-actual () {"},
{"lineNum":"  946","line":"\t# no-op in case content just a comment"},
{"lineNum":"  947","line":"\ttrue","class":"lineCov","hits":"2","order":"845","possible_hits":"0",},
{"lineNum":"  948","line":""},
{"lineNum":"  949","line":"\told-count-exts | testnum","class":"lineCov","hits":"6","order":"846","possible_hits":"0",},
{"lineNum":"  950","line":""},
{"lineNum":"  951","line":"}"},
{"lineNum":"  952","line":""},
{"lineNum":"  953","line":"function test-26-expected () {"},
{"lineNum":"  954","line":"\t# no-op in case content just a comment"},
{"lineNum":"  955","line":"\ttrue","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  956","line":""},
{"lineNum":"  957","line":"\tcat <<END_EXPECTED","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  958","line":"$ linebr"},
{"lineNum":"  959","line":"$ count-exts | testnum"},
{"lineNum":"  960","line":".txt\tN"},
{"lineNum":"  961","line":".log\tN"},
{"lineNum":"  962","line":"--------------------------------------------------------------------------------"},
{"lineNum":"  963","line":".txt\tN"},
{"lineNum":"  964","line":".log\tN"},
{"lineNum":"  965","line":"END_EXPECTED"},
{"lineNum":"  966","line":"}"},
{"lineNum":"  967","line":""},
{"lineNum":"  968","line":""},
{"lineNum":"  969","line":"test_test-2d27() { bats_test_begin \"test-27\";"},
{"lineNum":"  970","line":"\ttestfolder=\"/tmp/batspp-131274/test-27\"","class":"lineCov","hits":"2","order":"847","possible_hits":"0",},
{"lineNum":"  971","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"848","possible_hits":"0",},
{"lineNum":"  972","line":"\tcd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"849","possible_hits":"0",},
{"lineNum":"  973","line":""},
{"lineNum":"  974","line":"\techo \"==========\" $\'echo \"Done!\"\\n\' \"==========\"","class":"lineCov","hits":"2","order":"850","possible_hits":"0",},
{"lineNum":"  975","line":"\ttest-27-actual","class":"lineCov","hits":"2","order":"851","possible_hits":"0",},
{"lineNum":"  976","line":"\techo \"=========\" $\'Done!\' \"=========\"","class":"lineCov","hits":"2","order":"854","possible_hits":"0",},
{"lineNum":"  977","line":"\ttest-27-expected","class":"lineCov","hits":"2","order":"855","possible_hits":"0",},
{"lineNum":"  978","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"858","possible_hits":"0",},
{"lineNum":"  979","line":"\t# ???: \'echo \"Done!\"\\n\'=$(test-27-actual)"},
{"lineNum":"  980","line":"\t# ???: \'Done!\'=$(test-27-expected)"},
{"lineNum":"  981","line":"\t[ \"$(test-27-actual)\" == \"$(test-27-expected)\" ]","class":"lineCov","hits":"6","order":"859","possible_hits":"0",},
{"lineNum":"  982","line":"}"},
{"lineNum":"  983","line":""},
{"lineNum":"  984","line":"function test-27-actual () {"},
{"lineNum":"  985","line":"\t# no-op in case content just a comment"},
{"lineNum":"  986","line":"\ttrue","class":"lineCov","hits":"4","order":"852","possible_hits":"0",},
{"lineNum":"  987","line":""},
{"lineNum":"  988","line":"\techo \"Done!\"","class":"lineCov","hits":"4","order":"853","possible_hits":"0",},
{"lineNum":"  989","line":""},
{"lineNum":"  990","line":"}"},
{"lineNum":"  991","line":""},
{"lineNum":"  992","line":"function test-27-expected () {"},
{"lineNum":"  993","line":"\t# no-op in case content just a comment"},
{"lineNum":"  994","line":"\ttrue","class":"lineCov","hits":"4","order":"856","possible_hits":"0",},
{"lineNum":"  995","line":""},
{"lineNum":"  996","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"4","order":"857","possible_hits":"0",},
{"lineNum":"  997","line":"Done!"},
{"lineNum":"  998","line":"END_EXPECTED"},
{"lineNum":"  999","line":"}"},
{"lineNum":" 1000","line":""},
{"lineNum":" 1001","line":"bats_test_function --tags \'\' test_test-2d1","class":"lineCov","hits":"28","order":"350","possible_hits":"0",},
{"lineNum":" 1002","line":"bats_test_function --tags \'\' test_test-2d3","class":"lineCov","hits":"28","order":"351","possible_hits":"0",},
{"lineNum":" 1003","line":"bats_test_function --tags \'\' test_test-2d4","class":"lineCov","hits":"28","order":"352","possible_hits":"0",},
{"lineNum":" 1004","line":"bats_test_function --tags \'\' test_test-2d5","class":"lineCov","hits":"28","order":"353","possible_hits":"0",},
{"lineNum":" 1005","line":"bats_test_function --tags \'\' test_test-2d6","class":"lineCov","hits":"28","order":"354","possible_hits":"0",},
{"lineNum":" 1006","line":"bats_test_function --tags \'\' test_test-2d7","class":"lineCov","hits":"28","order":"355","possible_hits":"0",},
{"lineNum":" 1007","line":"bats_test_function --tags \'\' test_test-2d8","class":"lineCov","hits":"28","order":"356","possible_hits":"0",},
{"lineNum":" 1008","line":"bats_test_function --tags \'\' test_test-2d9","class":"lineCov","hits":"28","order":"357","possible_hits":"0",},
{"lineNum":" 1009","line":"bats_test_function --tags \'\' test_test-2d10","class":"lineCov","hits":"28","order":"358","possible_hits":"0",},
{"lineNum":" 1010","line":"bats_test_function --tags \'\' test_test-2d11","class":"lineCov","hits":"28","order":"359","possible_hits":"0",},
{"lineNum":" 1011","line":"bats_test_function --tags \'\' test_test-2d12","class":"lineCov","hits":"28","order":"360","possible_hits":"0",},
{"lineNum":" 1012","line":"bats_test_function --tags \'\' test_test-2d13","class":"lineCov","hits":"28","order":"361","possible_hits":"0",},
{"lineNum":" 1013","line":"bats_test_function --tags \'\' test_test-2d14","class":"lineCov","hits":"28","order":"362","possible_hits":"0",},
{"lineNum":" 1014","line":"bats_test_function --tags \'\' test_test-2d15","class":"lineCov","hits":"28","order":"363","possible_hits":"0",},
{"lineNum":" 1015","line":"bats_test_function --tags \'\' test_test-2d16","class":"lineCov","hits":"28","order":"364","possible_hits":"0",},
{"lineNum":" 1016","line":"bats_test_function --tags \'\' test_test-2d17","class":"lineCov","hits":"28","order":"365","possible_hits":"0",},
{"lineNum":" 1017","line":"bats_test_function --tags \'\' test_test-2d18","class":"lineCov","hits":"28","order":"366","possible_hits":"0",},
{"lineNum":" 1018","line":"bats_test_function --tags \'\' test_test-2d19","class":"lineCov","hits":"28","order":"367","possible_hits":"0",},
{"lineNum":" 1019","line":"bats_test_function --tags \'\' test_test-2d20","class":"lineCov","hits":"28","order":"368","possible_hits":"0",},
{"lineNum":" 1020","line":"bats_test_function --tags \'\' test_test-2d21","class":"lineCov","hits":"28","order":"369","possible_hits":"0",},
{"lineNum":" 1021","line":"bats_test_function --tags \'\' test_test-2d22","class":"lineCov","hits":"28","order":"370","possible_hits":"0",},
{"lineNum":" 1022","line":"bats_test_function --tags \'\' test_test-2d23","class":"lineCov","hits":"28","order":"371","possible_hits":"0",},
{"lineNum":" 1023","line":"bats_test_function --tags \'\' test_test-2d24","class":"lineCov","hits":"28","order":"372","possible_hits":"0",},
{"lineNum":" 1024","line":"bats_test_function --tags \'\' test_test-2d25","class":"lineCov","hits":"28","order":"373","possible_hits":"0",},
{"lineNum":" 1025","line":"bats_test_function --tags \'\' test_test-2d26","class":"lineCov","hits":"28","order":"374","possible_hits":"0",},
{"lineNum":" 1026","line":"bats_test_function --tags \'\' test_test-2d27","class":"lineCov","hits":"28","order":"375","possible_hits":"0",},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "bats", "date" : "2023-05-19 18:20:21", "instrumented" : 361, "covered" : 307,};
var merged_data = [];
