var data = {lines:[
{"lineNum":"    1","line":"#!/usr/bin/env bats"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":""},
{"lineNum":"    4","line":"# Make executables ./tests/../ visible to PATH"},
{"lineNum":"    5","line":"PATH=\"/home/aveey/tom-project/shell-scripts/tests/batspp-only/../:$PATH\"","class":"lineCov","hits":"33","order":"333","possible_hits":"0",},
{"lineNum":"    6","line":""},
{"lineNum":"    7","line":"# Source files"},
{"lineNum":"    8","line":"shopt -s expand_aliases","class":"lineCov","hits":"33","order":"349","possible_hits":"0",},
{"lineNum":"    9","line":""},
{"lineNum":"   10","line":""},
{"lineNum":"   11","line":"test_test0() { bats_test_begin \"test0\";"},
{"lineNum":"   12","line":"\ttest_folder=$(echo /tmp/test0-$$)","class":"lineCov","hits":"4","order":"456","possible_hits":"0",},
{"lineNum":"   13","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"457","possible_hits":"0",},
{"lineNum":"   14","line":""},
{"lineNum":"   15","line":"}"},
{"lineNum":"   16","line":""},
{"lineNum":"   17","line":""},
{"lineNum":"   18","line":"test_test1() { bats_test_begin \"test1\";"},
{"lineNum":"   19","line":"\ttest_folder=$(echo /tmp/test1-$$)","class":"lineCov","hits":"4","order":"496","possible_hits":"0",},
{"lineNum":"   20","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"497","possible_hits":"0",},
{"lineNum":"   21","line":""},
{"lineNum":"   22","line":"\tunalias -a","class":"lineCov","hits":"2","order":"498","possible_hits":"0",},
{"lineNum":"   23","line":"\talias | wc -l","class":"lineCov","hits":"4","order":"499","possible_hits":"0",},
{"lineNum":"   24","line":"\tfor f in $(typeset -f | egrep \'^\\w+\'); do unset -f $f; done","class":"lineCov","hits":"66","order":"500","possible_hits":"0",},
{"lineNum":"   25","line":"\tactual=$(test1-assert4-actual)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   26","line":"\texpected=$(test1-assert4-expected)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   27","line":"\techo \"========== actual ==========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   28","line":"\techo \"$actual\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   29","line":"\techo \"========= expected =========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   30","line":"\techo \"$expected\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   31","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   32","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   33","line":""},
{"lineNum":"   34","line":"}"},
{"lineNum":"   35","line":""},
{"lineNum":"   36","line":"function test1-assert4-actual () {"},
{"lineNum":"   37","line":"\ttypeset -f | egrep \'^\\w+\' | wc -l","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   38","line":"}"},
{"lineNum":"   39","line":"function test1-assert4-expected () {"},
{"lineNum":"   40","line":"\techo -e \'00\'","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"   41","line":"}"},
{"lineNum":"   42","line":""},
{"lineNum":"   43","line":"test_test2() { bats_test_begin \"test2\";"},
{"lineNum":"   44","line":"\ttest_folder=$(echo /tmp/test2-$$)","class":"lineCov","hits":"4","order":"592","possible_hits":"0",},
{"lineNum":"   45","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"593","possible_hits":"0",},
{"lineNum":"   46","line":""},
{"lineNum":"   47","line":"\tTMP=/tmp/test-py-commands","class":"lineCov","hits":"2","order":"594","possible_hits":"0",},
{"lineNum":"   48","line":"\tactual=$(test2-assert2-actual)","class":"lineCov","hits":"4","order":"595","possible_hits":"0",},
{"lineNum":"   49","line":"\texpected=$(test2-assert2-expected)","class":"lineCov","hits":"4","order":"597","possible_hits":"0",},
{"lineNum":"   50","line":"\techo \"========== actual ==========\"","class":"lineCov","hits":"2","order":"599","possible_hits":"0",},
{"lineNum":"   51","line":"\techo \"$actual\" | hexview.perl","class":"lineCov","hits":"4","order":"600","possible_hits":"0",},
{"lineNum":"   52","line":"\techo \"========= expected =========\"","class":"lineCov","hits":"2","order":"601","possible_hits":"0",},
{"lineNum":"   53","line":"\techo \"$expected\" | hexview.perl","class":"lineCov","hits":"4","order":"602","possible_hits":"0",},
{"lineNum":"   54","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"603","possible_hits":"0",},
{"lineNum":"   55","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineCov","hits":"2","order":"604","possible_hits":"0",},
{"lineNum":"   56","line":""},
{"lineNum":"   57","line":"}"},
{"lineNum":"   58","line":""},
{"lineNum":"   59","line":"function test2-assert2-actual () {"},
{"lineNum":"   60","line":"\talias | wc -l","class":"lineCov","hits":"4","order":"596","possible_hits":"0",},
{"lineNum":"   61","line":"}"},
{"lineNum":"   62","line":"function test2-assert2-expected () {"},
{"lineNum":"   63","line":"\techo -e \'0\'","class":"lineCov","hits":"2","order":"598","possible_hits":"0",},
{"lineNum":"   64","line":"}"},
{"lineNum":"   65","line":""},
{"lineNum":"   66","line":"test_test3() { bats_test_begin \"test3\";"},
{"lineNum":"   67","line":"\ttest_folder=$(echo /tmp/test3-$$)","class":"lineCov","hits":"4","order":"605","possible_hits":"0",},
{"lineNum":"   68","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"606","possible_hits":"0",},
{"lineNum":"   69","line":""},
{"lineNum":"   70","line":"\ttemp_dir=$TMP/test-7766","class":"lineCov","hits":"2","order":"607","possible_hits":"0",},
{"lineNum":"   71","line":"\tcd \"$temp_dir\"","class":"lineCov","hits":"4","order":"608","possible_hits":"0",},
{"lineNum":"   72","line":"}"},
{"lineNum":"   73","line":""},
{"lineNum":"   74","line":""},
{"lineNum":"   75","line":"test_test4() { bats_test_begin \"test4\";"},
{"lineNum":"   76","line":"\ttest_folder=$(echo /tmp/test4-$$)","class":"lineCov","hits":"4","order":"610","possible_hits":"0",},
{"lineNum":"   77","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"611","possible_hits":"0",},
{"lineNum":"   78","line":""},
{"lineNum":"   79","line":"\talias testuser=\"sed -r \"s/\"$USER\"+/userxf333/g\"\"","class":"lineCov","hits":"2","order":"612","possible_hits":"0",},
{"lineNum":"   80","line":"}"},
{"lineNum":"   81","line":""},
{"lineNum":"   82","line":""},
{"lineNum":"   83","line":"test_test5() { bats_test_begin \"test5\";"},
{"lineNum":"   84","line":"\ttest_folder=$(echo /tmp/test5-$$)","class":"lineCov","hits":"4","order":"613","possible_hits":"0",},
{"lineNum":"   85","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"614","possible_hits":"0",},
{"lineNum":"   86","line":""},
{"lineNum":"   87","line":"\tsource $BIN_DIR/tomohara-aliases.bash","class":"lineCov","hits":"2","order":"615","possible_hits":"0",},
{"lineNum":"   88","line":"}"},
{"lineNum":"   89","line":""},
{"lineNum":"   90","line":""},
{"lineNum":"   91","line":"test_test6() { bats_test_begin \"test6\";"},
{"lineNum":"   92","line":"\ttest_folder=$(echo /tmp/test6-$$)","class":"lineCov","hits":"4","order":"617","possible_hits":"0",},
{"lineNum":"   93","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"618","possible_hits":"0",},
{"lineNum":"   94","line":""},
{"lineNum":"   95","line":"}"},
{"lineNum":"   96","line":""},
{"lineNum":"   97","line":""},
{"lineNum":"   98","line":"test_test7() { bats_test_begin \"test7\";"},
{"lineNum":"   99","line":"\ttest_folder=$(echo /tmp/test7-$$)","class":"lineCov","hits":"4","order":"619","possible_hits":"0",},
{"lineNum":"  100","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"620","possible_hits":"0",},
{"lineNum":"  101","line":""},
{"lineNum":"  102","line":"}"},
{"lineNum":"  103","line":""},
{"lineNum":"  104","line":""},
{"lineNum":"  105","line":"test_test8() { bats_test_begin \"test8\";"},
{"lineNum":"  106","line":"\ttest_folder=$(echo /tmp/test8-$$)","class":"lineCov","hits":"4","order":"621","possible_hits":"0",},
{"lineNum":"  107","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"622","possible_hits":"0",},
{"lineNum":"  108","line":""},
{"lineNum":"  109","line":"\tactual=$(test8-assert1-actual)","class":"lineCov","hits":"7","order":"623","possible_hits":"0",},
{"lineNum":"  110","line":"\texpected=$(test8-assert1-expected)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  111","line":"\techo \"========== actual ==========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  112","line":"\techo \"$actual\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  113","line":"\techo \"========= expected =========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  114","line":"\techo \"$expected\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  115","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  116","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  117","line":""},
{"lineNum":"  118","line":"}"},
{"lineNum":"  119","line":""},
{"lineNum":"  120","line":"function test8-assert1-actual () {"},
{"lineNum":"  121","line":"\tshow-python-path | testuser","class":"lineCov","hits":"6","order":"624","possible_hits":"0",},
{"lineNum":"  122","line":"}"},
{"lineNum":"  123","line":"function test8-assert1-expected () {"},
{"lineNum":"  124","line":"\techo -e \'PYTHONPATH:/home/userxf333/python\'","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  125","line":"}"},
{"lineNum":"  126","line":""},
{"lineNum":"  127","line":"test_test9() { bats_test_begin \"test9\";"},
{"lineNum":"  128","line":"\ttest_folder=$(echo /tmp/test9-$$)","class":"lineCov","hits":"4","order":"625","possible_hits":"0",},
{"lineNum":"  129","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"626","possible_hits":"0",},
{"lineNum":"  130","line":""},
{"lineNum":"  131","line":"}"},
{"lineNum":"  132","line":""},
{"lineNum":"  133","line":""},
{"lineNum":"  134","line":"test_test10() { bats_test_begin \"test10\";"},
{"lineNum":"  135","line":"\ttest_folder=$(echo /tmp/test10-$$)","class":"lineCov","hits":"4","order":"627","possible_hits":"0",},
{"lineNum":"  136","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"628","possible_hits":"0",},
{"lineNum":"  137","line":""},
{"lineNum":"  138","line":"}"},
{"lineNum":"  139","line":""},
{"lineNum":"  140","line":""},
{"lineNum":"  141","line":"test_test11() { bats_test_begin \"test11\";"},
{"lineNum":"  142","line":"\ttest_folder=$(echo /tmp/test11-$$)","class":"lineCov","hits":"4","order":"629","possible_hits":"0",},
{"lineNum":"  143","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"630","possible_hits":"0",},
{"lineNum":"  144","line":""},
{"lineNum":"  145","line":"}"},
{"lineNum":"  146","line":""},
{"lineNum":"  147","line":""},
{"lineNum":"  148","line":"test_test12() { bats_test_begin \"test12\";"},
{"lineNum":"  149","line":"\ttest_folder=$(echo /tmp/test12-$$)","class":"lineCov","hits":"4","order":"631","possible_hits":"0",},
{"lineNum":"  150","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"632","possible_hits":"0",},
{"lineNum":"  151","line":""},
{"lineNum":"  152","line":"}"},
{"lineNum":"  153","line":""},
{"lineNum":"  154","line":""},
{"lineNum":"  155","line":"test_test13() { bats_test_begin \"test13\";"},
{"lineNum":"  156","line":"\ttest_folder=$(echo /tmp/test13-$$)","class":"lineCov","hits":"4","order":"633","possible_hits":"0",},
{"lineNum":"  157","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"634","possible_hits":"0",},
{"lineNum":"  158","line":""},
{"lineNum":"  159","line":"\tpython-import-path \'mezcla\' | testnum","class":"lineCov","hits":"6","order":"635","possible_hits":"0",},
{"lineNum":"  160","line":"\tlinebr","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  161","line":"\tpython-import-path-full \'mezcla\' | testnum","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  162","line":"\tactual=$(test13-assert4-actual)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  163","line":"\texpected=$(test13-assert4-expected)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  164","line":"\techo \"========== actual ==========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  165","line":"\techo \"$actual\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  166","line":"\techo \"========= expected =========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  167","line":"\techo \"$expected\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  168","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  169","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  170","line":""},
{"lineNum":"  171","line":"}"},
{"lineNum":"  172","line":""},
{"lineNum":"  173","line":"function test13-assert4-actual () {"},
{"lineNum":"  174","line":"\tpython-import-path-all \'mezcla\' | grep mezcla | head -n 5 | testnum","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  175","line":"}"},
{"lineNum":"  176","line":"function test13-assert4-expected () {"},
{"lineNum":"  177","line":"\techo -e \"matches /usr/local/lib/pythonN.NN/dist-packages/mezcla/__init__.py--------------------------------------------------------------------------------matches /usr/local/lib/pythonN.NN/dist-packages/mezcla/__init__.pymatches /usr/local/lib/pythonN.NN/dist-packages/mezcla/debug.pymatches /usr/local/lib/pythonN.NN/dist-packages/mezcla/sys_version_info_hack.pymatches /usr/local/lib/pythonN.NN/dist-packages/mezcla/glue_helpers.pymatches /usr/local/lib/pythonN.NN/dist-packages/mezcla/system.pymatches /usr/local/lib/pythonN.NN/dist-packages/mezcla/tpo_common.py--------------------------------------------------------------------------------# /usr/local/lib/pythonN.NN/dist-packages/mezcla/__pycache__/__init__.cpython-NNN.pyc matches /usr/local/lib/pythonN.NN/dist-packages/mezcla/__init__.py# code object from \'/usr/local/lib/pythonN.NN/dist-packages/mezcla/__pycache__/__init__.cpython-NNN.pyc\'# /usr/local/lib/pythonN.NN/dist-packages/mezcla/__pycache__/debug.cpython-NNN.pyc matches /usr/local/lib/pythonN.NN/dist-packages/mezcla/debug.py# code object from \'/usr/local/lib/pythonN.NN/dist-packages/mezcla/__pycache__/debug.cpython-NNN.pyc\'# /usr/local/lib/pythonN.NN/dist-packages/mezcla/__pycache__/sys_version_info_hack.cpython-NNN.pyc matches /usr/local/lib/pythonN.NN/dist-packages/mezcla/sys_version_info_hack.py\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  178","line":"}"},
{"lineNum":"  179","line":""},
{"lineNum":"  180","line":"test_test14() { bats_test_begin \"test14\";"},
{"lineNum":"  181","line":"\ttest_folder=$(echo /tmp/test14-$$)","class":"lineCov","hits":"4","order":"636","possible_hits":"0",},
{"lineNum":"  182","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"637","possible_hits":"0",},
{"lineNum":"  183","line":""},
{"lineNum":"  184","line":"\trm -rf ./* > /dev/null","class":"lineCov","hits":"2","order":"638","possible_hits":"0",},
{"lineNum":"  185","line":"\tactual=$(test14-assert2-actual)","class":"lineCov","hits":"4","order":"639","possible_hits":"0",},
{"lineNum":"  186","line":"\texpected=$(test14-assert2-expected)","class":"lineCov","hits":"4","order":"641","possible_hits":"0",},
{"lineNum":"  187","line":"\techo \"========== actual ==========\"","class":"lineCov","hits":"2","order":"643","possible_hits":"0",},
{"lineNum":"  188","line":"\techo \"$actual\" | hexview.perl","class":"lineCov","hits":"4","order":"644","possible_hits":"0",},
{"lineNum":"  189","line":"\techo \"========= expected =========\"","class":"lineCov","hits":"2","order":"645","possible_hits":"0",},
{"lineNum":"  190","line":"\techo \"$expected\" | hexview.perl","class":"lineCov","hits":"4","order":"646","possible_hits":"0",},
{"lineNum":"  191","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"647","possible_hits":"0",},
{"lineNum":"  192","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineCov","hits":"2","order":"648","possible_hits":"0",},
{"lineNum":"  193","line":""},
{"lineNum":"  194","line":"}"},
{"lineNum":"  195","line":""},
{"lineNum":"  196","line":"function test14-assert2-actual () {"},
{"lineNum":"  197","line":"\tpip3 freeze | grep ipython | wc -l","class":"lineCov","hits":"6","order":"640","possible_hits":"0",},
{"lineNum":"  198","line":"}"},
{"lineNum":"  199","line":"function test14-assert2-expected () {"},
{"lineNum":"  200","line":"\techo -e \'2\'","class":"lineCov","hits":"2","order":"642","possible_hits":"0",},
{"lineNum":"  201","line":"}"},
{"lineNum":"  202","line":""},
{"lineNum":"  203","line":"test_test15() { bats_test_begin \"test15\";"},
{"lineNum":"  204","line":"\ttest_folder=$(echo /tmp/test15-$$)","class":"lineCov","hits":"4","order":"649","possible_hits":"0",},
{"lineNum":"  205","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"650","possible_hits":"0",},
{"lineNum":"  206","line":""},
{"lineNum":"  207","line":"\tpython-module-version-full mezcla | testnum","class":"lineCov","hits":"6","order":"651","possible_hits":"0",},
{"lineNum":"  208","line":"\tlinebr","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  209","line":"\tpython-module-version mezcla | testnum","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  210","line":"\tlinebr","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  211","line":"\tpython-package-members mezcla | testnum","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  212","line":"\tactual=$(test15-assert6-actual)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  213","line":"\texpected=$(test15-assert6-expected)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  214","line":"\techo \"========== actual ==========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  215","line":"\techo \"$actual\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  216","line":"\techo \"========= expected =========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  217","line":"\techo \"$expected\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  218","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  219","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  220","line":""},
{"lineNum":"  221","line":"}"},
{"lineNum":"  222","line":""},
{"lineNum":"  223","line":"function test15-assert6-actual () {"},
{"lineNum":"  224","line":"\tlinebr","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  225","line":"}"},
{"lineNum":"  226","line":"function test15-assert6-expected () {"},
{"lineNum":"  227","line":"\techo -e \"N.N.N--------------------------------------------------------------------------------N.N.N--------------------------------------------------------------------------------[\'PYTHONN_PLUS\', \'TL\', \'__VERSION__\', \'__all__\', \'__builtins__\', \'__cached__\', \'__doc__\', \'__file__\', \'__loader__\', \'__name__\', \'__package__\', \'__path__\', \'__spec__\', \'__version__\', \'debug\', \'gh\', \'glue_helpers\', \'mezcla\', \'sys\', \'sys_version_info_hack\', \'system\', \'tpo_common\']--------------------------------------------------------------------------------\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  228","line":"}"},
{"lineNum":"  229","line":""},
{"lineNum":"  230","line":"test_test16() { bats_test_begin \"test16\";"},
{"lineNum":"  231","line":"\ttest_folder=$(echo /tmp/test16-$$)","class":"lineCov","hits":"4","order":"652","possible_hits":"0",},
{"lineNum":"  232","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"653","possible_hits":"0",},
{"lineNum":"  233","line":""},
{"lineNum":"  234","line":"\tpwd","class":"lineCov","hits":"2","order":"654","possible_hits":"0",},
{"lineNum":"  235","line":"}"},
{"lineNum":"  236","line":""},
{"lineNum":"  237","line":""},
{"lineNum":"  238","line":"test_test17() { bats_test_begin \"test17\";"},
{"lineNum":"  239","line":"\ttest_folder=$(echo /tmp/test17-$$)","class":"lineCov","hits":"4","order":"655","possible_hits":"0",},
{"lineNum":"  240","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"656","possible_hits":"0",},
{"lineNum":"  241","line":""},
{"lineNum":"  242","line":"\tactual=$(test17-assert1-actual)","class":"lineCov","hits":"7","order":"657","possible_hits":"0",},
{"lineNum":"  243","line":"\texpected=$(test17-assert1-expected)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  244","line":"\techo \"========== actual ==========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  245","line":"\techo \"$actual\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  246","line":"\techo \"========= expected =========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  247","line":"\techo \"$expected\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  248","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  249","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  250","line":""},
{"lineNum":"  251","line":"}"},
{"lineNum":"  252","line":""},
{"lineNum":"  253","line":"function test17-assert1-actual () {"},
{"lineNum":"  254","line":"\tltc testless.txt | testnum","class":"lineCov","hits":"6","order":"658","possible_hits":"0",},
{"lineNum":"  255","line":"}"},
{"lineNum":"  256","line":"function test17-assert1-expected () {"},
{"lineNum":"  257","line":"\techo -e \'THIS IS THE HEADNNNNNNNTHIS IS THE TAIL.\'","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  258","line":"}"},
{"lineNum":"  259","line":""},
{"lineNum":"  260","line":"test_test18() { bats_test_begin \"test18\";"},
{"lineNum":"  261","line":"\ttest_folder=$(echo /tmp/test18-$$)","class":"lineCov","hits":"4","order":"659","possible_hits":"0",},
{"lineNum":"  262","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"660","possible_hits":"0",},
{"lineNum":"  263","line":""},
{"lineNum":"  264","line":"\tactual=$(test18-assert1-actual)","class":"lineCov","hits":"7","order":"661","possible_hits":"0",},
{"lineNum":"  265","line":"\texpected=$(test18-assert1-expected)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  266","line":"\techo \"========== actual ==========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  267","line":"\techo \"$actual\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  268","line":"\techo \"========= expected =========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  269","line":"\techo \"$expected\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  270","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  271","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  272","line":""},
{"lineNum":"  273","line":"}"},
{"lineNum":"  274","line":""},
{"lineNum":"  275","line":"function test18-assert1-actual () {"},
{"lineNum":"  276","line":"\tless-tail testless.txt | testnum","class":"lineCov","hits":"6","order":"662","possible_hits":"0",},
{"lineNum":"  277","line":"}"},
{"lineNum":"  278","line":"function test18-assert1-expected () {"},
{"lineNum":"  279","line":"\techo -e \'THIS IS THE HEADNNNNNNNTHIS IS THE TAIL.\'","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  280","line":"}"},
{"lineNum":"  281","line":""},
{"lineNum":"  282","line":"test_test19() { bats_test_begin \"test19\";"},
{"lineNum":"  283","line":"\ttest_folder=$(echo /tmp/test19-$$)","class":"lineCov","hits":"4","order":"663","possible_hits":"0",},
{"lineNum":"  284","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"664","possible_hits":"0",},
{"lineNum":"  285","line":""},
{"lineNum":"  286","line":"\tactual=$(test19-assert1-actual)","class":"lineCov","hits":"7","order":"665","possible_hits":"0",},
{"lineNum":"  287","line":"\texpected=$(test19-assert1-expected)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  288","line":"\techo \"========== actual ==========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  289","line":"\techo \"$actual\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  290","line":"\techo \"========= expected =========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  291","line":"\techo \"$expected\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  292","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  293","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  294","line":""},
{"lineNum":"  295","line":"}"},
{"lineNum":"  296","line":""},
{"lineNum":"  297","line":"function test19-assert1-actual () {"},
{"lineNum":"  298","line":"\tless-tail-clipped testless.txt | testnum","class":"lineCov","hits":"6","order":"666","possible_hits":"0",},
{"lineNum":"  299","line":"}"},
{"lineNum":"  300","line":"function test19-assert1-expected () {"},
{"lineNum":"  301","line":"\techo -e \'THIS IS THE HEADNNNNNNNTHIS IS THE TAIL.\'","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  302","line":"}"},
{"lineNum":"  303","line":""},
{"lineNum":"  304","line":"test_test20() { bats_test_begin \"test20\";"},
{"lineNum":"  305","line":"\ttest_folder=$(echo /tmp/test20-$$)","class":"lineCov","hits":"4","order":"667","possible_hits":"0",},
{"lineNum":"  306","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"668","possible_hits":"0",},
{"lineNum":"  307","line":""},
{"lineNum":"  308","line":"\tactual=$(test20-assert1-actual)","class":"lineCov","hits":"7","order":"669","possible_hits":"0",},
{"lineNum":"  309","line":"\texpected=$(test20-assert1-expected)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  310","line":"\techo \"========== actual ==========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  311","line":"\techo \"$actual\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  312","line":"\techo \"========= expected =========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  313","line":"\techo \"$expected\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  314","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  315","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  316","line":""},
{"lineNum":"  317","line":"}"},
{"lineNum":"  318","line":""},
{"lineNum":"  319","line":"function test20-assert1-actual () {"},
{"lineNum":"  320","line":"\tless-clipped testless.txt | testnum","class":"lineCov","hits":"6","order":"670","possible_hits":"0",},
{"lineNum":"  321","line":"}"},
{"lineNum":"  322","line":"function test20-assert1-expected () {"},
{"lineNum":"  323","line":"\techo -e \'THIS IS THE HEADNNNNNNNTHIS IS THE TAIL.\'","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  324","line":"}"},
{"lineNum":"  325","line":""},
{"lineNum":"  326","line":"test_test21() { bats_test_begin \"test21\";"},
{"lineNum":"  327","line":"\ttest_folder=$(echo /tmp/test21-$$)","class":"lineCov","hits":"4","order":"671","possible_hits":"0",},
{"lineNum":"  328","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"672","possible_hits":"0",},
{"lineNum":"  329","line":""},
{"lineNum":"  330","line":"\tactual=$(test21-assert1-actual)","class":"lineCov","hits":"7","order":"673","possible_hits":"0",},
{"lineNum":"  331","line":"\texpected=$(test21-assert1-expected)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  332","line":"\techo \"========== actual ==========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  333","line":"\techo \"$actual\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  334","line":"\techo \"========= expected =========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  335","line":"\techo \"$expected\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  336","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  337","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  338","line":""},
{"lineNum":"  339","line":"}"},
{"lineNum":"  340","line":""},
{"lineNum":"  341","line":"function test21-assert1-actual () {"},
{"lineNum":"  342","line":"\tless- testless.txt | testnum","class":"lineCov","hits":"6","order":"674","possible_hits":"0",},
{"lineNum":"  343","line":"}"},
{"lineNum":"  344","line":"function test21-assert1-expected () {"},
{"lineNum":"  345","line":"\techo -e \'THIS IS THE HEADNNNNNNNTHIS IS THE TAIL.\'","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  346","line":"}"},
{"lineNum":"  347","line":""},
{"lineNum":"  348","line":"test_test22() { bats_test_begin \"test22\";"},
{"lineNum":"  349","line":"\ttest_folder=$(echo /tmp/test22-$$)","class":"lineCov","hits":"4","order":"675","possible_hits":"0",},
{"lineNum":"  350","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"676","possible_hits":"0",},
{"lineNum":"  351","line":""},
{"lineNum":"  352","line":"\tipython --version | testuser | testnum","class":"lineCov","hits":"8","order":"677","possible_hits":"0",},
{"lineNum":"  353","line":"}"},
{"lineNum":"  354","line":""},
{"lineNum":"  355","line":""},
{"lineNum":"  356","line":"test_test23() { bats_test_begin \"test23\";"},
{"lineNum":"  357","line":"\ttest_folder=$(echo /tmp/test23-$$)","class":"lineCov","hits":"4","order":"678","possible_hits":"0",},
{"lineNum":"  358","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"679","possible_hits":"0",},
{"lineNum":"  359","line":""},
{"lineNum":"  360","line":"\talias which-py3=\'which python3\'","class":"lineCov","hits":"2","order":"680","possible_hits":"0",},
{"lineNum":"  361","line":"}"},
{"lineNum":"  362","line":""},
{"lineNum":"  363","line":""},
{"lineNum":"  364","line":"test_test24() { bats_test_begin \"test24\";"},
{"lineNum":"  365","line":"\ttest_folder=$(echo /tmp/test24-$$)","class":"lineCov","hits":"4","order":"681","possible_hits":"0",},
{"lineNum":"  366","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"682","possible_hits":"0",},
{"lineNum":"  367","line":""},
{"lineNum":"  368","line":"\trm -rf ./* > /dev/null","class":"lineCov","hits":"2","order":"683","possible_hits":"0",},
{"lineNum":"  369","line":"\tprintf \"print(\'THIS IS A TEST\')\" > atest.py","class":"lineCov","hits":"2","order":"684","possible_hits":"0",},
{"lineNum":"  370","line":"\tprintf \"print(\'THIS IS A TEST\')\" > xyz.py","class":"lineCov","hits":"2","order":"685","possible_hits":"0",},
{"lineNum":"  371","line":"\tactual=$(test24-assert4-actual)","class":"lineCov","hits":"4","order":"686","possible_hits":"0",},
{"lineNum":"  372","line":"\texpected=$(test24-assert4-expected)","class":"lineCov","hits":"4","order":"688","possible_hits":"0",},
{"lineNum":"  373","line":"\techo \"========== actual ==========\"","class":"lineCov","hits":"2","order":"690","possible_hits":"0",},
{"lineNum":"  374","line":"\techo \"$actual\" | hexview.perl","class":"lineCov","hits":"4","order":"691","possible_hits":"0",},
{"lineNum":"  375","line":"\techo \"========= expected =========\"","class":"lineCov","hits":"2","order":"692","possible_hits":"0",},
{"lineNum":"  376","line":"\techo \"$expected\" | hexview.perl","class":"lineCov","hits":"4","order":"693","possible_hits":"0",},
{"lineNum":"  377","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"694","possible_hits":"0",},
{"lineNum":"  378","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineCov","hits":"4","order":"695","possible_hits":"0",},
{"lineNum":"  379","line":""},
{"lineNum":"  380","line":"}"},
{"lineNum":"  381","line":""},
{"lineNum":"  382","line":"function test24-assert4-actual () {"},
{"lineNum":"  383","line":"\tpy-diff atest.py xyz.py | testuser | testnum | awk \'!($6=\"\")\'","class":"lineCov","hits":"8","order":"687","possible_hits":"0",},
{"lineNum":"  384","line":"}"},
{"lineNum":"  385","line":"function test24-assert4-expected () {"},
{"lineNum":"  386","line":"\techo -e \"Assuming implicit --no-glob, as otherwise  would be in extensionabcN.py vs. atest.py   Differences: abcN.py atest.py   -rw-rw-r-- N userxfNNN userxfNNN NN  N NN:NN abcN.py-rw-rw-r-- N userxfNNN userxfNNN NN  N NN:NN atest.pyNcN     < print(\'THIS IS A TESTNN\') \\\\ No newline at end  file---     > print(\'THIS IS A TEST\') \\\\ No newline at end  file------------------------------------------------------------------------     \"","class":"lineCov","hits":"2","order":"689","possible_hits":"0",},
{"lineNum":"  387","line":"}"},
{"lineNum":"  388","line":""},
{"lineNum":"  389","line":"test_test25() { bats_test_begin \"test25\";"},
{"lineNum":"  390","line":"\ttest_folder=$(echo /tmp/test25-$$)","class":"lineCov","hits":"4","order":"696","possible_hits":"0",},
{"lineNum":"  391","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"697","possible_hits":"0",},
{"lineNum":"  392","line":""},
{"lineNum":"  393","line":"}"},
{"lineNum":"  394","line":""},
{"lineNum":"  395","line":""},
{"lineNum":"  396","line":"test_test26() { bats_test_begin \"test26\";"},
{"lineNum":"  397","line":"\ttest_folder=$(echo /tmp/test26-$$)","class":"lineCov","hits":"4","order":"698","possible_hits":"0",},
{"lineNum":"  398","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"699","possible_hits":"0",},
{"lineNum":"  399","line":""},
{"lineNum":"  400","line":"\tprintf \"print(\'THIS IS A TEST10\')\\nprint(\'THIS IS A TEST11\')\\nprint(\'THIS IS A TEST12\')\\nprint(\'THIS IS A TEST13\')\" > random_line_test.py","class":"lineCov","hits":"2","order":"700","possible_hits":"0",},
{"lineNum":"  401","line":"}"},
{"lineNum":"  402","line":""},
{"lineNum":"  403","line":""},
{"lineNum":"  404","line":"test_test27() { bats_test_begin \"test27\";"},
{"lineNum":"  405","line":"\ttest_folder=$(echo /tmp/test27-$$)","class":"lineCov","hits":"4","order":"701","possible_hits":"0",},
{"lineNum":"  406","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"702","possible_hits":"0",},
{"lineNum":"  407","line":""},
{"lineNum":"  408","line":"\tactual=$(test27-assert1-actual)","class":"lineCov","hits":"7","order":"703","possible_hits":"0",},
{"lineNum":"  409","line":"\texpected=$(test27-assert1-expected)","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  410","line":"\techo \"========== actual ==========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  411","line":"\techo \"$actual\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  412","line":"\techo \"========= expected =========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  413","line":"\techo \"$expected\" | hexview.perl","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  414","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  415","line":"\t[ \"$actual\" == \"$expected\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  416","line":""},
{"lineNum":"  417","line":"}"},
{"lineNum":"  418","line":""},
{"lineNum":"  419","line":"function test27-assert1-actual () {"},
{"lineNum":"  420","line":"\trandomize-datafile random_line_test.py","class":"lineCov","hits":"4","order":"704","possible_hits":"0",},
{"lineNum":"  421","line":"}"},
{"lineNum":"  422","line":"function test27-assert1-expected () {"},
{"lineNum":"  423","line":"\techo -e \"print(\'THIS IS A TEST10\')print(\'THIS IS A TEST10\')print(\'THIS IS A TEST11\')print(\'THIS IS A TEST12\')/usr/bin/python: No module named randomize_lines\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  424","line":"}"},
{"lineNum":"  425","line":""},
{"lineNum":"  426","line":"test_test28() { bats_test_begin \"test28\";"},
{"lineNum":"  427","line":"\ttest_folder=$(echo /tmp/test28-$$)","class":"lineCov","hits":"4","order":"705","possible_hits":"0",},
{"lineNum":"  428","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"706","possible_hits":"0",},
{"lineNum":"  429","line":""},
{"lineNum":"  430","line":"\tconditional-source $BIN_DIR/tests/_dir-aliases.bash","class":"lineCov","hits":"4","order":"707","possible_hits":"0",},
{"lineNum":"  431","line":"\ttouch file1","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  432","line":"\tln-symbolic file1 link1","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  433","line":"\tlinebr","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  434","line":"}"},
{"lineNum":"  435","line":""},
{"lineNum":"  436","line":""},
{"lineNum":"  437","line":"test_test29() { bats_test_begin \"test29\";"},
{"lineNum":"  438","line":"\ttest_folder=$(echo /tmp/test29-$$)","class":"lineCov","hits":"4","order":"708","possible_hits":"0",},
{"lineNum":"  439","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"709","possible_hits":"0",},
{"lineNum":"  440","line":""},
{"lineNum":"  441","line":"\tcurl-dump https://www.example.com/","class":"lineCov","hits":"4","order":"710","possible_hits":"0",},
{"lineNum":"  442","line":"\tlinebr","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  443","line":"\tls -l | testnum | testuser | awk \'!($6=\"\")\'","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  444","line":"\tlinebr","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  445","line":"}"},
{"lineNum":"  446","line":""},
{"lineNum":"  447","line":""},
{"lineNum":"  448","line":"test_test30() { bats_test_begin \"test30\";"},
{"lineNum":"  449","line":"\ttest_folder=$(echo /tmp/test30-$$)","class":"lineCov","hits":"4","order":"711","possible_hits":"0",},
{"lineNum":"  450","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"712","possible_hits":"0",},
{"lineNum":"  451","line":""},
{"lineNum":"  452","line":"\tpwd |  sed -r \"s/\"$USER\"+/user/g\"","class":"lineCov","hits":"4","order":"713","possible_hits":"0",},
{"lineNum":"  453","line":"}"},
{"lineNum":"  454","line":""},
{"lineNum":"  455","line":"bats_test_function --tags \'\' test_test0","class":"lineCov","hits":"33","order":"350","possible_hits":"0",},
{"lineNum":"  456","line":"bats_test_function --tags \'\' test_test1","class":"lineCov","hits":"33","order":"351","possible_hits":"0",},
{"lineNum":"  457","line":"bats_test_function --tags \'\' test_test2","class":"lineCov","hits":"33","order":"352","possible_hits":"0",},
{"lineNum":"  458","line":"bats_test_function --tags \'\' test_test3","class":"lineCov","hits":"33","order":"353","possible_hits":"0",},
{"lineNum":"  459","line":"bats_test_function --tags \'\' test_test4","class":"lineCov","hits":"33","order":"354","possible_hits":"0",},
{"lineNum":"  460","line":"bats_test_function --tags \'\' test_test5","class":"lineCov","hits":"33","order":"355","possible_hits":"0",},
{"lineNum":"  461","line":"bats_test_function --tags \'\' test_test6","class":"lineCov","hits":"33","order":"356","possible_hits":"0",},
{"lineNum":"  462","line":"bats_test_function --tags \'\' test_test7","class":"lineCov","hits":"33","order":"357","possible_hits":"0",},
{"lineNum":"  463","line":"bats_test_function --tags \'\' test_test8","class":"lineCov","hits":"33","order":"358","possible_hits":"0",},
{"lineNum":"  464","line":"bats_test_function --tags \'\' test_test9","class":"lineCov","hits":"33","order":"359","possible_hits":"0",},
{"lineNum":"  465","line":"bats_test_function --tags \'\' test_test10","class":"lineCov","hits":"33","order":"360","possible_hits":"0",},
{"lineNum":"  466","line":"bats_test_function --tags \'\' test_test11","class":"lineCov","hits":"33","order":"361","possible_hits":"0",},
{"lineNum":"  467","line":"bats_test_function --tags \'\' test_test12","class":"lineCov","hits":"33","order":"362","possible_hits":"0",},
{"lineNum":"  468","line":"bats_test_function --tags \'\' test_test13","class":"lineCov","hits":"33","order":"363","possible_hits":"0",},
{"lineNum":"  469","line":"bats_test_function --tags \'\' test_test14","class":"lineCov","hits":"33","order":"364","possible_hits":"0",},
{"lineNum":"  470","line":"bats_test_function --tags \'\' test_test15","class":"lineCov","hits":"33","order":"365","possible_hits":"0",},
{"lineNum":"  471","line":"bats_test_function --tags \'\' test_test16","class":"lineCov","hits":"33","order":"366","possible_hits":"0",},
{"lineNum":"  472","line":"bats_test_function --tags \'\' test_test17","class":"lineCov","hits":"33","order":"367","possible_hits":"0",},
{"lineNum":"  473","line":"bats_test_function --tags \'\' test_test18","class":"lineCov","hits":"33","order":"368","possible_hits":"0",},
{"lineNum":"  474","line":"bats_test_function --tags \'\' test_test19","class":"lineCov","hits":"33","order":"369","possible_hits":"0",},
{"lineNum":"  475","line":"bats_test_function --tags \'\' test_test20","class":"lineCov","hits":"33","order":"370","possible_hits":"0",},
{"lineNum":"  476","line":"bats_test_function --tags \'\' test_test21","class":"lineCov","hits":"33","order":"371","possible_hits":"0",},
{"lineNum":"  477","line":"bats_test_function --tags \'\' test_test22","class":"lineCov","hits":"33","order":"372","possible_hits":"0",},
{"lineNum":"  478","line":"bats_test_function --tags \'\' test_test23","class":"lineCov","hits":"33","order":"373","possible_hits":"0",},
{"lineNum":"  479","line":"bats_test_function --tags \'\' test_test24","class":"lineCov","hits":"33","order":"374","possible_hits":"0",},
{"lineNum":"  480","line":"bats_test_function --tags \'\' test_test25","class":"lineCov","hits":"33","order":"375","possible_hits":"0",},
{"lineNum":"  481","line":"bats_test_function --tags \'\' test_test26","class":"lineCov","hits":"33","order":"376","possible_hits":"0",},
{"lineNum":"  482","line":"bats_test_function --tags \'\' test_test27","class":"lineCov","hits":"33","order":"377","possible_hits":"0",},
{"lineNum":"  483","line":"bats_test_function --tags \'\' test_test28","class":"lineCov","hits":"33","order":"378","possible_hits":"0",},
{"lineNum":"  484","line":"bats_test_function --tags \'\' test_test29","class":"lineCov","hits":"33","order":"379","possible_hits":"0",},
{"lineNum":"  485","line":"bats_test_function --tags \'\' test_test30","class":"lineCov","hits":"33","order":"380","possible_hits":"0",},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "bats", "date" : "2023-05-04 19:40:24", "instrumented" : 258, "covered" : 160,};
var merged_data = [];
