var data = {lines:[
{"lineNum":"    1","line":"#!/usr/bin/env bats"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":""},
{"lineNum":"    4","line":"# Make executables ./tests/../ visible to PATH"},
{"lineNum":"    5","line":"PATH=\"/home/aveey/tom-project/shell-scripts/tests/batspp-only/../:$PATH\"","class":"lineCov","hits":"11","order":"333","possible_hits":"0",},
{"lineNum":"    6","line":""},
{"lineNum":"    7","line":"# Source files"},
{"lineNum":"    8","line":"shopt -s expand_aliases","class":"lineCov","hits":"11","order":"349","possible_hits":"0",},
{"lineNum":"    9","line":""},
{"lineNum":"   10","line":""},
{"lineNum":"   11","line":"test_test0() { bats_test_begin \"test0\";"},
{"lineNum":"   12","line":"\ttest_folder=$(echo /tmp/test0-$$)","class":"lineCov","hits":"4","order":"434","possible_hits":"0",},
{"lineNum":"   13","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"435","possible_hits":"0",},
{"lineNum":"   14","line":""},
{"lineNum":"   15","line":"\tshopt -s expand_aliases","class":"lineCov","hits":"2","order":"436","possible_hits":"0",},
{"lineNum":"   16","line":"}"},
{"lineNum":"   17","line":""},
{"lineNum":"   18","line":""},
{"lineNum":"   19","line":"test_test1() { bats_test_begin \"test1\";"},
{"lineNum":"   20","line":"\ttest_folder=$(echo /tmp/test1-$$)","class":"lineCov","hits":"4","order":"475","possible_hits":"0",},
{"lineNum":"   21","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"476","possible_hits":"0",},
{"lineNum":"   22","line":""},
{"lineNum":"   23","line":"\talias testuser=\"sed -r \"s/\"$USER\"+/userxf333/g\"\"","class":"lineCov","hits":"2","order":"477","possible_hits":"0",},
{"lineNum":"   24","line":"\talias testnum=\"sed -r \"s/[0-9]/N/g\"\"","class":"lineCov","hits":"2","order":"478","possible_hits":"0",},
{"lineNum":"   25","line":"}"},
{"lineNum":"   26","line":""},
{"lineNum":"   27","line":""},
{"lineNum":"   28","line":"test_test2() { bats_test_begin \"test2\";"},
{"lineNum":"   29","line":"\ttest_folder=$(echo /tmp/test2-$$)","class":"lineCov","hits":"4","order":"479","possible_hits":"0",},
{"lineNum":"   30","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"480","possible_hits":"0",},
{"lineNum":"   31","line":""},
{"lineNum":"   32","line":"\techo \"Hi Mom!\"","class":"lineCov","hits":"2","order":"481","possible_hits":"0",},
{"lineNum":"   33","line":"}"},
{"lineNum":"   34","line":""},
{"lineNum":"   35","line":""},
{"lineNum":"   36","line":"test_test3() { bats_test_begin \"test3\";"},
{"lineNum":"   37","line":"\ttest_folder=$(echo /tmp/test3-$$)","class":"lineCov","hits":"4","order":"482","possible_hits":"0",},
{"lineNum":"   38","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"483","possible_hits":"0",},
{"lineNum":"   39","line":""},
{"lineNum":"   40","line":"\techo \'Hello world\' | wc -l","class":"lineCov","hits":"4","order":"484","possible_hits":"0",},
{"lineNum":"   41","line":"}"},
{"lineNum":"   42","line":""},
{"lineNum":"   43","line":""},
{"lineNum":"   44","line":"test_test4() { bats_test_begin \"test4\";"},
{"lineNum":"   45","line":"\ttest_folder=$(echo /tmp/test4-$$)","class":"lineCov","hits":"4","order":"485","possible_hits":"0",},
{"lineNum":"   46","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"486","possible_hits":"0",},
{"lineNum":"   47","line":""},
{"lineNum":"   48","line":"\tpwd | testuser","class":"lineCov","hits":"6","order":"487","possible_hits":"0",},
{"lineNum":"   49","line":"}"},
{"lineNum":"   50","line":""},
{"lineNum":"   51","line":""},
{"lineNum":"   52","line":"test_test5() { bats_test_begin \"test5\";"},
{"lineNum":"   53","line":"\ttest_folder=$(echo /tmp/test5-$$)","class":"lineCov","hits":"4","order":"579","possible_hits":"0",},
{"lineNum":"   54","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"580","possible_hits":"0",},
{"lineNum":"   55","line":""},
{"lineNum":"   56","line":"\twhich systemd","class":"lineCov","hits":"2","order":"581","possible_hits":"0",},
{"lineNum":"   57","line":"}"},
{"lineNum":"   58","line":""},
{"lineNum":"   59","line":""},
{"lineNum":"   60","line":"test_test6() { bats_test_begin \"test6\";"},
{"lineNum":"   61","line":"\ttest_folder=$(echo /tmp/test6-$$)","class":"lineCov","hits":"4","order":"582","possible_hits":"0",},
{"lineNum":"   62","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"583","possible_hits":"0",},
{"lineNum":"   63","line":""},
{"lineNum":"   64","line":"\tman date | head -n 10 | testnum","class":"lineCov","hits":"8","order":"584","possible_hits":"0",},
{"lineNum":"   65","line":"}"},
{"lineNum":"   66","line":""},
{"lineNum":"   67","line":""},
{"lineNum":"   68","line":"test_test7() { bats_test_begin \"test7\";"},
{"lineNum":"   69","line":"\ttest_folder=$(echo /tmp/test7-$$)","class":"lineCov","hits":"4","order":"585","possible_hits":"0",},
{"lineNum":"   70","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"586","possible_hits":"0",},
{"lineNum":"   71","line":""},
{"lineNum":"   72","line":"\tps -l | awk \'!($3=$4=$5=$10=$13=\"\")\' | testnum","class":"lineCov","hits":"8","order":"587","possible_hits":"0",},
{"lineNum":"   73","line":"}"},
{"lineNum":"   74","line":""},
{"lineNum":"   75","line":""},
{"lineNum":"   76","line":"test_test8() { bats_test_begin \"test8\";"},
{"lineNum":"   77","line":"\ttest_folder=$(echo /tmp/test8-$$)","class":"lineCov","hits":"4","order":"588","possible_hits":"0",},
{"lineNum":"   78","line":"\tmkdir $test_folder && cd $test_folder","class":"lineCov","hits":"4","order":"589","possible_hits":"0",},
{"lineNum":"   79","line":""},
{"lineNum":"   80","line":"\tps | head -n 10 | testuser | testnum","class":"lineCov","hits":"10","order":"590","possible_hits":"0",},
{"lineNum":"   81","line":"}"},
{"lineNum":"   82","line":""},
{"lineNum":"   83","line":"bats_test_function --tags \'\' test_test0","class":"lineCov","hits":"11","order":"350","possible_hits":"0",},
{"lineNum":"   84","line":"bats_test_function --tags \'\' test_test1","class":"lineCov","hits":"11","order":"351","possible_hits":"0",},
{"lineNum":"   85","line":"bats_test_function --tags \'\' test_test2","class":"lineCov","hits":"11","order":"352","possible_hits":"0",},
{"lineNum":"   86","line":"bats_test_function --tags \'\' test_test3","class":"lineCov","hits":"11","order":"353","possible_hits":"0",},
{"lineNum":"   87","line":"bats_test_function --tags \'\' test_test4","class":"lineCov","hits":"11","order":"354","possible_hits":"0",},
{"lineNum":"   88","line":"bats_test_function --tags \'\' test_test5","class":"lineCov","hits":"11","order":"355","possible_hits":"0",},
{"lineNum":"   89","line":"bats_test_function --tags \'\' test_test6","class":"lineCov","hits":"11","order":"356","possible_hits":"0",},
{"lineNum":"   90","line":"bats_test_function --tags \'\' test_test7","class":"lineCov","hits":"11","order":"357","possible_hits":"0",},
{"lineNum":"   91","line":"bats_test_function --tags \'\' test_test8","class":"lineCov","hits":"11","order":"358","possible_hits":"0",},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "bats", "date" : "2023-05-04 19:40:25", "instrumented" : 39, "covered" : 39,};
var merged_data = [];
