#! /usr/bin/env bash
#
# evaluates command on command line as with /usr/bin/command under MacOs [BSD?]
#
# Note: this is intended to provide an executable target (i.e., non shell built-in)
# for use with aliases such as diff-default, so that usable with executables like time.
#

# Uncomment following line(s) for tracing:
# - xtrace shows arg expansion (and often is sufficient)
# - verbose shows source commands as is (but usually is superfluous w/ xtrace)
#  
## echo "$@"
## set -o xtrace
## DEBUG: set -o verbose

if [ "$1" == "--trace" ]; then
    shift
    echo "$@"
    set -o verbose
fi

"$@"
