var data = {lines:[
{"lineNum":"    1","line":"#!/usr/bin/env bats"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":""},
{"lineNum":"    4","line":"# Make executables ./tests/../ visible to PATH"},
{"lineNum":"    5","line":"PATH=\"/home/aveey/tom-project/shell-scripts/tests/batspp-only/../:$PATH\"","class":"lineCov","hits":"12","order":"333","possible_hits":"0",},
{"lineNum":"    6","line":""},
{"lineNum":"    7","line":"# Enable aliases"},
{"lineNum":"    8","line":"shopt -s expand_aliases","class":"lineCov","hits":"12","order":"349","possible_hits":"0",},
{"lineNum":"    9","line":""},
{"lineNum":"   10","line":""},
{"lineNum":"   11","line":""},
{"lineNum":"   12","line":"test_test-2d1() { bats_test_begin \"test-1\";"},
{"lineNum":"   13","line":"\ttestfolder=\"/tmp/batspp-201680/test-1\"","class":"lineCov","hits":"2","order":"435","possible_hits":"0",},
{"lineNum":"   14","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"436","possible_hits":"0",},
{"lineNum":"   15","line":"\tbuiltin cd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"437","possible_hits":"0",},
{"lineNum":"   16","line":""},
{"lineNum":"   17","line":"\techo \"==========\" $\"bind \'set enable-bracketed-paste off\'\\n\" \"==========\"","class":"lineCov","hits":"2","order":"438","possible_hits":"0",},
{"lineNum":"   18","line":"\ttest-1-actual","class":"lineCov","hits":"2","order":"439","possible_hits":"0",},
{"lineNum":"   19","line":"\techo \"=========\" $\"$ unalias -a\\n$ for f in $(typeset -f | egrep \'^\\\\w+\'); do unset -f $f; done\\n$ BIN_DIR=$PWD/..\" \"=========\"","class":"lineCov","hits":"8","order":"442","possible_hits":"0",},
{"lineNum":"   20","line":"\ttest-1-expected","class":"lineCov","hits":"2","order":"451","possible_hits":"0",},
{"lineNum":"   21","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"454","possible_hits":"0",},
{"lineNum":"   22","line":"\t# ???: \"bind \'set enable-bracketed-paste off\'\\n\"=$(test-1-actual)"},
{"lineNum":"   23","line":"\t# ???: \"$ unalias -a\\n$ for f in $(typeset -f | egrep \'^\\\\w+\'); do unset -f $f; done\\n$ BIN_DIR=$PWD/..\"=$(test-1-expected)"},
{"lineNum":"   24","line":"\t[ \"$(test-1-actual)\" == \"$(test-1-expected)\" ]","class":"lineCov","hits":"8","order":"455","possible_hits":"0",},
{"lineNum":"   25","line":"}"},
{"lineNum":"   26","line":""},
{"lineNum":"   27","line":"function test-1-actual () {"},
{"lineNum":"   28","line":"\t# no-op in case content just a comment"},
{"lineNum":"   29","line":"\ttrue","class":"lineCov","hits":"4","order":"440","possible_hits":"0",},
{"lineNum":"   30","line":""},
{"lineNum":"   31","line":"\tbind \'set enable-bracketed-paste off\'","class":"lineCov","hits":"4","order":"441","possible_hits":"0",},
{"lineNum":"   32","line":""},
{"lineNum":"   33","line":"}"},
{"lineNum":"   34","line":""},
{"lineNum":"   35","line":"function test-1-expected () {"},
{"lineNum":"   36","line":"\t# no-op in case content just a comment"},
{"lineNum":"   37","line":"\ttrue","class":"lineCov","hits":"4","order":"452","possible_hits":"0",},
{"lineNum":"   38","line":""},
{"lineNum":"   39","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"12","order":"453","possible_hits":"0",},
{"lineNum":"   40","line":"$ unalias -a"},
{"lineNum":"   41","line":"$ for f in $(typeset -f | egrep \'^\\w+\'); do unset -f $f; done"},
{"lineNum":"   42","line":"$ BIN_DIR=$PWD/.."},
{"lineNum":"   43","line":"END_EXPECTED"},
{"lineNum":"   44","line":"}"},
{"lineNum":"   45","line":""},
{"lineNum":"   46","line":""},
{"lineNum":"   47","line":"test_test-2d3() { bats_test_begin \"test-3\";"},
{"lineNum":"   48","line":"\ttestfolder=\"/tmp/batspp-201680/test-3\"","class":"lineCov","hits":"2","order":"570","possible_hits":"0",},
{"lineNum":"   49","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"571","possible_hits":"0",},
{"lineNum":"   50","line":"\tbuiltin cd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"572","possible_hits":"0",},
{"lineNum":"   51","line":""},
{"lineNum":"   52","line":"\techo \"==========\" $\"# $ echo \'Hii\'\\n\" \"==========\"","class":"lineCov","hits":"2","order":"573","possible_hits":"0",},
{"lineNum":"   53","line":"\ttest-3-actual","class":"lineCov","hits":"2","order":"574","possible_hits":"0",},
{"lineNum":"   54","line":"\techo \"=========\" $\'# | Hi?2004l\' \"=========\"","class":"lineCov","hits":"2","order":"576","possible_hits":"0",},
{"lineNum":"   55","line":"\ttest-3-expected","class":"lineCov","hits":"2","order":"577","possible_hits":"0",},
{"lineNum":"   56","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"580","possible_hits":"0",},
{"lineNum":"   57","line":"\t# ???: \"# $ echo \'Hii\'\\n\"=$(test-3-actual)"},
{"lineNum":"   58","line":"\t# ???: \'# | Hi?2004l\'=$(test-3-expected)"},
{"lineNum":"   59","line":"\t[ \"$(test-3-actual)\" == \"$(test-3-expected)\" ]","class":"lineCov","hits":"8","order":"581","possible_hits":"0",},
{"lineNum":"   60","line":"}"},
{"lineNum":"   61","line":""},
{"lineNum":"   62","line":"function test-3-actual () {"},
{"lineNum":"   63","line":"\t# no-op in case content just a comment"},
{"lineNum":"   64","line":"\ttrue","class":"lineCov","hits":"4","order":"575","possible_hits":"0",},
{"lineNum":"   65","line":""},
{"lineNum":"   66","line":""},
{"lineNum":"   67","line":"}"},
{"lineNum":"   68","line":""},
{"lineNum":"   69","line":"function test-3-expected () {"},
{"lineNum":"   70","line":"\t# no-op in case content just a comment"},
{"lineNum":"   71","line":"\ttrue","class":"lineCov","hits":"4","order":"578","possible_hits":"0",},
{"lineNum":"   72","line":""},
{"lineNum":"   73","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"4","order":"579","possible_hits":"0",},
{"lineNum":"   74","line":"# | Hi?2004l"},
{"lineNum":"   75","line":"END_EXPECTED"},
{"lineNum":"   76","line":"}"},
{"lineNum":"   77","line":""},
{"lineNum":"   78","line":""},
{"lineNum":"   79","line":"test_test-2d4() { bats_test_begin \"test-4\";"},
{"lineNum":"   80","line":"\ttestfolder=\"/tmp/batspp-201680/test-4\"","class":"lineCov","hits":"2","order":"582","possible_hits":"0",},
{"lineNum":"   81","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"583","possible_hits":"0",},
{"lineNum":"   82","line":"\tbuiltin cd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"584","possible_hits":"0",},
{"lineNum":"   83","line":""},
{"lineNum":"   84","line":"\techo \"==========\" $\'calc_entropy=calc_entropy.perl\\n\' \"==========\"","class":"lineCov","hits":"2","order":"585","possible_hits":"0",},
{"lineNum":"   85","line":"\ttest-4-actual","class":"lineCov","hits":"2","order":"586","possible_hits":"0",},
{"lineNum":"   86","line":"\techo \"=========\" $\'$ simple=\"-simple\"\\n$ verbose=\"-verbose\"\\n# -or-: calc_entropy=\"calc_entropy.py\"; simple=\"--simple\"; verbose=\"--verbose\"\\n# Convenience alias to use <NL> for entirely blank lines (i.e., no spaces)\\n$ alias encode-blank-line=\\\'perl -pe \"s/^$/<NL>/;\"\\\'\' \"=========\"","class":"lineCov","hits":"2","order":"589","possible_hits":"0",},
{"lineNum":"   87","line":"\ttest-4-expected","class":"lineCov","hits":"2","order":"590","possible_hits":"0",},
{"lineNum":"   88","line":"\techo \"============================\"","class":"lineCov","hits":"2","order":"593","possible_hits":"0",},
{"lineNum":"   89","line":"\t# ???: \'calc_entropy=calc_entropy.perl\\n\'=$(test-4-actual)"},
{"lineNum":"   90","line":"\t# ???: \'$ simple=\"-simple\"\\n$ verbose=\"-verbose\"\\n# -or-: calc_entropy=\"calc_entropy.py\"; simple=\"--simple\"; verbose=\"--verbose\"\\n# Convenience alias to use <NL> for entirely blank lines (i.e., no spaces)\\n$ alias encode-blank-line=\\\'perl -pe \"s/^$/<NL>/;\"\\\'\'=$(test-4-expected)"},
{"lineNum":"   91","line":"\t[ \"$(test-4-actual)\" == \"$(test-4-expected)\" ]","class":"lineCov","hits":"8","order":"594","possible_hits":"0",},
{"lineNum":"   92","line":"}"},
{"lineNum":"   93","line":""},
{"lineNum":"   94","line":"function test-4-actual () {"},
{"lineNum":"   95","line":"\t# no-op in case content just a comment"},
{"lineNum":"   96","line":"\ttrue","class":"lineCov","hits":"4","order":"587","possible_hits":"0",},
{"lineNum":"   97","line":""},
{"lineNum":"   98","line":"\tcalc_entropy=calc_entropy.perl","class":"lineCov","hits":"4","order":"588","possible_hits":"0",},
{"lineNum":"   99","line":""},
{"lineNum":"  100","line":"}"},
{"lineNum":"  101","line":""},
{"lineNum":"  102","line":"function test-4-expected () {"},
{"lineNum":"  103","line":"\t# no-op in case content just a comment"},
{"lineNum":"  104","line":"\ttrue","class":"lineCov","hits":"4","order":"591","possible_hits":"0",},
{"lineNum":"  105","line":""},
{"lineNum":"  106","line":"\tcat <<END_EXPECTED","class":"lineCov","hits":"4","order":"592","possible_hits":"0",},
{"lineNum":"  107","line":"$ simple=\"-simple\""},
{"lineNum":"  108","line":"$ verbose=\"-verbose\""},
{"lineNum":"  109","line":"# -or-: calc_entropy=\"calc_entropy.py\"; simple=\"--simple\"; verbose=\"--verbose\""},
{"lineNum":"  110","line":"# Convenience alias to use <NL> for entirely blank lines (i.e., no spaces)"},
{"lineNum":"  111","line":"$ alias encode-blank-line=\'perl -pe \"s/^$/<NL>/;\"\'"},
{"lineNum":"  112","line":"END_EXPECTED"},
{"lineNum":"  113","line":"}"},
{"lineNum":"  114","line":""},
{"lineNum":"  115","line":""},
{"lineNum":"  116","line":"test_test-2d5() { bats_test_begin \"test-5\";"},
{"lineNum":"  117","line":"\ttestfolder=\"/tmp/batspp-201680/test-5\"","class":"lineCov","hits":"2","order":"595","possible_hits":"0",},
{"lineNum":"  118","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"596","possible_hits":"0",},
{"lineNum":"  119","line":"\tbuiltin cd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"597","possible_hits":"0",},
{"lineNum":"  120","line":""},
{"lineNum":"  121","line":"\techo \"==========\" $\'$calc_entropy $simple .25 .25 .25 .25\\n\' \"==========\"","class":"lineCov","hits":"2","order":"598","possible_hits":"0",},
{"lineNum":"  122","line":"\ttest-5-actual","class":"lineCov","hits":"2","order":"599","possible_hits":"0",},
{"lineNum":"  123","line":"\techo \"=========\" $\'Entropy\\n2.000\' \"=========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  124","line":"\ttest-5-expected","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  125","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  126","line":"\t# ???: \'$calc_entropy $simple .25 .25 .25 .25\\n\'=$(test-5-actual)"},
{"lineNum":"  127","line":"\t# ???: \'Entropy\\n2.000\'=$(test-5-expected)"},
{"lineNum":"  128","line":"\t[ \"$(test-5-actual)\" == \"$(test-5-expected)\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  129","line":"}"},
{"lineNum":"  130","line":""},
{"lineNum":"  131","line":"function test-5-actual () {"},
{"lineNum":"  132","line":"\t# no-op in case content just a comment"},
{"lineNum":"  133","line":"\ttrue","class":"lineCov","hits":"2","order":"600","possible_hits":"0",},
{"lineNum":"  134","line":""},
{"lineNum":"  135","line":"\t$calc_entropy $simple .25 .25 .25 .25","class":"lineCov","hits":"4","order":"601","possible_hits":"0",},
{"lineNum":"  136","line":""},
{"lineNum":"  137","line":"}"},
{"lineNum":"  138","line":""},
{"lineNum":"  139","line":"function test-5-expected () {"},
{"lineNum":"  140","line":"\t# no-op in case content just a comment"},
{"lineNum":"  141","line":"\ttrue","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  142","line":""},
{"lineNum":"  143","line":"\tcat <<END_EXPECTED","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  144","line":"Entropy"},
{"lineNum":"  145","line":"2.000"},
{"lineNum":"  146","line":"END_EXPECTED"},
{"lineNum":"  147","line":"}"},
{"lineNum":"  148","line":""},
{"lineNum":"  149","line":""},
{"lineNum":"  150","line":"test_test-2d6() { bats_test_begin \"test-6\";"},
{"lineNum":"  151","line":"\ttestfolder=\"/tmp/batspp-201680/test-6\"","class":"lineCov","hits":"2","order":"609","possible_hits":"0",},
{"lineNum":"  152","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"610","possible_hits":"0",},
{"lineNum":"  153","line":"\tbuiltin cd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"611","possible_hits":"0",},
{"lineNum":"  154","line":""},
{"lineNum":"  155","line":"\techo \"==========\" $\'head calc_entropy.*input* | encode-blank-line\\n\' \"==========\"","class":"lineCov","hits":"2","order":"612","possible_hits":"0",},
{"lineNum":"  156","line":"\ttest-6-actual","class":"lineCov","hits":"2","order":"613","possible_hits":"0",},
{"lineNum":"  157","line":"\techo \"=========\" $\"==> calc_entropy.input <==\\n# Frequency of \'between\' in Penn Treebank II WSJ annotations\\n24\\tpp-clr\\n6\\tpp-dir\\n4\\tpp-ext\\n35\\tpp-loc\\n2\\tpp-nom\\n7\\tpp-prd\\n42\\tpp-tmp\\n<NL>\\n==> calc_entropy.input2 <==\\n2\\tabc\\n4\\tdef\\n1\\tghi\\n1\\tjkl\\n<NL>\\n==> calc_entropy.simple.input <==\\n.25 .25 .25 .25\\n<NL>\\n==> calc_entropy.simple.input2 <==\\n.47 .42 .06 .05\" \"=========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  158","line":"\ttest-6-expected","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  159","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  160","line":"\t# ???: \'head calc_entropy.*input* | encode-blank-line\\n\'=$(test-6-actual)"},
{"lineNum":"  161","line":"\t# ???: \"==> calc_entropy.input <==\\n# Frequency of \'between\' in Penn Treebank II WSJ annotations\\n24\\tpp-clr\\n6\\tpp-dir\\n4\\tpp-ext\\n35\\tpp-loc\\n2\\tpp-nom\\n7\\tpp-prd\\n42\\tpp-tmp\\n<NL>\\n==> calc_entropy.input2 <==\\n2\\tabc\\n4\\tdef\\n1\\tghi\\n1\\tjkl\\n<NL>\\n==> calc_entropy.simple.input <==\\n.25 .25 .25 .25\\n<NL>\\n==> calc_entropy.simple.input2 <==\\n.47 .42 .06 .05\"=$(test-6-expected)"},
{"lineNum":"  162","line":"\t[ \"$(test-6-actual)\" == \"$(test-6-expected)\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  163","line":"}"},
{"lineNum":"  164","line":""},
{"lineNum":"  165","line":"function test-6-actual () {"},
{"lineNum":"  166","line":"\t# no-op in case content just a comment"},
{"lineNum":"  167","line":"\ttrue","class":"lineCov","hits":"2","order":"614","possible_hits":"0",},
{"lineNum":"  168","line":""},
{"lineNum":"  169","line":"\thead calc_entropy.*input* | encode-blank-line","class":"lineCov","hits":"6","order":"615","possible_hits":"0",},
{"lineNum":"  170","line":""},
{"lineNum":"  171","line":"}"},
{"lineNum":"  172","line":""},
{"lineNum":"  173","line":"function test-6-expected () {"},
{"lineNum":"  174","line":"\t# no-op in case content just a comment"},
{"lineNum":"  175","line":"\ttrue","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  176","line":""},
{"lineNum":"  177","line":"\tcat <<END_EXPECTED","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  178","line":"==> calc_entropy.input <=="},
{"lineNum":"  179","line":"# Frequency of \'between\' in Penn Treebank II WSJ annotations"},
{"lineNum":"  180","line":"24\tpp-clr"},
{"lineNum":"  181","line":"6\tpp-dir"},
{"lineNum":"  182","line":"4\tpp-ext"},
{"lineNum":"  183","line":"35\tpp-loc"},
{"lineNum":"  184","line":"2\tpp-nom"},
{"lineNum":"  185","line":"7\tpp-prd"},
{"lineNum":"  186","line":"42\tpp-tmp"},
{"lineNum":"  187","line":"<NL>"},
{"lineNum":"  188","line":"==> calc_entropy.input2 <=="},
{"lineNum":"  189","line":"2\tabc"},
{"lineNum":"  190","line":"4\tdef"},
{"lineNum":"  191","line":"1\tghi"},
{"lineNum":"  192","line":"1\tjkl"},
{"lineNum":"  193","line":"<NL>"},
{"lineNum":"  194","line":"==> calc_entropy.simple.input <=="},
{"lineNum":"  195","line":".25 .25 .25 .25"},
{"lineNum":"  196","line":"<NL>"},
{"lineNum":"  197","line":"==> calc_entropy.simple.input2 <=="},
{"lineNum":"  198","line":".47 .42 .06 .05"},
{"lineNum":"  199","line":"END_EXPECTED"},
{"lineNum":"  200","line":"}"},
{"lineNum":"  201","line":""},
{"lineNum":"  202","line":""},
{"lineNum":"  203","line":"test_test-2d7() { bats_test_begin \"test-7\";"},
{"lineNum":"  204","line":"\ttestfolder=\"/tmp/batspp-201680/test-7\"","class":"lineCov","hits":"2","order":"616","possible_hits":"0",},
{"lineNum":"  205","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"617","possible_hits":"0",},
{"lineNum":"  206","line":"\tbuiltin cd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"618","possible_hits":"0",},
{"lineNum":"  207","line":""},
{"lineNum":"  208","line":"\techo \"==========\" $\'$calc_entropy $simple - < ./calc_entropy.simple.input\\n\' \"==========\"","class":"lineCov","hits":"2","order":"619","possible_hits":"0",},
{"lineNum":"  209","line":"\ttest-7-actual","class":"lineCov","hits":"2","order":"620","possible_hits":"0",},
{"lineNum":"  210","line":"\techo \"=========\" $\'Entropy\\n2.000\' \"=========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  211","line":"\ttest-7-expected","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  212","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  213","line":"\t# ???: \'$calc_entropy $simple - < ./calc_entropy.simple.input\\n\'=$(test-7-actual)"},
{"lineNum":"  214","line":"\t# ???: \'Entropy\\n2.000\'=$(test-7-expected)"},
{"lineNum":"  215","line":"\t[ \"$(test-7-actual)\" == \"$(test-7-expected)\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  216","line":"}"},
{"lineNum":"  217","line":""},
{"lineNum":"  218","line":"function test-7-actual () {"},
{"lineNum":"  219","line":"\t# no-op in case content just a comment"},
{"lineNum":"  220","line":"\ttrue","class":"lineCov","hits":"2","order":"621","possible_hits":"0",},
{"lineNum":"  221","line":""},
{"lineNum":"  222","line":"\t$calc_entropy $simple - < ./calc_entropy.simple.input","class":"lineCov","hits":"4","order":"622","possible_hits":"0",},
{"lineNum":"  223","line":""},
{"lineNum":"  224","line":"}"},
{"lineNum":"  225","line":""},
{"lineNum":"  226","line":"function test-7-expected () {"},
{"lineNum":"  227","line":"\t# no-op in case content just a comment"},
{"lineNum":"  228","line":"\ttrue","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  229","line":""},
{"lineNum":"  230","line":"\tcat <<END_EXPECTED","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  231","line":"Entropy"},
{"lineNum":"  232","line":"2.000"},
{"lineNum":"  233","line":"END_EXPECTED"},
{"lineNum":"  234","line":"}"},
{"lineNum":"  235","line":""},
{"lineNum":"  236","line":""},
{"lineNum":"  237","line":"test_test-2d8() { bats_test_begin \"test-8\";"},
{"lineNum":"  238","line":"\ttestfolder=\"/tmp/batspp-201680/test-8\"","class":"lineCov","hits":"2","order":"623","possible_hits":"0",},
{"lineNum":"  239","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"624","possible_hits":"0",},
{"lineNum":"  240","line":"\tbuiltin cd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"625","possible_hits":"0",},
{"lineNum":"  241","line":""},
{"lineNum":"  242","line":"\techo \"==========\" $\'$calc_entropy $simple - < ./calc_entropy.simple.input2\\n\' \"==========\"","class":"lineCov","hits":"2","order":"626","possible_hits":"0",},
{"lineNum":"  243","line":"\ttest-8-actual","class":"lineCov","hits":"2","order":"627","possible_hits":"0",},
{"lineNum":"  244","line":"\techo \"=========\" $\'Entropy\\n1.497\' \"=========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  245","line":"\ttest-8-expected","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  246","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  247","line":"\t# ???: \'$calc_entropy $simple - < ./calc_entropy.simple.input2\\n\'=$(test-8-actual)"},
{"lineNum":"  248","line":"\t# ???: \'Entropy\\n1.497\'=$(test-8-expected)"},
{"lineNum":"  249","line":"\t[ \"$(test-8-actual)\" == \"$(test-8-expected)\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  250","line":"}"},
{"lineNum":"  251","line":""},
{"lineNum":"  252","line":"function test-8-actual () {"},
{"lineNum":"  253","line":"\t# no-op in case content just a comment"},
{"lineNum":"  254","line":"\ttrue","class":"lineCov","hits":"2","order":"628","possible_hits":"0",},
{"lineNum":"  255","line":""},
{"lineNum":"  256","line":"\t$calc_entropy $simple - < ./calc_entropy.simple.input2","class":"lineCov","hits":"4","order":"629","possible_hits":"0",},
{"lineNum":"  257","line":""},
{"lineNum":"  258","line":"}"},
{"lineNum":"  259","line":""},
{"lineNum":"  260","line":"function test-8-expected () {"},
{"lineNum":"  261","line":"\t# no-op in case content just a comment"},
{"lineNum":"  262","line":"\ttrue","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  263","line":""},
{"lineNum":"  264","line":"\tcat <<END_EXPECTED","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  265","line":"Entropy"},
{"lineNum":"  266","line":"1.497"},
{"lineNum":"  267","line":"END_EXPECTED"},
{"lineNum":"  268","line":"}"},
{"lineNum":"  269","line":""},
{"lineNum":"  270","line":""},
{"lineNum":"  271","line":"test_test-2d9() { bats_test_begin \"test-9\";"},
{"lineNum":"  272","line":"\ttestfolder=\"/tmp/batspp-201680/test-9\"","class":"lineCov","hits":"2","order":"630","possible_hits":"0",},
{"lineNum":"  273","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"631","possible_hits":"0",},
{"lineNum":"  274","line":"\tbuiltin cd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"632","possible_hits":"0",},
{"lineNum":"  275","line":""},
{"lineNum":"  276","line":"\techo \"==========\" $\'$calc_entropy $verbose $simple - < ./calc_entropy.simple.input2\\n\' \"==========\"","class":"lineCov","hits":"2","order":"633","possible_hits":"0",},
{"lineNum":"  277","line":"\ttest-9-actual","class":"lineCov","hits":"2","order":"634","possible_hits":"0",},
{"lineNum":"  278","line":"\techo \"=========\" $\'#\\tprob\\t-p lg(p)    max p\\n#--------------------------------\\n#\\t0.470\\t0.512\\n#\\t0.420\\t0.526\\n#\\t0.060\\t0.244\\n#\\t0.050\\t0.216\\n#--------------------------------\\n# word\\tclasses\\tfreq\\tentropy\\tmax_prob\\n#\\t1.000\\t1.497\\t   0.470\\nEntropy\\n1.497\' \"=========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  279","line":"\ttest-9-expected","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  280","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  281","line":"\t# ???: \'$calc_entropy $verbose $simple - < ./calc_entropy.simple.input2\\n\'=$(test-9-actual)"},
{"lineNum":"  282","line":"\t# ???: \'#\\tprob\\t-p lg(p)    max p\\n#--------------------------------\\n#\\t0.470\\t0.512\\n#\\t0.420\\t0.526\\n#\\t0.060\\t0.244\\n#\\t0.050\\t0.216\\n#--------------------------------\\n# word\\tclasses\\tfreq\\tentropy\\tmax_prob\\n#\\t1.000\\t1.497\\t   0.470\\nEntropy\\n1.497\'=$(test-9-expected)"},
{"lineNum":"  283","line":"\t[ \"$(test-9-actual)\" == \"$(test-9-expected)\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  284","line":"}"},
{"lineNum":"  285","line":""},
{"lineNum":"  286","line":"function test-9-actual () {"},
{"lineNum":"  287","line":"\t# no-op in case content just a comment"},
{"lineNum":"  288","line":"\ttrue","class":"lineCov","hits":"2","order":"635","possible_hits":"0",},
{"lineNum":"  289","line":""},
{"lineNum":"  290","line":"\t$calc_entropy $verbose $simple - < ./calc_entropy.simple.input2","class":"lineCov","hits":"4","order":"636","possible_hits":"0",},
{"lineNum":"  291","line":""},
{"lineNum":"  292","line":"}"},
{"lineNum":"  293","line":""},
{"lineNum":"  294","line":"function test-9-expected () {"},
{"lineNum":"  295","line":"\t# no-op in case content just a comment"},
{"lineNum":"  296","line":"\ttrue","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  297","line":""},
{"lineNum":"  298","line":"\tcat <<END_EXPECTED","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  299","line":"#\tprob\t-p lg(p)    max p"},
{"lineNum":"  300","line":"#--------------------------------"},
{"lineNum":"  301","line":"#\t0.470\t0.512"},
{"lineNum":"  302","line":"#\t0.420\t0.526"},
{"lineNum":"  303","line":"#\t0.060\t0.244"},
{"lineNum":"  304","line":"#\t0.050\t0.216"},
{"lineNum":"  305","line":"#--------------------------------"},
{"lineNum":"  306","line":"# word\tclasses\tfreq\tentropy\tmax_prob"},
{"lineNum":"  307","line":"#\t1.000\t1.497\t   0.470"},
{"lineNum":"  308","line":"Entropy"},
{"lineNum":"  309","line":"1.497"},
{"lineNum":"  310","line":"END_EXPECTED"},
{"lineNum":"  311","line":"}"},
{"lineNum":"  312","line":""},
{"lineNum":"  313","line":""},
{"lineNum":"  314","line":"test_test-2d10() { bats_test_begin \"test-10\";"},
{"lineNum":"  315","line":"\ttestfolder=\"/tmp/batspp-201680/test-10\"","class":"lineCov","hits":"2","order":"637","possible_hits":"0",},
{"lineNum":"  316","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"638","possible_hits":"0",},
{"lineNum":"  317","line":"\tbuiltin cd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"639","possible_hits":"0",},
{"lineNum":"  318","line":""},
{"lineNum":"  319","line":"\techo \"==========\" $\'$calc_entropy - < ./calc_entropy.input\\n\' \"==========\"","class":"lineCov","hits":"2","order":"640","possible_hits":"0",},
{"lineNum":"  320","line":"\ttest-10-actual","class":"lineCov","hits":"2","order":"641","possible_hits":"0",},
{"lineNum":"  321","line":"\techo \"=========\" $\'2.230\' \"=========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  322","line":"\ttest-10-expected","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  323","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  324","line":"\t# ???: \'$calc_entropy - < ./calc_entropy.input\\n\'=$(test-10-actual)"},
{"lineNum":"  325","line":"\t# ???: \'2.230\'=$(test-10-expected)"},
{"lineNum":"  326","line":"\t[ \"$(test-10-actual)\" == \"$(test-10-expected)\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  327","line":"}"},
{"lineNum":"  328","line":""},
{"lineNum":"  329","line":"function test-10-actual () {"},
{"lineNum":"  330","line":"\t# no-op in case content just a comment"},
{"lineNum":"  331","line":"\ttrue","class":"lineCov","hits":"2","order":"642","possible_hits":"0",},
{"lineNum":"  332","line":""},
{"lineNum":"  333","line":"\t$calc_entropy - < ./calc_entropy.input","class":"lineCov","hits":"4","order":"643","possible_hits":"0",},
{"lineNum":"  334","line":""},
{"lineNum":"  335","line":"}"},
{"lineNum":"  336","line":""},
{"lineNum":"  337","line":"function test-10-expected () {"},
{"lineNum":"  338","line":"\t# no-op in case content just a comment"},
{"lineNum":"  339","line":"\ttrue","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  340","line":""},
{"lineNum":"  341","line":"\tcat <<END_EXPECTED","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  342","line":"2.230"},
{"lineNum":"  343","line":"END_EXPECTED"},
{"lineNum":"  344","line":"}"},
{"lineNum":"  345","line":""},
{"lineNum":"  346","line":""},
{"lineNum":"  347","line":"test_test-2d11() { bats_test_begin \"test-11\";"},
{"lineNum":"  348","line":"\ttestfolder=\"/tmp/batspp-201680/test-11\"","class":"lineCov","hits":"2","order":"644","possible_hits":"0",},
{"lineNum":"  349","line":"\tmkdir --parents \"$testfolder\"","class":"lineCov","hits":"2","order":"645","possible_hits":"0",},
{"lineNum":"  350","line":"\tbuiltin cd \"$testfolder\" || echo Warning: Unable to \"cd $testfolder\"","class":"lineCov","hits":"2","order":"646","possible_hits":"0",},
{"lineNum":"  351","line":""},
{"lineNum":"  352","line":"\techo \"==========\" $\'$calc_entropy $verbose - < calc_entropy.input | encode-blank-line\\n\' \"==========\"","class":"lineCov","hits":"2","order":"647","possible_hits":"0",},
{"lineNum":"  353","line":"\ttest-11-actual","class":"lineCov","hits":"2","order":"648","possible_hits":"0",},
{"lineNum":"  354","line":"\techo \"=========\" $\'#\\t\\tclass\\tfreq\\tprob\\t-p lg(p)\\n#\\t\\tpp-tmp\\t42\\t0.350\\t0.530\\n#\\t\\tpp-loc\\t35\\t0.292\\t0.518\\n#\\t\\tpp-clr\\t24\\t0.200\\t0.464\\n#\\t\\tpp-prd\\t7\\t0.058\\t0.239\\n#\\t\\tpp-dir\\t6\\t0.050\\t0.216\\n#\\t\\tpp-ext\\t4\\t0.033\\t0.164\\n#\\t\\tpp-nom\\t2\\t0.017\\t0.098\\n#\\t\\ttotal\\t120\\t1.000\\t2.230\\n<NL>\\n# word\\tclasses\\tfreq\\tentropy\\tmax_prob\\n-\\t7\\t120\\t2.230\\t0.350\' \"=========\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  355","line":"\ttest-11-expected","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  356","line":"\techo \"============================\"","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  357","line":"\t# ???: \'$calc_entropy $verbose - < calc_entropy.input | encode-blank-line\\n\'=$(test-11-actual)"},
{"lineNum":"  358","line":"\t# ???: \'#\\t\\tclass\\tfreq\\tprob\\t-p lg(p)\\n#\\t\\tpp-tmp\\t42\\t0.350\\t0.530\\n#\\t\\tpp-loc\\t35\\t0.292\\t0.518\\n#\\t\\tpp-clr\\t24\\t0.200\\t0.464\\n#\\t\\tpp-prd\\t7\\t0.058\\t0.239\\n#\\t\\tpp-dir\\t6\\t0.050\\t0.216\\n#\\t\\tpp-ext\\t4\\t0.033\\t0.164\\n#\\t\\tpp-nom\\t2\\t0.017\\t0.098\\n#\\t\\ttotal\\t120\\t1.000\\t2.230\\n<NL>\\n# word\\tclasses\\tfreq\\tentropy\\tmax_prob\\n-\\t7\\t120\\t2.230\\t0.350\'=$(test-11-expected)"},
{"lineNum":"  359","line":"\t[ \"$(test-11-actual)\" == \"$(test-11-expected)\" ]","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  360","line":"}"},
{"lineNum":"  361","line":""},
{"lineNum":"  362","line":"function test-11-actual () {"},
{"lineNum":"  363","line":"\t# no-op in case content just a comment"},
{"lineNum":"  364","line":"\ttrue","class":"lineCov","hits":"2","order":"649","possible_hits":"0",},
{"lineNum":"  365","line":""},
{"lineNum":"  366","line":"\t$calc_entropy $verbose - < calc_entropy.input | encode-blank-line","class":"lineCov","hits":"6","order":"650","possible_hits":"0",},
{"lineNum":"  367","line":""},
{"lineNum":"  368","line":"}"},
{"lineNum":"  369","line":""},
{"lineNum":"  370","line":"function test-11-expected () {"},
{"lineNum":"  371","line":"\t# no-op in case content just a comment"},
{"lineNum":"  372","line":"\ttrue","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  373","line":""},
{"lineNum":"  374","line":"\tcat <<END_EXPECTED","class":"lineNoCov","hits":"0","possible_hits":"0",},
{"lineNum":"  375","line":"#\t\tclass\tfreq\tprob\t-p lg(p)"},
{"lineNum":"  376","line":"#\t\tpp-tmp\t42\t0.350\t0.530"},
{"lineNum":"  377","line":"#\t\tpp-loc\t35\t0.292\t0.518"},
{"lineNum":"  378","line":"#\t\tpp-clr\t24\t0.200\t0.464"},
{"lineNum":"  379","line":"#\t\tpp-prd\t7\t0.058\t0.239"},
{"lineNum":"  380","line":"#\t\tpp-dir\t6\t0.050\t0.216"},
{"lineNum":"  381","line":"#\t\tpp-ext\t4\t0.033\t0.164"},
{"lineNum":"  382","line":"#\t\tpp-nom\t2\t0.017\t0.098"},
{"lineNum":"  383","line":"#\t\ttotal\t120\t1.000\t2.230"},
{"lineNum":"  384","line":"<NL>"},
{"lineNum":"  385","line":"# word\tclasses\tfreq\tentropy\tmax_prob"},
{"lineNum":"  386","line":"-\t7\t120\t2.230\t0.350"},
{"lineNum":"  387","line":"END_EXPECTED"},
{"lineNum":"  388","line":"}"},
{"lineNum":"  389","line":""},
{"lineNum":"  390","line":"bats_test_function --tags \'\' test_test-2d1","class":"lineCov","hits":"12","order":"350","possible_hits":"0",},
{"lineNum":"  391","line":"bats_test_function --tags \'\' test_test-2d3","class":"lineCov","hits":"12","order":"351","possible_hits":"0",},
{"lineNum":"  392","line":"bats_test_function --tags \'\' test_test-2d4","class":"lineCov","hits":"12","order":"352","possible_hits":"0",},
{"lineNum":"  393","line":"bats_test_function --tags \'\' test_test-2d5","class":"lineCov","hits":"12","order":"353","possible_hits":"0",},
{"lineNum":"  394","line":"bats_test_function --tags \'\' test_test-2d6","class":"lineCov","hits":"12","order":"354","possible_hits":"0",},
{"lineNum":"  395","line":"bats_test_function --tags \'\' test_test-2d7","class":"lineCov","hits":"12","order":"355","possible_hits":"0",},
{"lineNum":"  396","line":"bats_test_function --tags \'\' test_test-2d8","class":"lineCov","hits":"12","order":"356","possible_hits":"0",},
{"lineNum":"  397","line":"bats_test_function --tags \'\' test_test-2d9","class":"lineCov","hits":"12","order":"357","possible_hits":"0",},
{"lineNum":"  398","line":"bats_test_function --tags \'\' test_test-2d10","class":"lineCov","hits":"12","order":"358","possible_hits":"0",},
{"lineNum":"  399","line":"bats_test_function --tags \'\' test_test-2d11","class":"lineCov","hits":"12","order":"359","possible_hits":"0",},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "bats", "date" : "2023-06-15 21:54:58", "instrumented" : 141, "covered" : 99,};
var merged_data = [];
