# Workflow for running locally (e.g., via https://github.com/nektos/act)
#
# Note:
# - Invoked via local-workflows.sh:
#     WORKFLOW_FILE=act.yml local-workflow.sh ...
# - This leads to the following type of invocation:
#     act --container-architecture linux/amd64 --pull="false" -P "ubuntu-latest=local/test-act" -W ./.github/workflows/act.yml
# - Based initially on tests.yml from Python mezcla package.
# - Requires special permission for Github workflows.
# - For more information see following:
#     https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
#     https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# - Based initially on version from https://github.com/LimaBD/batspp.
# - Running Github Actions with Docker: https://stackoverflow.com/a/64373702
# - Docker documentation:
#   https://docs.docker.com/engine/reference/commandline/cli/
#   https://docs.docker.com/storage/bind-mounts
#
# Warning:
# - *** Changes need to be synchronized in 3 places: Dockerfile, local-workflow.sh, and .github/workflow/*.yml!
#

name: Act-Tests

on: [push, pull_request]

jobs:
  build:
    name: Build and Run Tests
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        ## TODO: os: [ubuntu-20.04, ubuntu-latest]
        os: [ubuntu-20.04]
        ## TODO: python-version: ["3.8", "3.9", "3.10"]
        python-version: ["3.9"]

    ## TEST:
    ## NOTE: following is for images on the hub
    ## container:
    ##   image: shell-scripts-dev
    ##   options: --user=root

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build --tag shell-scripts-dev -f- . <Dockerfile

      - name: Configure Environment
        ## TODO2: clarify why used
        run: |
          echo "PATH=$PATH" >> $GITHUB_ENV
          echo "PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.9/dist-packages" >> $GITHUB_ENV

      - name: Run tests
        run: |
          docker run --rm --mount type=bind,source="$(pwd)",target=/home/shell-scripts shell-scripts-dev
