# Regular workflow for Github testing (n.b., runs remote on their servers)
#
# Note:
# - See act.yml for the local workflow file.
# - It also contains a bunch of tips.
#

name: Github-Tests

on: [push, pull_request]

jobs:

  build-and-test-runner:
    name: Build and Run Tests via Runner
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]
        ## TODO: os: [ubuntu-20.04, ubuntu-latest]
        ## TODO2: python-version: ["3.8", "3.9", "3.10"]
        ## NOTE: need to track down differences between Docker and Runner runs
        ## TEMP: disable tests (and just run Docker version below)
        python-version: []
        ## TODO: 3.x [latest; -or latest, latest-1, latest-2, ...]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          pip install --verbose --requirement requirements.txt

      - name: Run Python Tests under Runner
        run: |
          PYTHONPATH="$PWD:$PWD/tests:$PYTHONPATH" ./tests/run_tests.bash
          
  build-and-test-docker:
    name: Build and Run Tests via Docker
    runs-on: [ubuntu-20.04]

    ## TEST:
    ## NOTE: following is for docker images on the hub
    ## container:
    ##   image: shell-scripts-dev
    ##   options: --user=root

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build --tag shell-scripts-dev -f- . <Dockerfile

      - name: Run tests
        run: |
          docker run --rm --mount type=bind,source="$(pwd)",target=/home/shell-scripts shell-scripts-dev

