# Regular workflow for Github testing (n.b., runs remote on their servers)
#
# Note:
# - See act.yml for the local workflow file.
# - It also contains a bunch of tips.
#

name: Github-Tests

on: [push, pull_request]

jobs:
  build:
    name: Build and Run Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]
        ## TODO: os: [ubuntu-20.04, ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10"]
        ## TODO: 3.x [latest; -or latest, latest-1, latest-2, ...]

    ## TEST:
    ## NOTE: following is for docker images on the hub
    ## container:
    ##   image: shell-scripts-dev
    ##   options: --user=root

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build --tag shell-scripts-dev -f- . <Dockerfile

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          docker run --rm --mount type=bind,source="$(pwd)",target=/home/shell-scripts shell-scripts-dev
